/*
**
** The JavaScript code is generated by atscc2js
** The starting compilation time is: 2015-12-5: 10h:53m
**
*/

/* ATSextcode_beg() */
//
function
ats2js_worker_channeg0_new_file
  (file) { var chn = new Worker(file); return chn; }
//
/* ATSextcode_end() */

/* ATSextcode_beg() */
//
function
ats2js_worker_channeg0_close(chn) { return chn.terminate(); }
function
ats2js_worker_channeg1_close(chn) { return chn.terminate(); }
//
/* ATSextcode_end() */

/* ATSextcode_beg() */
//
function
ats2js_worker_channeg0_send(chn, k0)
{
  chn.onmessage =
  function(event)
    { return ats2jspre_cloref2_app(k0, chn, event.data); };
  return/*void*/;
}
function
ats2js_worker_channeg0_recv(chn, x0, k0)
{
  chn.postMessage(x0); return ats2jspre_cloref1_app(k0, chn);
}
//
function
ats2js_worker_channeg1_send
  (chn, k0)
{
  return ats2js_worker_channeg0_send(chn, k0);
}
function
ats2js_worker_channeg1_recv
  (chn, x0, k0)
{
  return ats2js_worker_channeg0_recv(chn, x0, k0);
}
//
/* ATSextcode_end() */

/* ATSextcode_beg() */
//
var
Start_clicks =
  $("#Start").asEventStream("click")
var
theResult_clicks =
  $("#theResult").asEventStream("click")
//
/* ATSextcode_end() */

/* ATSextcode_beg() */
//
function
theArg1_get()
{
  return parseInt(document.getElementById("theArg1_input").value);
}
function
theArg2_get()
{
  return parseInt(document.getElementById("theArg2_input").value);
}
function
theResult_set(output)
{
  return document.getElementById("theResult_output").value = output;
}
//
function
Start_reset()
{
  document.getElementById("theArg1_input").value = "";
  document.getElementById("theArg2_input").value = "";
  document.getElementById("theResult_output").value = "";
}
function
Start_output(msg)
{
  document.getElementById("Start_output").innerHTML = msg;
}
//
/* ATSextcode_end() */

/* ATSextcode_beg() */
//
var theAction_fwork0 = 0;
var theAction_fwork1 = 0;
//
function
theAction_fwork0_set(f0)
  { theAction_fwork0 = f0; return; }
function
theAction_fwork1_set(f1)
  { theAction_fwork1 = f1; return; }
function
theAction_fwork01_set(f0, f1)
  { theAction_fwork0 = f0; theAction_fwork1 = f1; return; }
//
function
theAction_fwork0_run()
{
  if(theAction_fwork0)
  {
     var f ;
     f = theAction_fwork0;
     theAction_fwork0 = 0; ats2jspre_cloref0_app(f);
  } ; return /* void */ ;
}
function
theAction_fwork1_run(x)
{
  if(theAction_fwork1) ats2jspre_cloref1_app(theAction_fwork1, x); return;
}
//
/* ATSextcode_end() */

var statmp32

function
__patsfun_23__closurerize()
{
  return [function(cenv, arg0) { return __patsfun_23(arg0); }];
}


function
__patsfun_24__closurerize()
{
  return [function(cenv, arg0) { return __patsfun_24(arg0); }];
}


function
__patsfun_25__closurerize()
{
  return [function(cenv, arg0) { return __patsfun_25(arg0); }];
}


function
__patsfun_28__closurerize(env0)
{
  return [function(cenv) { return __patsfun_28(cenv[1]); }, env0];
}


function
__patsfun_29__closurerize(env0)
{
  return [function(cenv, arg0) { return __patsfun_29(cenv[1], arg0); }, env0];
}


function
__patsfun_30__closurerize()
{
  return [function(cenv, arg0) { return __patsfun_30(arg0); }];
}


function
__patsfun_31__closurerize()
{
  return [function(cenv, arg0, arg1) { return __patsfun_31(arg0, arg1); }];
}


function
__patsfun_35__closurerize()
{
  return [function(cenv, arg0) { return __patsfun_35(arg0); }];
}


function
__patsfun_37__closurerize(env0)
{
  return [function(cenv) { return __patsfun_37(cenv[1]); }, env0];
}


function
__patsfun_39__closurerize()
{
  return [function(cenv, arg0) { return __patsfun_39(arg0); }];
}


function
__patsfun_23(arg0)
{
//
// knd = 0
  var tmp35
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_23
  tmp35 = 0;
  ats2js_bacon_EStream_bus_push(statmp32, tmp35);
  return/*_void*/;
} // end-of-function


function
__patsfun_24(arg0)
{
//
// knd = 0
  var tmp38
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_24
  tmp38 = 1;
  ats2js_bacon_EStream_bus_push(statmp32, tmp38);
  return/*_void*/;
} // end-of-function


function
__patsfun_25(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_25
  theAction_fwork1_run(arg0);
  return/*_void*/;
} // end-of-function


function
P_26(arg0)
{
//
// knd = 0
  var tmp54
  var tmp57
  var tmplab, tmplab_js
//
  // __patsflab_P_26
  tmp54 = __patsfun_28__closurerize(arg0);
  tmp57 = __patsfun_35__closurerize();
  theAction_fwork01_set(tmp54, tmp57);
  return/*_void*/;
} // end-of-function


function
theResult_process_27(arg0)
{
//
// knd = 0
  var tmp59
  var tmplab, tmplab_js
//
  // __patsflab_theResult_process_27
  if(arg0) {
    tmp59 = "true";
  } else {
    tmp59 = "false";
  } // endif
  theResult_set(tmp59);
  return/*_void*/;
} // end-of-function


function
__patsfun_28(env0)
{
//
// knd = 0
  var tmp43
  var tmp44
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_28
  tmp43 = theArg1_get();
  tmp44 = theArg2_get();
  ats2js_worker_channeg1_recv(env0, tmp43, __patsfun_29__closurerize(tmp44));
  return/*_void*/;
} // end-of-function


function
__patsfun_29(env0, arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_29
  ats2js_worker_channeg1_recv(arg0, env0, __patsfun_30__closurerize());
  return/*_void*/;
} // end-of-function


function
__patsfun_30(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_30
  ats2js_worker_channeg1_send(arg0, __patsfun_31__closurerize());
  return/*_void*/;
} // end-of-function


function
__patsfun_31(arg0, arg1)
{
//
// knd = 0
  var tmp48
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_31
  tmp48 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chmsg_parse__32__1(arg1);
  theResult_process_27(tmp48);
  Start_output("Session over!");
  ats2js_worker_channeg1_close(arg0);
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_EXAMPLE_057_EFFECTIVATS_057_ssntyped_055_channels_055_1_057_introxmpl1_client_056_dats__theSession_loop();
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chmsg_parse__32__1(arg0)
{
//
// knd = 0
  var tmpret49__1
  var tmplab, tmplab_js
//
  // __patsflab_chmsg_parse
  tmpret49__1 = arg0;
  return tmpret49__1;
} // end-of-function


function
fwork1_34(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_fwork1_34
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab12
      if(!ATSCKpat_con0(arg0, 1)) { tmplab_js = 3; break; }
      case 2: // __atstmplab13
      theAction_fwork0_run();
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab14
      ats2jspre_alert("The action is ignored!");
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
__patsfun_35(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_35
  fwork1_34(arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_EXAMPLE_057_EFFECTIVATS_057_ssntyped_055_channels_055_1_057_introxmpl1_client_056_dats__theSession_loop()
{
//
// knd = 0
  var tmp61
  var tmp63
  var tmp68
  var tmplab, tmplab_js
//
  // __patsflab_theSession_loop
  tmp61 = ats2js_worker_channeg0_new_file("./introxmpl1_server_dats_.js");
  tmp63 = __patsfun_37__closurerize(tmp61);
  tmp68 = __patsfun_39__closurerize();
  theAction_fwork01_set(tmp63, tmp68);
  return/*_void*/;
} // end-of-function


function
__patsfun_37(env0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_37
  P_26(env0);
  return/*_void*/;
} // end-of-function


function
fwork1_38(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_fwork1_38
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab15
      if(!ATSCKpat_con0(arg0, 0)) { tmplab_js = 3; break; }
      case 2: // __atstmplab16
      Start_reset();
      Start_output("Session is on!");
      theAction_fwork0_run();
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab17
      ats2jspre_alert("The action is ignored!");
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
__patsfun_39(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_39
  fwork1_38(arg0);
  return/*_void*/;
} // end-of-function

// dynloadflag_minit
var _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_EXAMPLE_057_EFFECTIVATS_057_ssntyped_055_channels_055_1_057_introxmpl1_client_056_dats__dynloadflag = 0;

function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_EXAMPLE_057_EFFECTIVATS_057_ssntyped_055_channels_055_1_057_introxmpl1_client_056_dats__dynload()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // ATSdynload()
  // ATSdynloadflag_sta(_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_EXAMPLE_057_EFFECTIVATS_057_ssntyped_055_channels_055_1_057_introxmpl1_client_056_dats__dynloadflag(118))
  if(ATSCKiseqz(_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_EXAMPLE_057_EFFECTIVATS_057_ssntyped_055_channels_055_1_057_introxmpl1_client_056_dats__dynloadflag)) {
    _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_EXAMPLE_057_EFFECTIVATS_057_ssntyped_055_channels_055_1_057_introxmpl1_client_056_dats__dynloadflag = 1 ; // flag is set
    statmp32 = ats2js_bacon_Bacon_new_bus();
    ats2js_bacon_EStream_onValue(Start_clicks, __patsfun_23__closurerize());
    ats2js_bacon_EStream_onValue(theResult_clicks, __patsfun_24__closurerize());
    ats2js_bacon_EStream_onValue(statmp32, __patsfun_25__closurerize());
    _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_EXAMPLE_057_EFFECTIVATS_057_ssntyped_055_channels_055_1_057_introxmpl1_client_056_dats__theSession_loop();
  } // endif
  return/*_void*/;
} // end-of-function


function
introxmpl1_client_initize()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_EXAMPLE_057_EFFECTIVATS_057_ssntyped_055_channels_055_1_057_introxmpl1_client_056_dats__dynload();
  return/*_void*/;
} // end-of-function


/* ATSextcode_beg() */
//
jQuery(document).ready(function(){introxmpl1_client_initize();});
//
/* ATSextcode_end() */

/* ****** ****** */

/* end-of-compilation-unit */
