/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2015-7-21: 21h:18m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_rec_0 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_1 ;

typedef
struct {
ats_ptr_type atslab_p2at_loc ;
ats_ptr_type atslab_p2at_svs ;
ats_ptr_type atslab_p2at_dvs ;
ats_ptr_type atslab_p2at_type ;
ats_ptr_type atslab_p2at_node ;
} anairiats_rec_2 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_3 ;

typedef
struct {
ats_ptr_type atslab_d2exp_loc ;
ats_ptr_type atslab_d2exp_node ;
ats_ptr_type atslab_d2exp_type ;
} anairiats_rec_4 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_5 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_int_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_6 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
} anairiats_sum_7 ;

typedef
struct {
ats_ptr_type atslab_p1at_loc ;
ats_ptr_type atslab_p1at_node ;
} anairiats_rec_8 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_9 ;

typedef struct {
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_10 ;

typedef
struct {
ats_ptr_type atslab_d1exp_loc ;
ats_ptr_type atslab_d1exp_node ;
} anairiats_rec_11 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_12 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_13 ;

typedef
struct {
ats_ptr_type atslab_d2lab_loc ;
ats_ptr_type atslab_d2lab_node ;
ats_ptr_type atslab_d2lab_overld ;
} anairiats_rec_14 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_nil_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__None_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_vt_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_vt_nil_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_syntax_2esats__DL0ABELED_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__P1Tlist_14) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__D1Elam_dyn_51) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__D1Elam_met_53) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__D1Elam_sta_ana_54) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__D1Elam_sta_syn_55) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__LABP2ATnorm_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Evar_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eint_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Ebool_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Echar_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Estring_7) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Ei0nt_8) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Ec0har_9) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Es0tring_11) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Etop_12) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Esing_32) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Etup_35) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Erec_36) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eselab_38) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eviewat_40) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Ederef_41) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Earrsub_44) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eexist_52) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Elam_dyn_53) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Elam_sta_56) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2LVALderef_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2LVALvar_lin_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2LVALvar_mut_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2LVALarrsub_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2LVALviewat_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2LVALnone_5) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_int_type, atspre_add_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_idiv) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_mul2_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_zero_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_funenv_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_cloenv_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_split_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(anairiats_rec_0, atspre_array_ptr_takeout2_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_foreach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_iforeach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array2_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atslib_qsort) (ats_ref_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_label_2esats__label_make_int) (ats_int_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__location_combine) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_syntax_2esats__l0ab_make_label) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__d2con_get_arity_full) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2cst_get_artylst) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2var_is_linear) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2var_is_mutabl) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_selab) (ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_lvalize) (ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____copy_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____free_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_ptr_type aux_1 (ats_ptr_type arg0, ats_int_type arg1) ;
static
ats_bool_type aux_3 (ats_ptr_type arg0) ;
static
ats_bool_type auxlst_4 (ats_ptr_type arg0) ;
static
ats_bool_type auxlablst_5 (ats_ptr_type arg0) ;
static
ats_int_type loop_8 (ats_ptr_type arg0, ats_int_type arg1) ;
static
ats_int_type list_length_01410_ats_ptr_type (ats_ptr_type arg0) ;
static
ats_bool_type __ats_fun_9 (ats_int_type env0, ats_ptr_type arg0) ;
static
ats_clo_ptr_type __ats_fun_9_closure_make (ats_int_type env0) ;
static
ats_bool_type __ats_fun_9_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) ;
static
ats_bool_type app_11 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_void_type loop_13 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2, ats_ptr_type arg3) ;
static
ats_ptr_type list_filter_funenv_01338_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;
static
ats_ptr_type list_filter_vclo_01340_ats_ptr_type (ats_ptr_type arg0, ats_ref_type arg1) ;
static
ats_ptr_type d2exp_d2var_lvalize_14 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;
static
ats_int_type p1at_arity_16 (ats_ptr_type arg0) ;
static
ats_bool_type loop1_18 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_bool_type loop2_19 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) ;
static
ats_bool_type loop1_18_0loop2_19 (ats_int_type arg0, ...) ;
static
ats_bool_type aritest_17 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type aux_23 (ats_ptr_type arg0) ;
static
ats_ptr_type aux2_24 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type revapp_29 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type list_vt_reverse_append_01507_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type list_vt_reverse_01506_ats_ptr_type (ats_ptr_type arg0) ;
static
ats_ptr_type aux_26 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 1999(line=82, offs=1) -- 2370(line=96, offs=39)
*/
ATSstaticdec()
ats_ptr_type
aux_1 (ats_ptr_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp1) ;
ATSlocal (ats_ptr_type, tmp2) ;
ATSlocal (ats_ptr_type, tmp3) ;
ATSlocal (ats_ptr_type, tmp4) ;
ATSlocal (ats_ptr_type, tmp5) ;
ATSlocal (ats_ptr_type, tmp6) ;
ATSlocal (ats_ptr_type, tmp7) ;
ATSlocal (ats_ptr_type, tmp8) ;
ATSlocal (ats_int_type, tmp9) ;

__ats_lab_aux_1:
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp2 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
tmp3 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_1) ;
tmp4 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_2, tmp2), atslab_p2at_loc) ;
tmp5 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_label_2esats__label_make_int (arg1) ;
tmp6 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_syntax_2esats__l0ab_make_label (tmp4, tmp5) ;
tmp7 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp7)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_3, tmp7, atslab_0, tmp6) ;
ats_selptrset_mac(anairiats_sum_3, tmp7, atslab_1, tmp2) ;
tmp9 = atspre_add_int_int (arg1, 1) ;
tmp8 = aux_1 (tmp3, tmp9) ;
tmp1 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
ats_selptrset_mac(anairiats_sum_1, tmp1, atslab_0, tmp7) ;
ats_selptrset_mac(anairiats_sum_1, tmp1, atslab_1, tmp8) ;
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_1_1:
tmp1 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp1) ;
} /* end of [aux_1] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 1979(line=79, offs=3) -- 2412(line=101, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__p2atlst_tupize (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp0) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__p2atlst_tupize:
tmp0 = aux_1 (arg0, 0) ;
return (tmp0) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__p2atlst_tupize] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 2513(line=110, offs=1) -- 3095(line=146, offs=4)
*/
ATSstaticdec()
ats_bool_type
aux_3 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp11) ;
ATSlocal (ats_ptr_type, tmp12) ;
ATSlocal (ats_ptr_type, tmp13) ;
ATSlocal (ats_bool_type, tmp14) ;
ATSlocal (ats_ptr_type, tmp15) ;
ATSlocal (ats_ptr_type, tmp16) ;
ATSlocal (ats_ptr_type, tmp17) ;
ATSlocal (ats_ptr_type, tmp18) ;

__ats_lab_aux_3:
tmp12 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_4, arg0), atslab_d2exp_node) ;
do {
/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (((ats_sum_ptr_type)tmp12)->tag != 1) { goto __ats_lab_3_0 ; }
__ats_lab_2_1:
tmp13 = ats_caselptrlab_mac(anairiats_sum_5, tmp12, atslab_0) ;
tmp14 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2var_is_mutabl (tmp13) ;
if (tmp14) {
tmp11 = ats_false_bool ;
} else {
tmp11 = ats_true_bool ;
} /* end of [if] */
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
if (((ats_sum_ptr_type)tmp12)->tag != 53) { goto __ats_lab_4_0 ; }
__ats_lab_3_1:
tmp11 = ats_true_bool ;
break ;

/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (((ats_sum_ptr_type)tmp12)->tag != 56) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
tmp11 = ats_true_bool ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
if (((ats_sum_ptr_type)tmp12)->tag != 2) { goto __ats_lab_6_0 ; }
__ats_lab_5_1:
tmp11 = ats_true_bool ;
break ;

/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (((ats_sum_ptr_type)tmp12)->tag != 4) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
tmp11 = ats_true_bool ;
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
if (((ats_sum_ptr_type)tmp12)->tag != 5) { goto __ats_lab_8_0 ; }
__ats_lab_7_1:
tmp11 = ats_true_bool ;
break ;

/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (((ats_sum_ptr_type)tmp12)->tag != 7) { goto __ats_lab_9_0 ; }
__ats_lab_8_1:
tmp11 = ats_true_bool ;
break ;

/* branch: __ats_lab_9 */
__ats_lab_9_0:
if (((ats_sum_ptr_type)tmp12)->tag != 8) { goto __ats_lab_10_0 ; }
__ats_lab_9_1:
tmp11 = ats_true_bool ;
break ;

/* branch: __ats_lab_10 */
__ats_lab_10_0:
if (((ats_sum_ptr_type)tmp12)->tag != 9) { goto __ats_lab_11_0 ; }
__ats_lab_10_1:
tmp11 = ats_true_bool ;
break ;

/* branch: __ats_lab_11 */
__ats_lab_11_0:
if (((ats_sum_ptr_type)tmp12)->tag != 11) { goto __ats_lab_12_0 ; }
__ats_lab_11_1:
tmp11 = ats_true_bool ;
break ;

/* branch: __ats_lab_12 */
__ats_lab_12_0:
if (((ats_sum_ptr_type)tmp12)->tag != 12) { goto __ats_lab_13_0 ; }
__ats_lab_12_1:
tmp11 = ats_true_bool ;
break ;

/* branch: __ats_lab_13 */
__ats_lab_13_0:
if (((ats_sum_ptr_type)tmp12)->tag != 32) { goto __ats_lab_14_0 ; }
__ats_lab_13_1:
tmp15 = ats_caselptrlab_mac(anairiats_sum_5, tmp12, atslab_0) ;
arg0 = tmp15 ;
goto __ats_lab_aux_3 ; // tail call
break ;

/* branch: __ats_lab_14 */
__ats_lab_14_0:
if (((ats_sum_ptr_type)tmp12)->tag != 35) { goto __ats_lab_15_0 ; }
__ats_lab_14_1:
tmp16 = ats_caselptrlab_mac(anairiats_sum_6, tmp12, atslab_2) ;
tmp11 = auxlst_4 (tmp16) ;
break ;

/* branch: __ats_lab_15 */
__ats_lab_15_0:
if (((ats_sum_ptr_type)tmp12)->tag != 36) { goto __ats_lab_16_0 ; }
__ats_lab_15_1:
tmp17 = ats_caselptrlab_mac(anairiats_sum_6, tmp12, atslab_2) ;
tmp11 = auxlablst_5 (tmp17) ;
break ;

/* branch: __ats_lab_16 */
__ats_lab_16_0:
if (((ats_sum_ptr_type)tmp12)->tag != 52) { goto __ats_lab_17_0 ; }
__ats_lab_16_1:
tmp18 = ats_caselptrlab_mac(anairiats_sum_3, tmp12, atslab_1) ;
arg0 = tmp18 ;
goto __ats_lab_aux_3 ; // tail call
break ;

/* branch: __ats_lab_17 */
__ats_lab_17_0:
__ats_lab_17_1:
tmp11 = ats_false_bool ;
break ;
} while (0) ;
return (tmp11) ;
} /* end of [aux_3] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 3119(line=149, offs=1) -- 3291(line=159, offs=2)
*/
ATSstaticdec()
ats_bool_type
auxlst_4 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp19) ;
ATSlocal (ats_ptr_type, tmp20) ;
ATSlocal (ats_ptr_type, tmp21) ;
ATSlocal (ats_bool_type, tmp22) ;

__ats_lab_auxlst_4:
do {
/* branch: __ats_lab_18 */
__ats_lab_18_0:
if (arg0 != (ats_sum_ptr_type)0) { goto __ats_lab_19_0 ; }
__ats_lab_18_1:
tmp19 = ats_true_bool ;
break ;

/* branch: __ats_lab_19 */
__ats_lab_19_0:
// if (arg0 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_19_1:
tmp20 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
tmp21 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_1) ;
tmp22 = aux_3 (tmp20) ;
if (tmp22) {
arg0 = tmp21 ;
goto __ats_lab_auxlst_4 ; // tail call
} else {
tmp19 = ats_false_bool ;
} /* end of [if] */
break ;
} while (0) ;
return (tmp19) ;
} /* end of [auxlst_4] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 3299(line=162, offs=1) -- 3540(line=175, offs=2)
*/
ATSstaticdec()
ats_bool_type
auxlablst_5 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp23) ;
ATSlocal (ats_ptr_type, tmp24) ;
ATSlocal (ats_ptr_type, tmp25) ;
ATSlocal (ats_ptr_type, tmp26) ;
ATSlocal (ats_bool_type, tmp27) ;

__ats_lab_auxlablst_5:
do {
/* branch: __ats_lab_20 */
__ats_lab_20_0:
if (arg0 != (ats_sum_ptr_type)0) { goto __ats_lab_21_0 ; }
__ats_lab_20_1:
tmp23 = ats_true_bool ;
break ;

/* branch: __ats_lab_21 */
__ats_lab_21_0:
// if (arg0 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_21_1:
tmp24 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
tmp25 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_1) ;

tmp26 = ats_caselptrlab_mac(anairiats_sum_1, tmp24, atslab_1) ;
tmp27 = aux_3 (tmp26) ;
if (tmp27) {
arg0 = tmp25 ;
goto __ats_lab_auxlablst_5 ; // tail call
} else {
tmp23 = ats_false_bool ;
} /* end of [if] */
break ;
} while (0) ;
return (tmp23) ;
} /* end of [auxlablst_5] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 2493(line=107, offs=3) -- 3562(line=179, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_is_varlamcst (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp10) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_is_varlamcst:
tmp10 = aux_3 (arg0) ;
return (tmp10) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_is_varlamcst] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 51781(line=1842, offs=7) -- 51921(line=1845, offs=6)
*/
ATSstaticdec()
ats_int_type
loop_8 (ats_ptr_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp31) ;
ATSlocal (ats_ptr_type, tmp32) ;
ATSlocal (ats_int_type, tmp33) ;

__ats_lab_loop_8:
do {
/* branch: __ats_lab_22 */
__ats_lab_22_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_23_0 ; }
__ats_lab_22_1:
tmp32 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_1) ;
tmp33 = atspre_isucc (arg1) ;
arg0 = tmp32 ;
arg1 = tmp33 ;
goto __ats_lab_loop_8 ; // tail call
break ;

/* branch: __ats_lab_23 */
__ats_lab_23_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_23_1:
tmp31 = arg1 ;
break ;
} while (0) ;
return (tmp31) ;
} /* end of [loop_8] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 51764(line=1841, offs=13) -- 52005(line=1849, offs=4)
*/
ATSstaticdec()
ats_int_type
list_length_01410_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp30) ;

__ats_lab_list_length_01410_ats_ptr_type:
tmp30 = loop_8 (arg0, 0) ;
return (tmp30) ;
} /* end of [list_length_01410_ats_ptr_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 3745(line=194, offs=3) -- 3830(line=196, offs=50)
*/
ATSstaticdec()
ats_bool_type
__ats_fun_9 (ats_int_type env0, ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp36) ;
ATSlocal (ats_int_type, tmp37) ;

__ats_lab___ats_fun_9:
tmp37 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__d2con_get_arity_full (arg0) ;
tmp36 = atspre_eq_int_int (tmp37, env0) ;
return (tmp36) ;
} /* end of [__ats_fun_9] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_int_type closure_env_0 ;
} __ats_fun_9_closure_type ;

ats_bool_type
__ats_fun_9_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) {
return __ats_fun_9 (((__ats_fun_9_closure_type*)cloptr)->closure_env_0, arg0) ;
} /* end of function */

ATSinline()
ats_void_type
__ats_fun_9_closure_init (__ats_fun_9_closure_type *p_clo, ats_int_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&__ats_fun_9_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 21113(line=764, offs=6) -- 21259(line=768, offs=6)
*/
ATSstaticdec()
ats_bool_type
app_11 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp41) ;

__ats_lab_app_11:
tmp41 = ((ats_bool_type(*)(ats_clo_ptr_type, ats_ptr_type))(ats_closure_fun(arg1))) (arg1, arg0) ;
return (tmp41) ;
} /* end of [app_11] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 19833(line=716, offs=7) -- 20397(line=733, offs=40)
*/
ATSstaticdec()
ats_void_type
loop_13 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2, ats_ptr_type arg3) {
/* local vardec */
// ATSlocal_void (tmp43) ;
ATSlocal (ats_ptr_type, tmp44) ;
ATSlocal (ats_ptr_type, tmp45) ;
ATSlocal (ats_bool_type, tmp46) ;
ATSlocal (ats_ptr_type, tmp47) ;
ATSlocal (ats_ptr_type, tmp48) ;
ATSlocal (ats_ptr_type, tmp49) ;

__ats_lab_loop_13:
do {
/* branch: __ats_lab_24 */
__ats_lab_24_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_25_0 ; }
__ats_lab_24_1:
tmp44 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
tmp45 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_1) ;
tmp46 = ((ats_bool_type(*)(ats_ptr_type, ats_ptr_type))arg1) (tmp44, arg3) ;
if (tmp46) {
tmp47 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
ats_selptrset_mac(anairiats_sum_1, tmp47, atslab_0, tmp44) ;
ats_ptrget_mac(ats_ptr_type, arg2) = tmp47 ;
// if (ats_ptrget_mac(ats_ptr_type, arg2) == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
tmp48 = &ats_caselptrlab_mac(anairiats_sum_1, ats_ptrget_mac(ats_ptr_type, arg2), atslab_1) ;
arg0 = tmp45 ;
arg1 = arg1 ;
arg2 = tmp48 ;
arg3 = arg3 ;
goto __ats_lab_loop_13 ; // tail call
} else {
arg0 = tmp45 ;
arg1 = arg1 ;
arg2 = arg2 ;
arg3 = arg3 ;
goto __ats_lab_loop_13 ; // tail call
} /* end of [if] */
break ;

/* branch: __ats_lab_25 */
__ats_lab_25_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_25_1:
tmp49 = (ats_sum_ptr_type)0 ;
ats_ptrget_mac(ats_ptr_type, arg2) = tmp49 ;
break ;
} while (0) ;
return /* (tmp43) */ ;
} /* end of [loop_13] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 19800(line=714, offs=24) -- 20566(line=744, offs=4)
*/
ATSstaticdec()
ats_ptr_type
list_filter_funenv_01338_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp42) ;
ATSlocal (ats_ptr_type, tmp50) ;
// ATSlocal_void (tmp51) ;

__ats_lab_list_filter_funenv_01338_ats_ptr_type:
/* ats_ptr_type tmp50 ; */
/* tmp51 = */ loop_13 (arg0, arg1, (&tmp50), arg2) ;
tmp42 = tmp50 ;
return (tmp42) ;
} /* end of [list_filter_funenv_01338_ats_ptr_type] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 20978(line=760, offs=19) -- 21434(line=775, offs=4)
*/
ATSstaticdec()
ats_ptr_type
list_filter_vclo_01340_ats_ptr_type (ats_ptr_type arg0, ats_ref_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp40) ;

__ats_lab_list_filter_vclo_01340_ats_ptr_type:
tmp40 = list_filter_funenv_01338_ats_ptr_type (arg0, &app_11, arg1) ;
return (tmp40) ;
} /* end of [list_filter_vclo_01340_ats_ptr_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 3647(line=185, offs=3) -- 4089(line=209, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2con_select_arity (ats_ptr_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp28) ;
ATSlocal (ats_int_type, tmp29) ;
ATSlocal (ats_bool_type, tmp34) ;
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (__ats_fun_9_closure_type, tmp38) ;
ATSlocal (ats_ptr_type, tmp39) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2con_select_arity:
tmp29 = list_length_01410_ats_ptr_type (arg0) ;
tmp34 = atspre_igte (tmp29, 2) ;
if (tmp34) {
/* ats_ptr_type tmp35 ; */
tmp35 = &(tmp38) ;
__ats_fun_9_closure_init (tmp35, arg1) ; // closure initialization
tmp39 = list_filter_vclo_01340_ats_ptr_type (arg0, tmp35) ;
do {
/* branch: __ats_lab_26 */
__ats_lab_26_0:
if (ats_castfn_mac(ats_ptr_type, tmp39) == (ats_sum_ptr_type)0) { goto __ats_lab_27_0 ; }
__ats_lab_26_1:
tmp28 = ats_castfn_mac(ats_ptr_type, tmp39) ;
break ;

/* branch: __ats_lab_27 */
__ats_lab_27_0:
// if (ats_castfn_mac(ats_ptr_type, tmp39) != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_27_1:
tmp28 = arg0 ;
break ;
} while (0) ;
} else {
tmp28 = arg0 ;
} /* end of [if] */
return (tmp28) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2con_select_arity] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 4154(line=216, offs=1) -- 4394(line=223, offs=27)
*/
ATSstaticdec()
ats_ptr_type
d2exp_d2var_lvalize_14 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp52) ;
ATSlocal (ats_bool_type, tmp53) ;
ATSlocal (ats_bool_type, tmp54) ;

__ats_lab_d2exp_d2var_lvalize_14:
do {
/* branch: __ats_lab_28 */
__ats_lab_28_0:
__ats_lab_28_1:
tmp53 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2var_is_linear (arg1) ;
if (!tmp53) { goto __ats_lab_29_1 ; }
tmp52 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp52)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_3, tmp52, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_3, tmp52, atslab_1, arg2) ;
break ;

/* branch: __ats_lab_29 */
__ats_lab_29_0:
__ats_lab_29_1:
tmp54 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2var_is_mutabl (arg1) ;
if (!tmp54) { goto __ats_lab_30_1 ; }
tmp52 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp52)->tag = 2 ;
ats_selptrset_mac(anairiats_sum_3, tmp52, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_3, tmp52, atslab_1, arg2) ;
break ;

/* branch: __ats_lab_30 */
__ats_lab_30_0:
__ats_lab_30_1:
tmp52 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
((ats_sum_ptr_type)tmp52)->tag = 5 ;
ats_selptrset_mac(anairiats_sum_5, tmp52, atslab_0, arg0) ;
break ;
} while (0) ;
return (tmp52) ;
} /* end of [d2exp_d2var_lvalize_14] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 4484(line=230, offs=3) -- 5201(line=267, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_lvalize (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp55) ;
ATSlocal (ats_ptr_type, tmp56) ;
ATSlocal (ats_ptr_type, tmp57) ;
ATSlocal (ats_ptr_type, tmp58) ;
ATSlocal (ats_ptr_type, tmp59) ;
ATSlocal (ats_ptr_type, tmp60) ;
ATSlocal (ats_ptr_type, tmp61) ;
ATSlocal (ats_ptr_type, tmp62) ;
ATSlocal (ats_ptr_type, tmp63) ;
ATSlocal (ats_ptr_type, tmp64) ;
ATSlocal (ats_ptr_type, tmp65) ;
ATSlocal (ats_ptr_type, tmp66) ;
ATSlocal (ats_ptr_type, tmp67) ;
ATSlocal (ats_ptr_type, tmp68) ;
ATSlocal (ats_ptr_type, tmp69) ;
ATSlocal (ats_ptr_type, tmp70) ;
ATSlocal (ats_ptr_type, tmp71) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_lvalize:
tmp56 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_4, arg0), atslab_d2exp_node) ;
do {
/* branch: __ats_lab_31 */
__ats_lab_31_0:
if (((ats_sum_ptr_type)tmp56)->tag != 1) { goto __ats_lab_32_0 ; }
__ats_lab_31_1:
tmp57 = ats_caselptrlab_mac(anairiats_sum_5, tmp56, atslab_0) ;
tmp58 = (ats_sum_ptr_type)0 ;
tmp55 = d2exp_d2var_lvalize_14 (arg0, tmp57, tmp58) ;
break ;

/* branch: __ats_lab_32 */
__ats_lab_32_0:
if (((ats_sum_ptr_type)tmp56)->tag != 41) { goto __ats_lab_33_0 ; }
__ats_lab_32_1:
tmp59 = ats_caselptrlab_mac(anairiats_sum_5, tmp56, atslab_0) ;
tmp60 = (ats_sum_ptr_type)0 ;
tmp55 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp55)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_3, tmp55, atslab_0, tmp59) ;
ats_selptrset_mac(anairiats_sum_3, tmp55, atslab_1, tmp60) ;
break ;

/* branch: __ats_lab_33 */
__ats_lab_33_0:
if (((ats_sum_ptr_type)tmp56)->tag != 38) { goto __ats_lab_37_0 ; }
__ats_lab_33_1:
tmp61 = ats_caselptrlab_mac(anairiats_sum_3, tmp56, atslab_0) ;
tmp62 = ats_caselptrlab_mac(anairiats_sum_3, tmp56, atslab_1) ;
tmp63 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_4, tmp61), atslab_d2exp_node) ;
do {
/* branch: __ats_lab_34 */
__ats_lab_34_0:
if (((ats_sum_ptr_type)tmp63)->tag != 1) { goto __ats_lab_35_0 ; }
__ats_lab_34_1:
tmp64 = ats_caselptrlab_mac(anairiats_sum_5, tmp63, atslab_0) ;
tmp55 = d2exp_d2var_lvalize_14 (arg0, tmp64, tmp62) ;
break ;

/* branch: __ats_lab_35 */
__ats_lab_35_0:
if (((ats_sum_ptr_type)tmp63)->tag != 41) { goto __ats_lab_36_0 ; }
__ats_lab_35_1:
tmp65 = ats_caselptrlab_mac(anairiats_sum_5, tmp63, atslab_0) ;
tmp55 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp55)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_3, tmp55, atslab_0, tmp65) ;
ats_selptrset_mac(anairiats_sum_3, tmp55, atslab_1, tmp62) ;
break ;

/* branch: __ats_lab_36 */
__ats_lab_36_0:
__ats_lab_36_1:
tmp55 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
((ats_sum_ptr_type)tmp55)->tag = 5 ;
ats_selptrset_mac(anairiats_sum_5, tmp55, atslab_0, arg0) ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_37 */
__ats_lab_37_0:
if (((ats_sum_ptr_type)tmp56)->tag != 40) { goto __ats_lab_38_0 ; }
__ats_lab_37_1:
tmp66 = ats_caselptrlab_mac(anairiats_sum_5, tmp56, atslab_0) ;
tmp55 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
((ats_sum_ptr_type)tmp55)->tag = 4 ;
ats_selptrset_mac(anairiats_sum_5, tmp55, atslab_0, tmp66) ;
break ;

/* branch: __ats_lab_38 */
__ats_lab_38_0:
if (((ats_sum_ptr_type)tmp56)->tag != 44) { goto __ats_lab_39_0 ; }
__ats_lab_38_1:
tmp67 = ats_caselptrlab_mac(anairiats_sum_7, tmp56, atslab_0) ;
tmp68 = ats_caselptrlab_mac(anairiats_sum_7, tmp56, atslab_1) ;
tmp69 = ats_caselptrlab_mac(anairiats_sum_7, tmp56, atslab_2) ;
tmp70 = ats_caselptrlab_mac(anairiats_sum_7, tmp56, atslab_3) ;
tmp55 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
((ats_sum_ptr_type)tmp55)->tag = 3 ;
ats_selptrset_mac(anairiats_sum_7, tmp55, atslab_0, tmp67) ;
ats_selptrset_mac(anairiats_sum_7, tmp55, atslab_1, tmp68) ;
ats_selptrset_mac(anairiats_sum_7, tmp55, atslab_2, tmp69) ;
ats_selptrset_mac(anairiats_sum_7, tmp55, atslab_3, tmp70) ;
break ;

/* branch: __ats_lab_39 */
__ats_lab_39_0:
if (((ats_sum_ptr_type)tmp56)->tag != 32) { goto __ats_lab_40_0 ; }
__ats_lab_39_1:
tmp71 = ats_caselptrlab_mac(anairiats_sum_5, tmp56, atslab_0) ;
arg0 = tmp71 ;
goto __ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_lvalize ; // tail call
break ;

/* branch: __ats_lab_40 */
__ats_lab_40_0:
__ats_lab_40_1:
tmp55 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
((ats_sum_ptr_type)tmp55)->tag = 5 ;
ats_selptrset_mac(anairiats_sum_5, tmp55, atslab_0, arg0) ;
break ;
} while (0) ;
return (tmp55) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_lvalize] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 5310(line=277, offs=4) -- 5425(line=282, offs=2)
*/
ATSstaticdec()
ats_int_type
p1at_arity_16 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp72) ;
ATSlocal (ats_ptr_type, tmp73) ;
ATSlocal (ats_ptr_type, tmp74) ;

__ats_lab_p1at_arity_16:
tmp73 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_8, arg0), atslab_p1at_node) ;
do {
/* branch: __ats_lab_41 */
__ats_lab_41_0:
if (((ats_sum_ptr_type)tmp73)->tag != 14) { goto __ats_lab_42_0 ; }
__ats_lab_41_1:
tmp74 = ats_caselptrlab_mac(anairiats_sum_9, tmp73, atslab_1) ;
tmp72 = list_length_01410_ats_ptr_type (tmp74) ;
break ;

/* branch: __ats_lab_42 */
__ats_lab_42_0:
__ats_lab_42_1:
tmp72 = 1 ;
break ;
} while (0) ;
return (tmp72) ;
} /* end of [p1at_arity_16] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 5509(line=286, offs=7) -- 5646(line=292, offs=46)
*/
ATSstaticdec()
ats_bool_type
loop1_18 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp94) ;

tmp94 = loop1_18_0loop2_19 (0, arg0, arg1) ;
return (tmp94) ;
} /* end of [loop1_18] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 5673(line=294, offs=7) -- 6080(line=307, offs=32)
*/
ATSstaticdec()
ats_bool_type
loop2_19 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_bool_type, tmp95) ;

tmp95 = loop1_18_0loop2_19 (1, arg0, arg1, arg2) ;
return (tmp95) ;
} /* end of [loop2_19] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 5509(line=286, offs=7) -- 6080(line=307, offs=32)
*/
ATSstaticdec()
ats_bool_type
loop1_18_0loop2_19 (ats_int_type arg0, ...) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp76) ;
ATSlocal (ats_ptr_type, tmp77) ;
ATSlocal (ats_ptr_type, tmp78) ;
ATSlocal (ats_int_type, tmp79) ;
ATSlocal (ats_ptr_type, tmp80) ;
ATSlocal (ats_bool_type, tmp81) ;
ATSlocal (ats_int_type, tmp82) ;
ATSlocal (ats_ptr_type, tmp83) ;
ATSlocal (ats_bool_type, tmp84) ;
ATSlocal (ats_ptr_type, tmp85) ;
ATSlocal (ats_ptr_type, tmp86) ;
ATSlocal (ats_ptr_type, tmp87) ;
ATSlocal (ats_bool_type, tmp88) ;
ATSlocal (ats_int_type, tmp89) ;
ATSlocal (ats_ptr_type, tmp90) ;
ATSlocal (ats_ptr_type, tmp91) ;
ATSlocal (ats_ptr_type, tmp92) ;
ATSlocal (ats_bool_type, tmp93) ;

va_list funarg ;

switch (arg0) {
case 0:
va_start(funarg, arg0) ;
tmp76 = va_arg(funarg, ats_ptr_type) ;
tmp77 = va_arg(funarg, ats_ptr_type) ;
va_end(funarg) ;
goto __ats_lab_loop1_18 ;

case 1:
va_start(funarg, arg0) ;
tmp78 = va_arg(funarg, ats_ptr_type) ;
tmp79 = va_arg(funarg, ats_int_type) ;
tmp80 = va_arg(funarg, ats_ptr_type) ;
va_end(funarg) ;
goto __ats_lab_loop2_19 ;

default: exit(1) ; /* deadcode */
} /* end of switch */

ATSlocal (va_list, arg1) ;
va_start(arg1, arg0) ;

__ats_lab_loop1_18:
do {
/* branch: __ats_lab_43 */
__ats_lab_43_0:
if (tmp77 != (ats_sum_ptr_type)0) { goto __ats_lab_44_0 ; }
__ats_lab_43_1:
tmp81 = ats_true_bool ;
break ;

/* branch: __ats_lab_44 */
__ats_lab_44_0:
// if (tmp77 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_44_1:
tmp82 = ats_caselptrlab_mac(anairiats_sum_10, tmp77, atslab_0) ;
tmp83 = ats_caselptrlab_mac(anairiats_sum_10, tmp77, atslab_1) ;
tmp78 = tmp76 ;
tmp79 = tmp82 ;
tmp80 = tmp83 ;
goto __ats_lab_loop2_19 ; // tail call
break ;
} while (0) ;
return tmp81 ;

__ats_lab_loop2_19:
tmp85 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_11, tmp78), atslab_d1exp_node) ;
do {
/* branch: __ats_lab_45 */
__ats_lab_45_0:
if (((ats_sum_ptr_type)tmp85)->tag != 51) { goto __ats_lab_46_0 ; }
__ats_lab_45_1:
tmp86 = ats_caselptrlab_mac(anairiats_sum_12, tmp85, atslab_1) ;
tmp87 = ats_caselptrlab_mac(anairiats_sum_12, tmp85, atslab_2) ;
tmp89 = p1at_arity_16 (tmp86) ;
tmp88 = atspre_eq_int_int (tmp79, tmp89) ;
if (tmp88) {
tmp76 = tmp87 ;
tmp77 = tmp80 ;
goto __ats_lab_loop1_18 ; // tail call
} else {
tmp84 = ats_false_bool ;
} /* end of [if] */
break ;

/* branch: __ats_lab_46 */
__ats_lab_46_0:
if (((ats_sum_ptr_type)tmp85)->tag != 53) { goto __ats_lab_47_0 ; }
__ats_lab_46_1:
tmp90 = ats_caselptrlab_mac(anairiats_sum_13, tmp85, atslab_2) ;
tmp78 = tmp90 ;
tmp79 = tmp79 ;
tmp80 = tmp80 ;
goto __ats_lab_loop2_19 ; // tail call
break ;

/* branch: __ats_lab_47 */
__ats_lab_47_0:
if (((ats_sum_ptr_type)tmp85)->tag != 54) { goto __ats_lab_48_0 ; }
__ats_lab_47_1:
tmp91 = ats_caselptrlab_mac(anairiats_sum_13, tmp85, atslab_2) ;
tmp78 = tmp91 ;
tmp79 = tmp79 ;
tmp80 = tmp80 ;
goto __ats_lab_loop2_19 ; // tail call
break ;

/* branch: __ats_lab_48 */
__ats_lab_48_0:
if (((ats_sum_ptr_type)tmp85)->tag != 55) { goto __ats_lab_49_0 ; }
__ats_lab_48_1:
tmp92 = ats_caselptrlab_mac(anairiats_sum_13, tmp85, atslab_2) ;
tmp78 = tmp92 ;
tmp79 = tmp79 ;
tmp80 = tmp80 ;
goto __ats_lab_loop2_19 ; // tail call
break ;

/* branch: __ats_lab_49 */
__ats_lab_49_0:
__ats_lab_49_1:
tmp84 = ats_false_bool ;
break ;
} while (0) ;
return tmp84 ;

return (tmp93) ;
} /* end of [loop1_18_0loop2_19] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 5456(line=284, offs=4) -- 6125(line=311, offs=4)
*/
ATSstaticdec()
ats_bool_type
aritest_17 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp75) ;

__ats_lab_aritest_17:
tmp75 = loop1_18 (arg0, arg1) ;
return (tmp75) ;
} /* end of [aritest_17] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 6197(line=317, offs=3) -- 6273(line=319, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2cst_match_def (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp96) ;
ATSlocal (ats_ptr_type, tmp97) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2cst_match_def:
tmp97 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2cst_get_artylst (arg0) ;
tmp96 = aritest_17 (arg1, tmp97) ;
return (tmp96) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2cst_match_def] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 6399(line=329, offs=5) -- 6534(line=335, offs=2)
*/
ATSstaticdec()
ats_ptr_type
aux_23 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp99) ;
ATSlocal (ats_ptr_type, tmp100) ;
ATSlocal (ats_ptr_type, tmp101) ;

__ats_lab_aux_23:
do {
/* branch: __ats_lab_50 */
__ats_lab_50_0:
if (arg0 != (ats_sum_ptr_type)0) { goto __ats_lab_51_0 ; }
__ats_lab_50_1:
tmp99 = (ats_sum_ptr_type)0 ;
break ;

/* branch: __ats_lab_51 */
__ats_lab_51_0:
// if (arg0 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_51_1:
tmp100 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
tmp101 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_1) ;
tmp99 = aux2_24 (tmp100, tmp101) ;
break ;
} while (0) ;
return (tmp99) ;
} /* end of [aux_23] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 6561(line=337, offs=5) -- 6707(line=345, offs=2)
*/
ATSstaticdec()
ats_ptr_type
aux2_24 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp102) ;
ATSlocal (ats_ptr_type, tmp103) ;
ATSlocal (ats_ptr_type, tmp104) ;

__ats_lab_aux2_24:
do {
/* branch: __ats_lab_52 */
__ats_lab_52_0:
if (arg1 != (ats_sum_ptr_type)0) { goto __ats_lab_53_0 ; }
__ats_lab_52_1:
tmp102 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_14, arg0), atslab_d2lab_overld) ;
break ;

/* branch: __ats_lab_53 */
__ats_lab_53_0:
// if (arg1 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_53_1:
tmp103 = ats_caselptrlab_mac(anairiats_sum_1, arg1, atslab_0) ;
tmp104 = ats_caselptrlab_mac(anairiats_sum_1, arg1, atslab_1) ;
arg0 = tmp103 ;
arg1 = tmp104 ;
goto __ats_lab_aux2_24 ; // tail call
break ;
} while (0) ;
return (tmp102) ;
} /* end of [aux2_24] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 6379(line=327, offs=3) -- 6819(line=352, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_get_seloverld (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp98) ;
ATSlocal (ats_ptr_type, tmp105) ;
ATSlocal (ats_ptr_type, tmp106) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_get_seloverld:
tmp105 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_4, arg0), atslab_d2exp_node) ;
do {
/* branch: __ats_lab_54 */
__ats_lab_54_0:
if (((ats_sum_ptr_type)tmp105)->tag != 38) { goto __ats_lab_55_0 ; }
__ats_lab_54_1:
tmp106 = ats_caselptrlab_mac(anairiats_sum_3, tmp105, atslab_1) ;
tmp98 = aux_23 (tmp106) ;
break ;

/* branch: __ats_lab_55 */
__ats_lab_55_0:
__ats_lab_55_1:
tmp98 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp98) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_get_seloverld] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list_vt.dats: 7889(line=308, offs=7) -- 8174(line=317, offs=28)
*/
ATSstaticdec()
ats_ptr_type
revapp_29 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp121) ;
ATSlocal (ats_ptr_type, tmp122) ;
ATSlocal (ats_ptr_type, tmp123) ;
ATSlocal (ats_ptr_type, tmp124) ;

__ats_lab_revapp_29:
do {
/* branch: __ats_lab_57 */
__ats_lab_57_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_58_0 ; }
__ats_lab_57_1:
tmp122 = &ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_1) ;
tmp123 = ats_ptrget_mac(ats_ptr_type, tmp122) ;
ats_ptrget_mac(ats_ptr_type, tmp122) = arg1 ;
tmp124 = arg0 ;
arg0 = tmp123 ;
arg1 = tmp124 ;
goto __ats_lab_revapp_29 ; // tail call
break ;

/* branch: __ats_lab_58 */
__ats_lab_58_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_58_1:
tmp121 = arg1 ;
break ;
} while (0) ;
return (tmp121) ;
} /* end of [revapp_29] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list_vt.dats: 7770(line=303, offs=24) -- 8220(line=321, offs=4)
*/
ATSstaticdec()
ats_ptr_type
list_vt_reverse_append_01507_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp120) ;

__ats_lab_list_vt_reverse_append_01507_ats_ptr_type:
tmp120 = revapp_29 (arg0, arg1) ;
return (tmp120) ;
} /* end of [list_vt_reverse_append_01507_ats_ptr_type] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list_vt.dats: 7652(line=298, offs=17) -- 7704(line=299, offs=46)
*/
ATSstaticdec()
ats_ptr_type
list_vt_reverse_01506_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp119) ;
ATSlocal (ats_ptr_type, tmp125) ;

__ats_lab_list_vt_reverse_01506_ats_ptr_type:
tmp125 = (ats_sum_ptr_type)0 ;
tmp119 = list_vt_reverse_append_01507_ats_ptr_type (arg0, tmp125) ;
return (tmp119) ;
} /* end of [list_vt_reverse_01506_ats_ptr_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 7016(line=365, offs=5) -- 7467(line=387, offs=2)
*/
ATSstaticdec()
ats_ptr_type
aux_26 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp113) ;
ATSlocal (ats_ptr_type, tmp114) ;
ATSlocal (ats_ptr_type, tmp115) ;
ATSlocal (ats_ptr_type, tmp116) ;
ATSlocal (ats_ptr_type, tmp117) ;
ATSlocal (ats_ptr_type, tmp118) ;
ATSlocal (ats_ptr_type, tmp126) ;
ATSlocal (ats_ptr_type, tmp127) ;
ATSlocal (ats_ptr_type, tmp128) ;

__ats_lab_aux_26:
do {
/* branch: __ats_lab_56 */
__ats_lab_56_0:
if (arg3 != (ats_sum_ptr_type)0) { goto __ats_lab_59_0 ; }
__ats_lab_56_1:
tmp115 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_4, arg0), atslab_d2exp_loc) ;
tmp116 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_14, arg1), atslab_d2lab_loc) ;
tmp114 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__location_combine (tmp115, tmp116) ;
tmp117 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
ats_selptrset_mac(anairiats_sum_1, tmp117, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_1, tmp117, atslab_1, arg4) ;
tmp118 = list_vt_reverse_01506_ats_ptr_type (tmp117) ;
tmp113 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_selab (tmp114, arg0, ats_castfn_mac(ats_ptr_type, tmp118)) ;
break ;

/* branch: __ats_lab_59 */
__ats_lab_59_0:
// if (arg3 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_59_1:
tmp126 = ats_caselptrlab_mac(anairiats_sum_1, arg3, atslab_0) ;
tmp127 = ats_caselptrlab_mac(anairiats_sum_1, arg3, atslab_1) ;
tmp128 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
ats_selptrset_mac(anairiats_sum_1, tmp128, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_1, tmp128, atslab_1, arg4) ;
arg0 = arg0 ;
arg1 = arg2 ;
arg2 = tmp126 ;
arg3 = tmp127 ;
arg4 = tmp128 ;
goto __ats_lab_aux_26 ; // tail call
break ;
} while (0) ;
return (tmp113) ;
} /* end of [aux_26] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 6911(line=358, offs=3) -- 7626(line=398, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_get_seloverld_root (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp107) ;
ATSlocal (ats_ptr_type, tmp108) ;
ATSlocal (ats_ptr_type, tmp109) ;
ATSlocal (ats_ptr_type, tmp110) ;
ATSlocal (ats_ptr_type, tmp111) ;
ATSlocal (ats_ptr_type, tmp112) ;
ATSlocal (ats_ptr_type, tmp129) ;
ATSlocal (ats_ptr_type, tmp130) ;
ATSlocal (ats_ptr_type, tmp131) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_get_seloverld_root:
tmp108 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_4, arg0), atslab_d2exp_node) ;
if (((ats_sum_ptr_type)tmp108)->tag != 38) { ats_caseof_failure_handle ("/home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 6931(line=360, offs=5) -- 6971(line=361, offs=32)") ; }
tmp109 = ats_caselptrlab_mac(anairiats_sum_3, tmp108, atslab_0) ;
tmp110 = ats_caselptrlab_mac(anairiats_sum_3, tmp108, atslab_1) ;
if (tmp110 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 6979(line=363, offs=5) -- 7008(line=363, offs=34)") ; }
tmp111 = ats_caselptrlab_mac(anairiats_sum_1, tmp110, atslab_0) ;
tmp112 = ats_caselptrlab_mac(anairiats_sum_1, tmp110, atslab_1) ;
do {
/* branch: __ats_lab_60 */
__ats_lab_60_0:
if (tmp112 != (ats_sum_ptr_type)0) { goto __ats_lab_61_0 ; }
__ats_lab_60_1:
tmp107 = tmp109 ;
break ;

/* branch: __ats_lab_61 */
__ats_lab_61_0:
// if (tmp112 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_61_1:
tmp129 = ats_caselptrlab_mac(anairiats_sum_1, tmp112, atslab_0) ;
tmp130 = ats_caselptrlab_mac(anairiats_sum_1, tmp112, atslab_1) ;
tmp131 = (ats_sum_ptr_type)0 ;
tmp107 = aux_26 (tmp109, tmp111, tmp129, tmp130, tmp131) ;
break ;
} while (0) ;
return (tmp107) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_get_seloverld_root] */

/* static load function */

// extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_label_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_syntax_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp1_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__staload (void) ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__staload () {
static int _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__staload_flag) return ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__staload_flag = 1 ;

// _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_label_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_syntax_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp1_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__dynload () {
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__dynload_flag = 1 ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e12_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____copy_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____free_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [pats_dynexp2_util_dats.c] */
