/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2016-12-6:  9h:51m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_rec_0 ;

typedef struct {
ats_ptr_type atslab_0 ;
} anairiats_sum_1 ;

typedef
struct {
ats_ptr_type atslab_hisexp_name ;
ats_ptr_type atslab_hisexp_node ;
} anairiats_rec_2 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_3 ;

typedef
struct {
ats_ptr_type atslab_hipat_loc ;
ats_ptr_type atslab_hipat_type ;
ats_ptr_type atslab_hipat_node ;
ats_ptr_type atslab_hipat_asvar ;
} anairiats_rec_4 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_5 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_6 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
} anairiats_sum_7 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
} anairiats_sum_8 ;

typedef struct {
int tag ;
ats_bool_type atslab_0 ;
} anairiats_sum_9 ;

typedef struct {
int tag ;
ats_char_type atslab_0 ;
} anairiats_sum_10 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_11 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_12 ;

typedef
struct {
ats_ptr_type atslab_hidecl_loc ;
ats_ptr_type atslab_hidecl_node ;
} anairiats_rec_13 ;

typedef
struct {
ats_ptr_type atslab_hivaldec_loc ;
ats_ptr_type atslab_hivaldec_pat ;
ats_ptr_type atslab_hivaldec_def ;
} anairiats_rec_14 ;

typedef
struct {
ats_ptr_type atslab_hidexp_loc ;
ats_ptr_type atslab_hidexp_type ;
ats_ptr_type atslab_hidexp_node ;
} anairiats_rec_15 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_nil_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__None_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__Some_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__None_vt_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__Some_vt_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_basics_2esats__FUNCLOfun_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_histaexp_2esats__HSEfun_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__LABHIPAT_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HIPany_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HIPvar_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HIPint_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HIPbool_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HIPchar_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HIPstring_6) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HIPfloat_7) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HIPempty_10) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HIPcon_11) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HIPcon_any_12) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HIPrec_13) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HIPrefas_14) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HIPann_15) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__LABHIDEXP_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HDEcst_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HDEvar_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HDEbool_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HDEchar_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HDEstring_7) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HDEi0nt_8) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HDEf0loat_9) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HDEempty_13) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HDEextval_16) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HDEtmpcst_20) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HDEtmpvar_21) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HDEfoldat_22) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HDElet_24) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HDErec_30) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HDEseq_31) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HDEselvar_36) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HDEselptr_37) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HDElam_46) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HIDnone_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HIDlist_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HIDfundecs_10) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HIDvaldecs_11) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__HIDvaldecs_rec_12) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HDEVEnone_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HDEVEsome_var_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HDEVEsome_emp_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HABNDnone_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HABNDsome_any_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HABNDsome_var_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HABNDsome_emp_3) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_assert_errmsg) (ats_bool_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_prerr_newline) () ;
ATSextern_fun(ats_ptr_type, atspre_string_append) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, atspre_neg_bool) (ats_bool_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_bool_bool) (ats_bool_type, ats_bool_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_char_char) (ats_char_type, ats_char_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_idiv) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_mul2_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_zero_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_string_string) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_prerr_string) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_funenv_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_cloenv_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_split_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(anairiats_rec_0, atspre_array_ptr_takeout2_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_foreach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_iforeach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array2_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atslib_qsort) (ats_ref_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_location_2esats__prerr_location) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_label_2esats__eq_label_label) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__eq_d2con_d2con) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__d2cst_get_hisexp) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__d2cst_set_hisexp) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__d2var_get_hisexp) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__d2var_set_hisexp) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__d2var_is_mutabl) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__eq_d2var_d2var) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_histaexp_2esats__prerr_hisexp) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2cst_get2_hisexp) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2var_get2_hisexp) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipat_is_wild) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__labhipatlst_is_wild) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipat_subtest) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipatlst_subtest) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__labhipatlst_subtest) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_is_value) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_is_lvalue) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_let) (ats_ptr_type, ats_ptr_type, ats_ptr_type, ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____copy_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____free_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
/* sum constructor declarations */
ATSglobal(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HDEVEnone_0) ;
ATSglobal(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HDEVEsome_var_1) ;
ATSglobal(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HDEVEsome_emp_2) ;
ATSglobal(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HABNDnone_0) ;
ATSglobal(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HABNDsome_any_1) ;
ATSglobal(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HABNDsome_var_2) ;
ATSglobal(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HABNDsome_emp_3) ;

/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_void_type prerr_FILENAME_02041_ () ;
static
ats_void_type prerr_interror_02042_ () ;
static
ats_bool_type loop_15 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;
static
ats_bool_type list_forall_funenv_01366_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;
static
ats_bool_type list_forall_fun_01367_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_bool_type labhipat_is_wild_17 (ats_ptr_type arg0) ;
static
ats_bool_type labhipat_subtest_20 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_bool_type hidexplst_is_value_22 (ats_ptr_type arg0) ;
static
ats_bool_type ftest_24 (ats_ptr_type arg0) ;
static
ats_bool_type labhidexplst_is_value_23 (ats_ptr_type arg0) ;
static
ats_bool_type hidecl_is_value_25 (ats_ptr_type arg0) ;
static
ats_bool_type hideclist_is_value_26 (ats_ptr_type arg0) ;
static
ats_bool_type hivaldec_is_value_27 (ats_ptr_type arg0) ;
static
ats_bool_type hivaldecs_is_value_28 (ats_ptr_type arg0) ;
static
ats_bool_type auxseq_30 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_bool_type list_is_nil_01294_ (ats_ptr_type arg0) ;
static
ats_ptr_type hidexp_is_varemp_34 (ats_ptr_type arg0) ;
static
ats_ptr_type aux_36 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type hidecl_is_anybind_35 (ats_ptr_type arg0) ;
static
ats_ptr_type dropz_37 (ats_ptr_type arg0) ;
static
ats_ptr_type loop_40 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type list_last_01407_ats_ptr_type (ats_ptr_type arg0) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 1623(line=48, offs=28) -- 1654(line=48, offs=59)
*/
ATSstaticdec()
ats_void_type
prerr_FILENAME_02041_ () {
/* local vardec */
// ATSlocal_void (tmp0) ;

__ats_lab_prerr_FILENAME_02041_:
/* tmp0 = */ atspre_prerr_string (ATSstrcst("pats_hidynexp_util")) ;
return /* (tmp0) */ ;
} /* end of [prerr_FILENAME_02041_] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 2199(line=79, offs=19) -- 2254(line=80, offs=48)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2cst_get2_hisexp (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp1) ;
ATSlocal (ats_ptr_type, tmp2) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2cst_get2_hisexp:
tmp2 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__d2cst_get_hisexp (arg0) ;
tmp1 = ats_castfn_mac(ats_ptr_type, tmp2) ;
return (tmp1) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2cst_get2_hisexp] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 2285(line=82, offs=19) -- 2358(line=83, offs=61)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2cst_set2_hisexp (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp3) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2cst_set2_hisexp:
/* tmp3 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__d2cst_set_hisexp (arg0, ats_castfn_mac(ats_ptr_type, arg1)) ;
return /* (tmp3) */ ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2cst_set2_hisexp] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 2413(line=89, offs=3) -- 2644(line=103, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__d2cst_is_fun (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp4) ;
ATSlocal (ats_ptr_type, tmp5) ;
ATSlocal (ats_ptr_type, tmp6) ;
ATSlocal (ats_ptr_type, tmp7) ;
ATSlocal (ats_ptr_type, tmp8) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__d2cst_is_fun:
tmp5 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2cst_get2_hisexp (arg0) ;
if (tmp5 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 2432(line=91, offs=5) -- 2468(line=91, offs=41)") ; }
tmp6 = ats_caselptrlab_mac(anairiats_sum_1, tmp5, atslab_0) ;
tmp7 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_2, tmp6), atslab_hisexp_node) ;
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (((ats_sum_ptr_type)tmp7)->tag != 5) { goto __ats_lab_3_0 ; }
__ats_lab_0_1:
tmp8 = ats_caselptrlab_mac(anairiats_sum_3, tmp7, atslab_0) ;
do {
/* branch: __ats_lab_1 */
__ats_lab_1_0:
if (tmp8 != (ats_sum_ptr_type)0) { goto __ats_lab_2_0 ; }
__ats_lab_1_1:
tmp4 = ats_true_bool ;
break ;

/* branch: __ats_lab_2 */
__ats_lab_2_0:
__ats_lab_2_1:
tmp4 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
__ats_lab_3_1:
tmp4 = ats_false_bool ;
break ;
} while (0) ;
return (tmp4) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__d2cst_is_fun] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_errmsg.dats: 1624(line=48, offs=16) -- 1722(line=53, offs=2)
*/
ATSstaticdec()
ats_void_type
prerr_interror_02042_ () {
/* local vardec */
// ATSlocal_void (tmp15) ;
// ATSlocal_void (tmp16) ;
// ATSlocal_void (tmp17) ;

__ats_lab_prerr_interror_02042_:
/* tmp16 = */ atspre_prerr_string (ATSstrcst("INTERROR(")) ;
/* tmp17 = */ prerr_FILENAME_02041_ () ;
/* tmp15 = */ atspre_prerr_string (ATSstrcst(")")) ;
return /* (tmp15) */ ;
} /* end of [prerr_interror_02042_] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 2729(line=109, offs=3) -- 3108(line=130, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2cst_get2_type_arg (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_ptr_type, tmp10) ;
ATSlocal (ats_ptr_type, tmp11) ;
ATSlocal (ats_ptr_type, tmp12) ;
ATSlocal (ats_ptr_type, tmp13) ;
// ATSlocal_void (tmp14) ;
// ATSlocal_void (tmp18) ;
// ATSlocal_void (tmp19) ;
// ATSlocal_void (tmp20) ;
// ATSlocal_void (tmp21) ;
ATSlocal (ats_ptr_type, tmp22) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2cst_get2_type_arg:
tmp10 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2cst_get2_hisexp (arg0) ;
if (tmp10 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 2748(line=111, offs=5) -- 2783(line=111, offs=40)") ; }
tmp11 = ats_caselptrlab_mac(anairiats_sum_1, tmp10, atslab_0) ;
tmp12 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_2, tmp11), atslab_hisexp_node) ;
do {
/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (((ats_sum_ptr_type)tmp12)->tag != 5) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
tmp13 = ats_caselptrlab_mac(anairiats_sum_3, tmp12, atslab_1) ;
tmp9 = tmp13 ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
__ats_lab_5_1:
/* tmp14 = */ prerr_interror_02042_ () ;
/* tmp18 = */ atspre_prerr_string (ATSstrcst(": d2cst_get_type_arg: hse = ")) ;
/* tmp19 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_histaexp_2esats__prerr_hisexp (tmp11) ;
/* tmp20 = */ atspre_prerr_newline () ;
tmp22 = atspre_string_append ("/home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 3019(line=125, offs=14) -- 3035(line=125, offs=30)", ATSstrcst("\n")) ;
/* tmp21 = */ atspre_assert_errmsg (ats_false_bool, tmp22) ;
/* tmp9 = */ ats_exit (1) ;
break ;
} while (0) ;
return (tmp9) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2cst_get2_type_arg] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 3174(line=134, offs=3) -- 3555(line=156, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2cst_get2_type_res (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp23) ;
ATSlocal (ats_ptr_type, tmp24) ;
ATSlocal (ats_ptr_type, tmp25) ;
ATSlocal (ats_ptr_type, tmp26) ;
ATSlocal (ats_ptr_type, tmp27) ;
// ATSlocal_void (tmp28) ;
// ATSlocal_void (tmp29) ;
// ATSlocal_void (tmp30) ;
// ATSlocal_void (tmp31) ;
// ATSlocal_void (tmp32) ;
ATSlocal (ats_ptr_type, tmp33) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2cst_get2_type_res:
tmp24 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2cst_get2_hisexp (arg0) ;
if (tmp24 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 3193(line=136, offs=5) -- 3228(line=136, offs=40)") ; }
tmp25 = ats_caselptrlab_mac(anairiats_sum_1, tmp24, atslab_0) ;
tmp26 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_2, tmp25), atslab_hisexp_node) ;
do {
/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (((ats_sum_ptr_type)tmp26)->tag != 5) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
tmp27 = ats_caselptrlab_mac(anairiats_sum_3, tmp26, atslab_2) ;
tmp23 = tmp27 ;
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
__ats_lab_7_1:
/* tmp28 = */ prerr_interror_02042_ () ;
/* tmp29 = */ atspre_prerr_string (ATSstrcst(": d2cst_get_type_arg: hse = ")) ;
/* tmp30 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_histaexp_2esats__prerr_hisexp (tmp25) ;
/* tmp31 = */ atspre_prerr_newline () ;
tmp33 = atspre_string_append ("/home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 3466(line=151, offs=14) -- 3482(line=151, offs=30)", ATSstrcst("\n")) ;
/* tmp32 = */ atspre_assert_errmsg (ats_false_bool, tmp33) ;
/* tmp23 = */ ats_exit (1) ;
break ;
} while (0) ;
return (tmp23) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2cst_get2_type_res] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 3639(line=161, offs=19) -- 3694(line=162, offs=48)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2var_get2_hisexp (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp34) ;
ATSlocal (ats_ptr_type, tmp35) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2var_get2_hisexp:
tmp35 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__d2var_get_hisexp (arg0) ;
tmp34 = ats_castfn_mac(ats_ptr_type, tmp35) ;
return (tmp34) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2var_get2_hisexp] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 3725(line=164, offs=19) -- 3798(line=165, offs=61)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2var_set2_hisexp (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp36) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2var_set2_hisexp:
/* tmp36 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__d2var_set_hisexp (arg0, ats_castfn_mac(ats_ptr_type, arg1)) ;
return /* (tmp36) */ ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2var_set2_hisexp] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 3851(line=170, offs=19) -- 4059(line=182, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2cst_get2_funclo (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp37) ;
ATSlocal (ats_ptr_type, tmp38) ;
ATSlocal (ats_ptr_type, tmp39) ;
ATSlocal (ats_ptr_type, tmp40) ;
ATSlocal (ats_ptr_type, tmp41) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2cst_get2_funclo:
tmp38 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2cst_get2_hisexp (arg0) ;
do {
/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (tmp38 == (ats_sum_ptr_type)0) { goto __ats_lab_11_0 ; }
__ats_lab_8_1:
tmp39 = ats_caselptrlab_mac(anairiats_sum_1, tmp38, atslab_0) ;
tmp40 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_2, tmp39), atslab_hisexp_node) ;
do {
/* branch: __ats_lab_9 */
__ats_lab_9_0:
if (((ats_sum_ptr_type)tmp40)->tag != 5) { goto __ats_lab_10_0 ; }
__ats_lab_9_1:
tmp41 = ats_caselptrlab_mac(anairiats_sum_3, tmp40, atslab_0) ;
tmp37 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
ats_selptrset_mac(anairiats_sum_1, tmp37, atslab_0, tmp41) ;
break ;

/* branch: __ats_lab_10 */
__ats_lab_10_0:
__ats_lab_10_1:
tmp37 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_11 */
__ats_lab_11_0:
// if (tmp38 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_11_1:
tmp37 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp37) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2cst_get2_funclo] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 4140(line=187, offs=19) -- 4348(line=199, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2var_get2_funclo (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp42) ;
ATSlocal (ats_ptr_type, tmp43) ;
ATSlocal (ats_ptr_type, tmp44) ;
ATSlocal (ats_ptr_type, tmp45) ;
ATSlocal (ats_ptr_type, tmp46) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2var_get2_funclo:
tmp43 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2var_get2_hisexp (arg0) ;
do {
/* branch: __ats_lab_12 */
__ats_lab_12_0:
if (tmp43 == (ats_sum_ptr_type)0) { goto __ats_lab_15_0 ; }
__ats_lab_12_1:
tmp44 = ats_caselptrlab_mac(anairiats_sum_1, tmp43, atslab_0) ;
tmp45 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_2, tmp44), atslab_hisexp_node) ;
do {
/* branch: __ats_lab_13 */
__ats_lab_13_0:
if (((ats_sum_ptr_type)tmp45)->tag != 5) { goto __ats_lab_14_0 ; }
__ats_lab_13_1:
tmp46 = ats_caselptrlab_mac(anairiats_sum_3, tmp45, atslab_0) ;
tmp42 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
ats_selptrset_mac(anairiats_sum_1, tmp42, atslab_0, tmp46) ;
break ;

/* branch: __ats_lab_14 */
__ats_lab_14_0:
__ats_lab_14_1:
tmp42 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_15 */
__ats_lab_15_0:
// if (tmp43 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_15_1:
tmp42 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp42) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__d2var_get2_funclo] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 4427(line=205, offs=3) -- 4612(line=216, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipat_is_wild (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp47) ;
ATSlocal (ats_ptr_type, tmp48) ;
ATSlocal (ats_ptr_type, tmp49) ;
ATSlocal (ats_ptr_type, tmp50) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipat_is_wild:
tmp48 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_4, arg0), atslab_hipat_node) ;
do {
/* branch: __ats_lab_16 */
__ats_lab_16_0:
if (((ats_sum_ptr_type)tmp48)->tag != 0) { goto __ats_lab_17_0 ; }
__ats_lab_16_1:
tmp47 = ats_true_bool ;
break ;

/* branch: __ats_lab_17 */
__ats_lab_17_0:
if (((ats_sum_ptr_type)tmp48)->tag != 1) { goto __ats_lab_18_0 ; }
__ats_lab_17_1:
tmp47 = ats_true_bool ;
break ;

/* branch: __ats_lab_18 */
__ats_lab_18_0:
if (((ats_sum_ptr_type)tmp48)->tag != 15) { goto __ats_lab_19_0 ; }
__ats_lab_18_1:
tmp49 = ats_caselptrlab_mac(anairiats_sum_5, tmp48, atslab_0) ;
arg0 = tmp49 ;
goto __ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipat_is_wild ; // tail call
break ;

/* branch: __ats_lab_19 */
__ats_lab_19_0:
if (((ats_sum_ptr_type)tmp48)->tag != 14) { goto __ats_lab_20_0 ; }
__ats_lab_19_1:
tmp50 = ats_caselptrlab_mac(anairiats_sum_5, tmp48, atslab_1) ;
arg0 = tmp50 ;
goto __ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipat_is_wild ; // tail call
break ;

/* branch: __ats_lab_20 */
__ats_lab_20_0:
__ats_lab_20_1:
tmp47 = ats_false_bool ;
break ;
} while (0) ;
return (tmp47) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipat_is_wild] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/list.dats: 32895(line=1167, offs=7) -- 33167(line=1176, offs=21)
*/
ATSstaticdec()
ats_bool_type
loop_15 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_bool_type, tmp54) ;
ATSlocal (ats_ptr_type, tmp55) ;
ATSlocal (ats_ptr_type, tmp56) ;
ATSlocal (ats_bool_type, tmp57) ;

__ats_lab_loop_15:
do {
/* branch: __ats_lab_21 */
__ats_lab_21_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_22_0 ; }
__ats_lab_21_1:
tmp55 = ats_caselptrlab_mac(anairiats_sum_6, arg0, atslab_0) ;
tmp56 = ats_caselptrlab_mac(anairiats_sum_6, arg0, atslab_1) ;
tmp57 = ((ats_bool_type(*)(ats_ptr_type, ats_ptr_type))arg1) (tmp55, arg2) ;
if (tmp57) {
arg0 = tmp56 ;
arg1 = arg1 ;
arg2 = arg2 ;
goto __ats_lab_loop_15 ; // tail call
} else {
tmp54 = ats_false_bool ;
} /* end of [if] */
break ;

/* branch: __ats_lab_22 */
__ats_lab_22_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_22_1:
tmp54 = ats_true_bool ;
break ;
} while (0) ;
return (tmp54) ;
} /* end of [loop_15] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/list.dats: 32865(line=1166, offs=20) -- 33218(line=1180, offs=4)
*/
ATSstaticdec()
ats_bool_type
list_forall_funenv_01366_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_bool_type, tmp53) ;

__ats_lab_list_forall_funenv_01366_ats_ptr_type:
tmp53 = loop_15 (arg0, arg1, arg2) ;
return (tmp53) ;
} /* end of [list_forall_funenv_01366_ats_ptr_type] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/list.dats: 33288(line=1183, offs=25) -- 33550(line=1192, offs=4)
*/
ATSstaticdec()
ats_bool_type
list_forall_fun_01367_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp52) ;

__ats_lab_list_forall_fun_01367_ats_ptr_type:
tmp52 = list_forall_funenv_01366_ats_ptr_type (arg0, ats_castfn_mac(ats_ptr_type, arg1), atspre_null_ptr) ;
return (tmp52) ;
} /* end of [list_forall_fun_01367_ats_ptr_type] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 4669(line=220, offs=3) -- 4715(line=220, offs=49)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipatlst_is_wild (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp51) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipatlst_is_wild:
tmp51 = list_forall_fun_01367_ats_ptr_type (arg0, &_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipat_is_wild) ;
return (tmp51) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipatlst_is_wild] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 4799(line=227, offs=5) -- 4904(line=230, offs=4)
*/
ATSstaticdec()
ats_bool_type
labhipat_is_wild_17 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp59) ;
ATSlocal (ats_ptr_type, tmp60) ;

__ats_lab_labhipat_is_wild_17:

tmp60 = ats_caselptrlab_mac(anairiats_sum_6, arg0, atslab_1) ;
tmp59 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipat_is_wild (tmp60) ;
return (tmp59) ;
} /* end of [labhipat_is_wild_17] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 4778(line=225, offs=3) -- 4987(line=234, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__labhipatlst_is_wild (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp58) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__labhipatlst_is_wild:
tmp58 = list_forall_fun_01367_ats_ptr_type (arg0, &labhipat_is_wild_17) ;
return (tmp58) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__labhipatlst_is_wild] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 5068(line=240, offs=3) -- 6897(line=323, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipat_subtest (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp61) ;
ATSlocal (ats_ptr_type, tmp62) ;
ATSlocal (ats_ptr_type, tmp63) ;
ATSlocal (ats_ptr_type, tmp64) ;
ATSlocal (ats_ptr_type, tmp65) ;
ATSlocal (ats_ptr_type, tmp66) ;
ATSlocal (ats_ptr_type, tmp67) ;
ATSlocal (ats_ptr_type, tmp68) ;
ATSlocal (ats_ptr_type, tmp69) ;
ATSlocal (ats_ptr_type, tmp70) ;
ATSlocal (ats_ptr_type, tmp71) ;
ATSlocal (ats_bool_type, tmp72) ;
ATSlocal (ats_ptr_type, tmp73) ;
ATSlocal (ats_ptr_type, tmp74) ;
ATSlocal (ats_ptr_type, tmp75) ;
ATSlocal (ats_ptr_type, tmp76) ;
ATSlocal (ats_bool_type, tmp77) ;
ATSlocal (ats_ptr_type, tmp78) ;
ATSlocal (ats_int_type, tmp79) ;
ATSlocal (ats_int_type, tmp80) ;
ATSlocal (ats_bool_type, tmp81) ;
ATSlocal (ats_bool_type, tmp82) ;
ATSlocal (ats_char_type, tmp83) ;
ATSlocal (ats_char_type, tmp84) ;
ATSlocal (ats_ptr_type, tmp85) ;
ATSlocal (ats_ptr_type, tmp86) ;
ATSlocal (ats_ptr_type, tmp87) ;
ATSlocal (ats_ptr_type, tmp88) ;
ATSlocal (ats_ptr_type, tmp89) ;
ATSlocal (ats_ptr_type, tmp90) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipat_subtest:
tmp62 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_4, arg0), atslab_hipat_node) ;
tmp63 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_4, arg1), atslab_hipat_node) ;
do {
/* branch: __ats_lab_23 */
__ats_lab_23_0:
__ats_lab_23_1:
if (((ats_sum_ptr_type)tmp63)->tag != 0) { goto __ats_lab_24_1 ; }
__ats_lab_23_2:
tmp61 = ats_true_bool ;
break ;

/* branch: __ats_lab_24 */
__ats_lab_24_0:
__ats_lab_24_1:
if (((ats_sum_ptr_type)tmp63)->tag != 1) { goto __ats_lab_25_1 ; }
__ats_lab_24_2:
tmp61 = ats_true_bool ;
break ;

/* branch: __ats_lab_25 */
__ats_lab_25_0:
__ats_lab_25_1:
if (((ats_sum_ptr_type)tmp63)->tag != 15) { goto __ats_lab_26_1 ; }
__ats_lab_25_2:
tmp64 = ats_caselptrlab_mac(anairiats_sum_5, tmp63, atslab_0) ;
arg0 = arg0 ;
arg1 = tmp64 ;
goto __ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipat_subtest ; // tail call
break ;

/* branch: __ats_lab_26 */
__ats_lab_26_0:
__ats_lab_26_1:
if (((ats_sum_ptr_type)tmp63)->tag != 14) { goto __ats_lab_27_0 ; }
__ats_lab_26_2:
tmp65 = ats_caselptrlab_mac(anairiats_sum_5, tmp63, atslab_1) ;
arg0 = arg0 ;
arg1 = tmp65 ;
goto __ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipat_subtest ; // tail call
break ;

/* branch: __ats_lab_27 */
__ats_lab_27_0:
if (((ats_sum_ptr_type)tmp62)->tag != 15) { goto __ats_lab_28_0 ; }
__ats_lab_27_1:
__ats_lab_27_2:
tmp66 = ats_caselptrlab_mac(anairiats_sum_5, tmp62, atslab_0) ;
arg0 = tmp66 ;
arg1 = arg1 ;
goto __ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipat_subtest ; // tail call
break ;

/* branch: __ats_lab_28 */
__ats_lab_28_0:
if (((ats_sum_ptr_type)tmp62)->tag != 14) { goto __ats_lab_29_0 ; }
__ats_lab_28_1:
__ats_lab_28_2:
tmp67 = ats_caselptrlab_mac(anairiats_sum_5, tmp62, atslab_1) ;
arg0 = tmp67 ;
arg1 = arg1 ;
goto __ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipat_subtest ; // tail call
break ;

/* branch: __ats_lab_29 */
__ats_lab_29_0:
if (((ats_sum_ptr_type)tmp62)->tag != 11) { goto __ats_lab_33_0 ; }
__ats_lab_29_1:
__ats_lab_29_2:
tmp68 = ats_caselptrlab_mac(anairiats_sum_7, tmp62, atslab_1) ;
tmp69 = ats_caselptrlab_mac(anairiats_sum_7, tmp62, atslab_3) ;
do {
/* branch: __ats_lab_30 */
__ats_lab_30_0:
if (((ats_sum_ptr_type)tmp63)->tag != 11) { goto __ats_lab_31_0 ; }
__ats_lab_30_1:
tmp70 = ats_caselptrlab_mac(anairiats_sum_7, tmp63, atslab_1) ;
tmp71 = ats_caselptrlab_mac(anairiats_sum_7, tmp63, atslab_3) ;
tmp72 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__eq_d2con_d2con (tmp68, tmp70) ;
if (tmp72) {
tmp61 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__labhipatlst_subtest (tmp69, tmp71) ;
} else {
tmp61 = ats_false_bool ;
} /* end of [if] */
break ;

/* branch: __ats_lab_31 */
__ats_lab_31_0:
if (((ats_sum_ptr_type)tmp63)->tag != 12) { goto __ats_lab_32_0 ; }
__ats_lab_31_1:
tmp73 = ats_caselptrlab_mac(anairiats_sum_5, tmp63, atslab_1) ;
tmp61 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__eq_d2con_d2con (tmp68, tmp73) ;
break ;

/* branch: __ats_lab_32 */
__ats_lab_32_0:
__ats_lab_32_1:
tmp61 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_33 */
__ats_lab_33_0:
if (((ats_sum_ptr_type)tmp62)->tag != 12) { goto __ats_lab_37_0 ; }
__ats_lab_33_1:
__ats_lab_33_2:
tmp74 = ats_caselptrlab_mac(anairiats_sum_5, tmp62, atslab_1) ;
do {
/* branch: __ats_lab_34 */
__ats_lab_34_0:
if (((ats_sum_ptr_type)tmp63)->tag != 11) { goto __ats_lab_35_0 ; }
__ats_lab_34_1:
tmp75 = ats_caselptrlab_mac(anairiats_sum_7, tmp63, atslab_1) ;
tmp76 = ats_caselptrlab_mac(anairiats_sum_7, tmp63, atslab_3) ;
tmp77 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__eq_d2con_d2con (tmp74, tmp75) ;
if (tmp77) {
tmp61 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__labhipatlst_is_wild (tmp76) ;
} else {
tmp61 = ats_false_bool ;
} /* end of [if] */
break ;

/* branch: __ats_lab_35 */
__ats_lab_35_0:
if (((ats_sum_ptr_type)tmp63)->tag != 12) { goto __ats_lab_36_0 ; }
__ats_lab_35_1:
tmp78 = ats_caselptrlab_mac(anairiats_sum_5, tmp63, atslab_1) ;
tmp61 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__eq_d2con_d2con (tmp74, tmp78) ;
break ;

/* branch: __ats_lab_36 */
__ats_lab_36_0:
__ats_lab_36_1:
tmp61 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_37 */
__ats_lab_37_0:
if (((ats_sum_ptr_type)tmp62)->tag != 2) { goto __ats_lab_40_0 ; }
__ats_lab_37_1:
__ats_lab_37_2:
tmp79 = ats_caselptrlab_mac(anairiats_sum_8, tmp62, atslab_0) ;
do {
/* branch: __ats_lab_38 */
__ats_lab_38_0:
if (((ats_sum_ptr_type)tmp63)->tag != 2) { goto __ats_lab_39_0 ; }
__ats_lab_38_1:
tmp80 = ats_caselptrlab_mac(anairiats_sum_8, tmp63, atslab_0) ;
tmp61 = atspre_eq_int_int (tmp79, tmp80) ;
break ;

/* branch: __ats_lab_39 */
__ats_lab_39_0:
__ats_lab_39_1:
tmp61 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_40 */
__ats_lab_40_0:
if (((ats_sum_ptr_type)tmp62)->tag != 4) { goto __ats_lab_43_0 ; }
__ats_lab_40_1:
__ats_lab_40_2:
tmp81 = ats_caselptrlab_mac(anairiats_sum_9, tmp62, atslab_0) ;
do {
/* branch: __ats_lab_41 */
__ats_lab_41_0:
if (((ats_sum_ptr_type)tmp63)->tag != 4) { goto __ats_lab_42_0 ; }
__ats_lab_41_1:
tmp82 = ats_caselptrlab_mac(anairiats_sum_9, tmp63, atslab_0) ;
tmp61 = atspre_eq_bool_bool (tmp81, tmp82) ;
break ;

/* branch: __ats_lab_42 */
__ats_lab_42_0:
__ats_lab_42_1:
tmp61 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_43 */
__ats_lab_43_0:
if (((ats_sum_ptr_type)tmp62)->tag != 5) { goto __ats_lab_46_0 ; }
__ats_lab_43_1:
__ats_lab_43_2:
tmp83 = ats_caselptrlab_mac(anairiats_sum_10, tmp62, atslab_0) ;
do {
/* branch: __ats_lab_44 */
__ats_lab_44_0:
if (((ats_sum_ptr_type)tmp63)->tag != 5) { goto __ats_lab_45_0 ; }
__ats_lab_44_1:
tmp84 = ats_caselptrlab_mac(anairiats_sum_10, tmp63, atslab_0) ;
tmp61 = atspre_eq_char_char (tmp83, tmp84) ;
break ;

/* branch: __ats_lab_45 */
__ats_lab_45_0:
__ats_lab_45_1:
tmp61 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_46 */
__ats_lab_46_0:
if (((ats_sum_ptr_type)tmp62)->tag != 6) { goto __ats_lab_49_0 ; }
__ats_lab_46_1:
__ats_lab_46_2:
tmp85 = ats_caselptrlab_mac(anairiats_sum_11, tmp62, atslab_0) ;
do {
/* branch: __ats_lab_47 */
__ats_lab_47_0:
if (((ats_sum_ptr_type)tmp63)->tag != 6) { goto __ats_lab_48_0 ; }
__ats_lab_47_1:
tmp86 = ats_caselptrlab_mac(anairiats_sum_11, tmp63, atslab_0) ;
tmp61 = atspre_eq_string_string (tmp85, tmp86) ;
break ;

/* branch: __ats_lab_48 */
__ats_lab_48_0:
__ats_lab_48_1:
tmp61 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_49 */
__ats_lab_49_0:
if (((ats_sum_ptr_type)tmp62)->tag != 7) { goto __ats_lab_52_0 ; }
__ats_lab_49_1:
__ats_lab_49_2:
tmp87 = ats_caselptrlab_mac(anairiats_sum_11, tmp62, atslab_0) ;
do {
/* branch: __ats_lab_50 */
__ats_lab_50_0:
if (((ats_sum_ptr_type)tmp63)->tag != 7) { goto __ats_lab_51_0 ; }
__ats_lab_50_1:
tmp88 = ats_caselptrlab_mac(anairiats_sum_11, tmp63, atslab_0) ;
tmp61 = atspre_eq_string_string (tmp87, tmp88) ;
break ;

/* branch: __ats_lab_51 */
__ats_lab_51_0:
__ats_lab_51_1:
tmp61 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_52 */
__ats_lab_52_0:
if (((ats_sum_ptr_type)tmp62)->tag != 10) { goto __ats_lab_55_0 ; }
__ats_lab_52_1:
__ats_lab_52_2:
do {
/* branch: __ats_lab_53 */
__ats_lab_53_0:
if (((ats_sum_ptr_type)tmp63)->tag != 10) { goto __ats_lab_54_0 ; }
__ats_lab_53_1:
tmp61 = ats_true_bool ;
break ;

/* branch: __ats_lab_54 */
__ats_lab_54_0:
__ats_lab_54_1:
tmp61 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_55 */
__ats_lab_55_0:
if (((ats_sum_ptr_type)tmp62)->tag != 13) { goto __ats_lab_58_0 ; }
__ats_lab_55_1:
__ats_lab_55_2:
tmp89 = ats_caselptrlab_mac(anairiats_sum_12, tmp62, atslab_1) ;
do {
/* branch: __ats_lab_56 */
__ats_lab_56_0:
if (((ats_sum_ptr_type)tmp63)->tag != 13) { goto __ats_lab_57_0 ; }
__ats_lab_56_1:
tmp90 = ats_caselptrlab_mac(anairiats_sum_12, tmp63, atslab_1) ;
tmp61 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__labhipatlst_subtest (tmp89, tmp90) ;
break ;

/* branch: __ats_lab_57 */
__ats_lab_57_0:
__ats_lab_57_1:
tmp61 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_58 */
__ats_lab_58_0:
__ats_lab_58_1:
__ats_lab_58_2:
tmp61 = ats_false_bool ;
break ;
} while (0) ;
return (tmp61) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipat_subtest] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 6975(line=329, offs=3) -- 7317(line=348, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipatlst_subtest (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp91) ;
ATSlocal (ats_ptr_type, tmp92) ;
ATSlocal (ats_ptr_type, tmp93) ;
ATSlocal (ats_ptr_type, tmp94) ;
ATSlocal (ats_ptr_type, tmp95) ;
ATSlocal (ats_bool_type, tmp96) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipatlst_subtest:
do {
/* branch: __ats_lab_59 */
__ats_lab_59_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_62_0 ; }
__ats_lab_59_1:
tmp92 = ats_caselptrlab_mac(anairiats_sum_6, arg0, atslab_0) ;
tmp93 = ats_caselptrlab_mac(anairiats_sum_6, arg0, atslab_1) ;
do {
/* branch: __ats_lab_60 */
__ats_lab_60_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_61_0 ; }
__ats_lab_60_1:
tmp94 = ats_caselptrlab_mac(anairiats_sum_6, arg1, atslab_0) ;
tmp95 = ats_caselptrlab_mac(anairiats_sum_6, arg1, atslab_1) ;
tmp96 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipat_subtest (tmp92, tmp94) ;
if (tmp96) {
arg0 = tmp93 ;
arg1 = tmp95 ;
goto __ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipatlst_subtest ; // tail call
} else {
tmp91 = ats_false_bool ;
} /* end of [if] */
break ;

/* branch: __ats_lab_61 */
__ats_lab_61_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_61_1:
tmp91 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_62 */
__ats_lab_62_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_62_1:
do {
/* branch: __ats_lab_63 */
__ats_lab_63_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_64_0 ; }
__ats_lab_63_1:
tmp91 = ats_false_bool ;
break ;

/* branch: __ats_lab_64 */
__ats_lab_64_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_64_1:
tmp91 = ats_true_bool ;
break ;
} while (0) ;
break ;
} while (0) ;
return (tmp91) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipatlst_subtest] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 7380(line=354, offs=5) -- 7565(line=364, offs=4)
*/
ATSstaticdec()
ats_bool_type
labhipat_subtest_20 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp97) ;
ATSlocal (ats_ptr_type, tmp98) ;
ATSlocal (ats_ptr_type, tmp99) ;
ATSlocal (ats_ptr_type, tmp100) ;
ATSlocal (ats_ptr_type, tmp101) ;
ATSlocal (ats_bool_type, tmp102) ;

__ats_lab_labhipat_subtest_20:
// 
tmp98 = ats_caselptrlab_mac(anairiats_sum_6, arg0, atslab_0) ;
tmp99 = ats_caselptrlab_mac(anairiats_sum_6, arg0, atslab_1) ;
// 
tmp100 = ats_caselptrlab_mac(anairiats_sum_6, arg1, atslab_0) ;
tmp101 = ats_caselptrlab_mac(anairiats_sum_6, arg1, atslab_1) ;
tmp102 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_label_2esats__eq_label_label (tmp98, tmp100) ;
if (tmp102) {
tmp97 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hipat_subtest (tmp99, tmp101) ;
} else {
tmp97 = ats_false_bool ;
} /* end of [if] */
return (tmp97) ;
} /* end of [labhipat_subtest_20] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 7652(line=370, offs=3) -- 8013(line=389, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__labhipatlst_subtest (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp103) ;
ATSlocal (ats_ptr_type, tmp104) ;
ATSlocal (ats_ptr_type, tmp105) ;
ATSlocal (ats_ptr_type, tmp106) ;
ATSlocal (ats_ptr_type, tmp107) ;
ATSlocal (ats_bool_type, tmp108) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__labhipatlst_subtest:
do {
/* branch: __ats_lab_65 */
__ats_lab_65_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_68_0 ; }
__ats_lab_65_1:
tmp104 = ats_caselptrlab_mac(anairiats_sum_6, arg0, atslab_0) ;
tmp105 = ats_caselptrlab_mac(anairiats_sum_6, arg0, atslab_1) ;
do {
/* branch: __ats_lab_66 */
__ats_lab_66_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_67_0 ; }
__ats_lab_66_1:
tmp106 = ats_caselptrlab_mac(anairiats_sum_6, arg1, atslab_0) ;
tmp107 = ats_caselptrlab_mac(anairiats_sum_6, arg1, atslab_1) ;
tmp108 = labhipat_subtest_20 (tmp104, tmp106) ;
if (tmp108) {
arg0 = tmp105 ;
arg1 = tmp107 ;
goto __ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__labhipatlst_subtest ; // tail call
} else {
tmp103 = ats_false_bool ;
} /* end of [if] */
break ;

/* branch: __ats_lab_67 */
__ats_lab_67_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_67_1:
tmp103 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_68 */
__ats_lab_68_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_68_1:
do {
/* branch: __ats_lab_69 */
__ats_lab_69_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_70_0 ; }
__ats_lab_69_1:
tmp103 = ats_false_bool ;
break ;

/* branch: __ats_lab_70 */
__ats_lab_70_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_70_1:
tmp103 = ats_true_bool ;
break ;
} while (0) ;
break ;
} while (0) ;
return (tmp103) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__labhipatlst_subtest] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 8102(line=398, offs=1) -- 8186(line=400, offs=40)
*/
ATSstaticdec()
ats_bool_type
hidexplst_is_value_22 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp109) ;

__ats_lab_hidexplst_is_value_22:
tmp109 = list_forall_fun_01367_ats_ptr_type (arg0, &_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_is_value) ;
return (tmp109) ;
} /* end of [hidexplst_is_value_22] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 8286(line=407, offs=5) -- 8368(line=409, offs=4)
*/
ATSstaticdec()
ats_bool_type
ftest_24 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp111) ;
ATSlocal (ats_ptr_type, tmp112) ;

__ats_lab_ftest_24:

tmp112 = ats_caselptrlab_mac(anairiats_sum_6, arg0, atslab_1) ;
tmp111 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_is_value (tmp112) ;
return (tmp111) ;
} /* end of [ftest_24] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 8223(line=404, offs=1) -- 8425(line=413, offs=4)
*/
ATSstaticdec()
ats_bool_type
labhidexplst_is_value_23 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp110) ;

__ats_lab_labhidexplst_is_value_23:
tmp110 = list_forall_fun_01367_ats_ptr_type (arg0, &ftest_24) ;
return (tmp110) ;
} /* end of [labhidexplst_is_value_23] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 8465(line=416, offs=1) -- 8768(line=435, offs=4)
*/
ATSstaticdec()
ats_bool_type
hidecl_is_value_25 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp113) ;
ATSlocal (ats_ptr_type, tmp114) ;
ATSlocal (ats_ptr_type, tmp115) ;
ATSlocal (ats_ptr_type, tmp116) ;

__ats_lab_hidecl_is_value_25:
tmp114 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_13, arg0), atslab_hidecl_node) ;
do {
/* branch: __ats_lab_71 */
__ats_lab_71_0:
if (((ats_sum_ptr_type)tmp114)->tag != 0) { goto __ats_lab_72_0 ; }
__ats_lab_71_1:
tmp113 = ats_true_bool ;
break ;

/* branch: __ats_lab_72 */
__ats_lab_72_0:
if (((ats_sum_ptr_type)tmp114)->tag != 1) { goto __ats_lab_73_0 ; }
__ats_lab_72_1:
tmp115 = ats_caselptrlab_mac(anairiats_sum_11, tmp114, atslab_0) ;
tmp113 = hideclist_is_value_26 (tmp115) ;
break ;

/* branch: __ats_lab_73 */
__ats_lab_73_0:
if (((ats_sum_ptr_type)tmp114)->tag != 10) { goto __ats_lab_74_0 ; }
__ats_lab_73_1:
tmp113 = ats_true_bool ;
break ;

/* branch: __ats_lab_74 */
__ats_lab_74_0:
if (((ats_sum_ptr_type)tmp114)->tag != 11) { goto __ats_lab_75_0 ; }
__ats_lab_74_1:
tmp116 = ats_caselptrlab_mac(anairiats_sum_5, tmp114, atslab_1) ;
tmp113 = hivaldecs_is_value_28 (tmp116) ;
break ;

/* branch: __ats_lab_75 */
__ats_lab_75_0:
__ats_lab_75_1:
tmp113 = ats_false_bool ;
break ;
} while (0) ;
return (tmp113) ;
} /* end of [hidecl_is_value_25] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 8802(line=438, offs=1) -- 8889(line=440, offs=41)
*/
ATSstaticdec()
ats_bool_type
hideclist_is_value_26 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp117) ;

__ats_lab_hideclist_is_value_26:
tmp117 = list_forall_fun_01367_ats_ptr_type (arg0, &hidecl_is_value_25) ;
return (tmp117) ;
} /* end of [hideclist_is_value_26] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 8926(line=444, offs=1) -- 9005(line=446, offs=36)
*/
ATSstaticdec()
ats_bool_type
hivaldec_is_value_27 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp118) ;
ATSlocal (ats_ptr_type, tmp119) ;

__ats_lab_hivaldec_is_value_27:
tmp119 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_14, arg0), atslab_hivaldec_def) ;
tmp118 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_is_value (tmp119) ;
return (tmp118) ;
} /* end of [hivaldec_is_value_27] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 9013(line=449, offs=1) -- 9104(line=451, offs=43)
*/
ATSstaticdec()
ats_bool_type
hivaldecs_is_value_28 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp120) ;

__ats_lab_hivaldecs_is_value_28:
tmp120 = list_forall_fun_01367_ats_ptr_type (arg0, &hivaldec_is_value_27) ;
return (tmp120) ;
} /* end of [hivaldecs_is_value_28] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 9158(line=457, offs=3) -- 9677(line=487, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_is_value (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp121) ;
ATSlocal (ats_ptr_type, tmp122) ;
ATSlocal (ats_ptr_type, tmp123) ;
ATSlocal (ats_ptr_type, tmp124) ;
ATSlocal (ats_ptr_type, tmp125) ;
ATSlocal (ats_bool_type, tmp126) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_is_value:
tmp122 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_15, arg0), atslab_hidexp_node) ;
do {
/* branch: __ats_lab_76 */
__ats_lab_76_0:
if (((ats_sum_ptr_type)tmp122)->tag != 1) { goto __ats_lab_77_0 ; }
__ats_lab_76_1:
tmp121 = ats_true_bool ;
break ;

/* branch: __ats_lab_77 */
__ats_lab_77_0:
if (((ats_sum_ptr_type)tmp122)->tag != 0) { goto __ats_lab_78_0 ; }
__ats_lab_77_1:
tmp121 = ats_true_bool ;
break ;

/* branch: __ats_lab_78 */
__ats_lab_78_0:
if (((ats_sum_ptr_type)tmp122)->tag != 4) { goto __ats_lab_79_0 ; }
__ats_lab_78_1:
tmp121 = ats_true_bool ;
break ;

/* branch: __ats_lab_79 */
__ats_lab_79_0:
if (((ats_sum_ptr_type)tmp122)->tag != 5) { goto __ats_lab_80_0 ; }
__ats_lab_79_1:
tmp121 = ats_true_bool ;
break ;

/* branch: __ats_lab_80 */
__ats_lab_80_0:
if (((ats_sum_ptr_type)tmp122)->tag != 7) { goto __ats_lab_81_0 ; }
__ats_lab_80_1:
tmp121 = ats_true_bool ;
break ;

/* branch: __ats_lab_81 */
__ats_lab_81_0:
if (((ats_sum_ptr_type)tmp122)->tag != 8) { goto __ats_lab_82_0 ; }
__ats_lab_81_1:
tmp121 = ats_true_bool ;
break ;

/* branch: __ats_lab_82 */
__ats_lab_82_0:
if (((ats_sum_ptr_type)tmp122)->tag != 9) { goto __ats_lab_83_0 ; }
__ats_lab_82_1:
tmp121 = ats_true_bool ;
break ;

/* branch: __ats_lab_83 */
__ats_lab_83_0:
if (((ats_sum_ptr_type)tmp122)->tag != 16) { goto __ats_lab_84_0 ; }
__ats_lab_83_1:
tmp121 = ats_true_bool ;
break ;

/* branch: __ats_lab_84 */
__ats_lab_84_0:
if (((ats_sum_ptr_type)tmp122)->tag != 46) { goto __ats_lab_85_0 ; }
__ats_lab_84_1:
tmp121 = ats_true_bool ;
break ;

/* branch: __ats_lab_85 */
__ats_lab_85_0:
if (((ats_sum_ptr_type)tmp122)->tag != 30) { goto __ats_lab_86_0 ; }
__ats_lab_85_1:
tmp123 = ats_caselptrlab_mac(anairiats_sum_12, tmp122, atslab_1) ;
tmp121 = labhidexplst_is_value_23 (tmp123) ;
break ;

/* branch: __ats_lab_86 */
__ats_lab_86_0:
if (((ats_sum_ptr_type)tmp122)->tag != 20) { goto __ats_lab_87_0 ; }
__ats_lab_86_1:
tmp121 = ats_true_bool ;
break ;

/* branch: __ats_lab_87 */
__ats_lab_87_0:
if (((ats_sum_ptr_type)tmp122)->tag != 21) { goto __ats_lab_88_0 ; }
__ats_lab_87_1:
tmp121 = ats_true_bool ;
break ;

/* branch: __ats_lab_88 */
__ats_lab_88_0:
if (((ats_sum_ptr_type)tmp122)->tag != 24) { goto __ats_lab_89_0 ; }
__ats_lab_88_1:
tmp124 = ats_caselptrlab_mac(anairiats_sum_5, tmp122, atslab_0) ;
tmp125 = ats_caselptrlab_mac(anairiats_sum_5, tmp122, atslab_1) ;
tmp126 = hideclist_is_value_26 (tmp124) ;
if (tmp126) {
arg0 = tmp125 ;
goto __ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_is_value ; // tail call
} else {
tmp121 = ats_false_bool ;
} /* end of [if] */
break ;

/* branch: __ats_lab_89 */
__ats_lab_89_0:
__ats_lab_89_1:
tmp121 = ats_false_bool ;
break ;
} while (0) ;
return (tmp121) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_is_value] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 9762(line=496, offs=1) -- 9914(line=504, offs=2)
*/
ATSstaticdec()
ats_bool_type
auxseq_30 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp127) ;
ATSlocal (ats_ptr_type, tmp128) ;
ATSlocal (ats_ptr_type, tmp129) ;

__ats_lab_auxseq_30:
do {
/* branch: __ats_lab_90 */
__ats_lab_90_0:
if (arg1 != (ats_sum_ptr_type)0) { goto __ats_lab_91_0 ; }
__ats_lab_90_1:
tmp127 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_is_lvalue (arg0) ;
break ;

/* branch: __ats_lab_91 */
__ats_lab_91_0:
// if (arg1 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_91_1:
tmp128 = ats_caselptrlab_mac(anairiats_sum_6, arg1, atslab_0) ;
tmp129 = ats_caselptrlab_mac(anairiats_sum_6, arg1, atslab_1) ;
arg0 = tmp128 ;
arg1 = tmp129 ;
goto __ats_lab_auxseq_30 ; // tail call
break ;
} while (0) ;
return (tmp127) ;
} /* end of [auxseq_30] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 9987(line=510, offs=3) -- 10353(line=528, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_is_lvalue (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp130) ;
ATSlocal (ats_ptr_type, tmp131) ;
ATSlocal (ats_ptr_type, tmp132) ;
ATSlocal (ats_ptr_type, tmp133) ;
ATSlocal (ats_ptr_type, tmp134) ;
ATSlocal (ats_ptr_type, tmp135) ;
ATSlocal (ats_ptr_type, tmp136) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_is_lvalue:
tmp131 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_15, arg0), atslab_hidexp_node) ;
do {
/* branch: __ats_lab_92 */
__ats_lab_92_0:
if (((ats_sum_ptr_type)tmp131)->tag != 1) { goto __ats_lab_93_0 ; }
__ats_lab_92_1:
tmp132 = ats_caselptrlab_mac(anairiats_sum_11, tmp131, atslab_0) ;
tmp130 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__d2var_is_mutabl (tmp132) ;
break ;

/* branch: __ats_lab_93 */
__ats_lab_93_0:
if (((ats_sum_ptr_type)tmp131)->tag != 36) { goto __ats_lab_94_0 ; }
__ats_lab_93_1:
tmp133 = ats_caselptrlab_mac(anairiats_sum_3, tmp131, atslab_0) ;
tmp130 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__d2var_is_mutabl (tmp133) ;
break ;

/* branch: __ats_lab_94 */
__ats_lab_94_0:
if (((ats_sum_ptr_type)tmp131)->tag != 37) { goto __ats_lab_95_0 ; }
__ats_lab_94_1:
tmp130 = ats_true_bool ;
break ;

/* branch: __ats_lab_95 */
__ats_lab_95_0:
if (((ats_sum_ptr_type)tmp131)->tag != 31) { goto __ats_lab_98_0 ; }
__ats_lab_95_1:
tmp134 = ats_caselptrlab_mac(anairiats_sum_11, tmp131, atslab_0) ;
do {
/* branch: __ats_lab_96 */
__ats_lab_96_0:
if (tmp134 == (ats_sum_ptr_type)0) { goto __ats_lab_97_0 ; }
__ats_lab_96_1:
tmp135 = ats_caselptrlab_mac(anairiats_sum_6, tmp134, atslab_0) ;
tmp136 = ats_caselptrlab_mac(anairiats_sum_6, tmp134, atslab_1) ;
tmp130 = auxseq_30 (tmp135, tmp136) ;
break ;

/* branch: __ats_lab_97 */
__ats_lab_97_0:
// if (tmp134 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_97_1:
tmp130 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_98 */
__ats_lab_98_0:
__ats_lab_98_1:
tmp130 = ats_false_bool ;
break ;
} while (0) ;
return (tmp130) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_is_lvalue] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/list.dats: 50443(line=1783, offs=17) -- 50505(line=1785, offs=4)
*/
ATSstaticdec()
ats_bool_type
list_is_nil_01294_ (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp140) ;

__ats_lab_list_is_nil_01294_:
do {
/* branch: __ats_lab_101 */
__ats_lab_101_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_102_0 ; }
__ats_lab_101_1:
tmp140 = ats_false_bool ;
break ;

/* branch: __ats_lab_102 */
__ats_lab_102_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_102_1:
tmp140 = ats_true_bool ;
break ;
} while (0) ;
return (tmp140) ;
} /* end of [list_is_nil_01294_] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 10662(line=548, offs=17) -- 10968(line=567, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidecl_is_empty (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp137) ;
ATSlocal (ats_ptr_type, tmp138) ;
ATSlocal (ats_ptr_type, tmp139) ;
ATSlocal (ats_ptr_type, tmp141) ;
ATSlocal (ats_ptr_type, tmp142) ;
ATSlocal (ats_ptr_type, tmp143) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidecl_is_empty:
tmp138 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_13, arg0), atslab_hidecl_node) ;
do {
/* branch: __ats_lab_99 */
__ats_lab_99_0:
if (((ats_sum_ptr_type)tmp138)->tag != 0) { goto __ats_lab_100_0 ; }
__ats_lab_99_1:
tmp137 = ats_true_bool ;
break ;

/* branch: __ats_lab_100 */
__ats_lab_100_0:
if (((ats_sum_ptr_type)tmp138)->tag != 1) { goto __ats_lab_103_0 ; }
__ats_lab_100_1:
tmp139 = ats_caselptrlab_mac(anairiats_sum_11, tmp138, atslab_0) ;
tmp137 = list_is_nil_01294_ (tmp139) ;
break ;

/* branch: __ats_lab_103 */
__ats_lab_103_0:
if (((ats_sum_ptr_type)tmp138)->tag != 10) { goto __ats_lab_104_0 ; }
__ats_lab_103_1:
tmp141 = ats_caselptrlab_mac(anairiats_sum_3, tmp138, atslab_2) ;
tmp137 = list_is_nil_01294_ (tmp141) ;
break ;

/* branch: __ats_lab_104 */
__ats_lab_104_0:
if (((ats_sum_ptr_type)tmp138)->tag != 11) { goto __ats_lab_105_0 ; }
__ats_lab_104_1:
tmp142 = ats_caselptrlab_mac(anairiats_sum_5, tmp138, atslab_1) ;
tmp137 = list_is_nil_01294_ (tmp142) ;
break ;

/* branch: __ats_lab_105 */
__ats_lab_105_0:
if (((ats_sum_ptr_type)tmp138)->tag != 12) { goto __ats_lab_106_0 ; }
__ats_lab_105_1:
tmp143 = ats_caselptrlab_mac(anairiats_sum_5, tmp138, atslab_1) ;
tmp137 = list_is_nil_01294_ (tmp143) ;
break ;

/* branch: __ats_lab_106 */
__ats_lab_106_0:
__ats_lab_106_1:
tmp137 = ats_false_bool ;
break ;
} while (0) ;
return (tmp137) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidecl_is_empty] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 11184(line=582, offs=5) -- 11750(line=602, offs=4)
*/
ATSstaticdec()
ats_ptr_type
hidexp_is_varemp_34 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp144) ;
ATSlocal (ats_ptr_type, tmp145) ;
ATSlocal (ats_ptr_type, tmp146) ;
ATSlocal (ats_int_type, tmp147) ;
ATSlocal (ats_ptr_type, tmp148) ;
ATSlocal (ats_bool_type, tmp149) ;
ATSlocal (ats_ptr_type, tmp150) ;
ATSlocal (ats_ptr_type, tmp151) ;
ATSlocal (ats_ptr_type, tmp152) ;

__ats_lab_hidexp_is_varemp_34:
tmp145 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_15, arg0), atslab_hidexp_node) ;
do {
/* branch: __ats_lab_107 */
__ats_lab_107_0:
if (((ats_sum_ptr_type)tmp145)->tag != 1) { goto __ats_lab_108_0 ; }
__ats_lab_107_1:
tmp146 = ats_caselptrlab_mac(anairiats_sum_11, tmp145, atslab_0) ;
tmp144 = ATS_MALLOC(sizeof(anairiats_sum_11)) ;
((ats_sum_ptr_type)tmp144)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_11, tmp144, atslab_0, tmp146) ;
break ;

/* branch: __ats_lab_108 */
__ats_lab_108_0:
if (((ats_sum_ptr_type)tmp145)->tag != 13) { goto __ats_lab_109_0 ; }
__ats_lab_108_1:
tmp144 = (ats_sum_ptr_type)(&_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HDEVEsome_emp_2) ;
break ;

/* branch: __ats_lab_109 */
__ats_lab_109_0:
if (((ats_sum_ptr_type)tmp145)->tag != 22) { goto __ats_lab_110_0 ; }
__ats_lab_109_1:
tmp144 = (ats_sum_ptr_type)(&_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HDEVEsome_emp_2) ;
break ;

/* branch: __ats_lab_110 */
__ats_lab_110_0:
if (((ats_sum_ptr_type)tmp145)->tag != 30) { goto __ats_lab_113_0 ; }
__ats_lab_110_1:
tmp147 = ats_caselptrlab_mac(anairiats_sum_12, tmp145, atslab_0) ;
tmp148 = ats_caselptrlab_mac(anairiats_sum_12, tmp145, atslab_1) ;
tmp149 = atspre_eq_int_int (tmp147, 0) ;
if (tmp149) {
do {
/* branch: __ats_lab_111 */
__ats_lab_111_0:
if (tmp148 == (ats_sum_ptr_type)0) { goto __ats_lab_112_0 ; }
tmp150 = ats_caselptrlab_mac(anairiats_sum_6, tmp148, atslab_1) ;
if (tmp150 != (ats_sum_ptr_type)0) { goto __ats_lab_112_0 ; }
__ats_lab_111_1:
tmp151 = ats_caselptrlab_mac(anairiats_sum_6, tmp148, atslab_0) ;
// 
tmp152 = ats_caselptrlab_mac(anairiats_sum_6, tmp151, atslab_1) ;
arg0 = tmp152 ;
goto __ats_lab_hidexp_is_varemp_34 ; // tail call
break ;

/* branch: __ats_lab_112 */
__ats_lab_112_0:
__ats_lab_112_1:
tmp144 = (ats_sum_ptr_type)(&_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HDEVEnone_0) ;
break ;
} while (0) ;
} else {
tmp144 = (ats_sum_ptr_type)(&_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HDEVEnone_0) ;
} /* end of [if] */
break ;

/* branch: __ats_lab_113 */
__ats_lab_113_0:
__ats_lab_113_1:
tmp144 = (ats_sum_ptr_type)(&_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HDEVEnone_0) ;
break ;
} while (0) ;
return (tmp144) ;
} /* end of [hidexp_is_varemp_34] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 11980(line=614, offs=5) -- 12500(line=637, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux_36 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp154) ;
ATSlocal (ats_ptr_type, tmp155) ;
ATSlocal (ats_ptr_type, tmp156) ;
ATSlocal (ats_int_type, tmp157) ;
ATSlocal (ats_ptr_type, tmp158) ;
ATSlocal (ats_bool_type, tmp159) ;
ATSlocal (ats_ptr_type, tmp160) ;
ATSlocal (ats_ptr_type, tmp161) ;
ATSlocal (ats_ptr_type, tmp162) ;

__ats_lab_aux_36:
tmp155 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_4, arg0), atslab_hipat_node) ;
do {
/* branch: __ats_lab_114 */
__ats_lab_114_0:
if (((ats_sum_ptr_type)tmp155)->tag != 0) { goto __ats_lab_115_0 ; }
__ats_lab_114_1:
tmp154 = ATS_MALLOC(sizeof(anairiats_sum_11)) ;
((ats_sum_ptr_type)tmp154)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_11, tmp154, atslab_0, arg1) ;
break ;

/* branch: __ats_lab_115 */
__ats_lab_115_0:
if (((ats_sum_ptr_type)tmp155)->tag != 1) { goto __ats_lab_116_0 ; }
__ats_lab_115_1:
tmp156 = ats_caselptrlab_mac(anairiats_sum_11, tmp155, atslab_0) ;
tmp154 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
((ats_sum_ptr_type)tmp154)->tag = 2 ;
ats_selptrset_mac(anairiats_sum_5, tmp154, atslab_0, tmp156) ;
ats_selptrset_mac(anairiats_sum_5, tmp154, atslab_1, arg1) ;
break ;

/* branch: __ats_lab_116 */
__ats_lab_116_0:
if (((ats_sum_ptr_type)tmp155)->tag != 10) { goto __ats_lab_117_0 ; }
__ats_lab_116_1:
tmp154 = ATS_MALLOC(sizeof(anairiats_sum_11)) ;
((ats_sum_ptr_type)tmp154)->tag = 3 ;
ats_selptrset_mac(anairiats_sum_11, tmp154, atslab_0, arg1) ;
break ;

/* branch: __ats_lab_117 */
__ats_lab_117_0:
if (((ats_sum_ptr_type)tmp155)->tag != 13) { goto __ats_lab_120_0 ; }
__ats_lab_117_1:
tmp157 = ats_caselptrlab_mac(anairiats_sum_12, tmp155, atslab_0) ;
tmp158 = ats_caselptrlab_mac(anairiats_sum_12, tmp155, atslab_1) ;
tmp159 = atspre_eq_int_int (tmp157, 0) ;
if (tmp159) {
do {
/* branch: __ats_lab_118 */
__ats_lab_118_0:
if (tmp158 == (ats_sum_ptr_type)0) { goto __ats_lab_119_0 ; }
tmp160 = ats_caselptrlab_mac(anairiats_sum_6, tmp158, atslab_1) ;
if (tmp160 != (ats_sum_ptr_type)0) { goto __ats_lab_119_0 ; }
__ats_lab_118_1:
tmp161 = ats_caselptrlab_mac(anairiats_sum_6, tmp158, atslab_0) ;
// 
tmp162 = ats_caselptrlab_mac(anairiats_sum_6, tmp161, atslab_1) ;
arg0 = tmp162 ;
arg1 = arg1 ;
goto __ats_lab_aux_36 ; // tail call
break ;

/* branch: __ats_lab_119 */
__ats_lab_119_0:
__ats_lab_119_1:
tmp154 = (ats_sum_ptr_type)(&_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HABNDnone_0) ;
break ;
} while (0) ;
} else {
tmp154 = (ats_sum_ptr_type)(&_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HABNDnone_0) ;
} /* end of [if] */
break ;

/* branch: __ats_lab_120 */
__ats_lab_120_0:
__ats_lab_120_1:
tmp154 = (ats_sum_ptr_type)(&_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HABNDnone_0) ;
break ;
} while (0) ;
return (tmp154) ;
} /* end of [aux_36] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 11921(line=611, offs=5) -- 12771(line=651, offs=4)
*/
ATSstaticdec()
ats_ptr_type
hidecl_is_anybind_35 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp153) ;
ATSlocal (ats_ptr_type, tmp163) ;
ATSlocal (ats_ptr_type, tmp164) ;
ATSlocal (ats_ptr_type, tmp165) ;
ATSlocal (ats_ptr_type, tmp166) ;
ATSlocal (ats_ptr_type, tmp167) ;
ATSlocal (ats_ptr_type, tmp168) ;

__ats_lab_hidecl_is_anybind_35:
tmp163 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_13, arg0), atslab_hidecl_node) ;
do {
/* branch: __ats_lab_121 */
__ats_lab_121_0:
if (((ats_sum_ptr_type)tmp163)->tag != 11) { goto __ats_lab_124_0 ; }
__ats_lab_121_1:
tmp164 = ats_caselptrlab_mac(anairiats_sum_5, tmp163, atslab_1) ;
do {
/* branch: __ats_lab_122 */
__ats_lab_122_0:
if (tmp164 == (ats_sum_ptr_type)0) { goto __ats_lab_123_0 ; }
tmp165 = ats_caselptrlab_mac(anairiats_sum_6, tmp164, atslab_1) ;
if (tmp165 != (ats_sum_ptr_type)0) { goto __ats_lab_123_0 ; }
__ats_lab_122_1:
tmp166 = ats_caselptrlab_mac(anairiats_sum_6, tmp164, atslab_0) ;
tmp167 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_14, tmp166), atslab_hivaldec_pat) ;
tmp168 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_14, tmp166), atslab_hivaldec_def) ;
tmp153 = aux_36 (tmp167, tmp168) ;
break ;

/* branch: __ats_lab_123 */
__ats_lab_123_0:
__ats_lab_123_1:
tmp153 = (ats_sum_ptr_type)(&_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HABNDnone_0) ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_124 */
__ats_lab_124_0:
__ats_lab_124_1:
tmp153 = (ats_sum_ptr_type)(&_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HABNDnone_0) ;
break ;
} while (0) ;
return (tmp153) ;
} /* end of [hidecl_is_anybind_35] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 12807(line=653, offs=5) -- 13010(line=667, offs=4)
*/
ATSstaticdec()
ats_ptr_type
dropz_37 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp169) ;
ATSlocal (ats_ptr_type, tmp170) ;
ATSlocal (ats_ptr_type, tmp171) ;
ATSlocal (ats_ptr_type, tmp172) ;

__ats_lab_dropz_37:
// if (arg0 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
tmp170 = ats_caselptrlab_mac(anairiats_sum_6, arg0, atslab_0) ;
tmp171 = ats_caselptrlab_mac(anairiats_sum_6, arg0, atslab_1) ;
do {
/* branch: __ats_lab_125 */
__ats_lab_125_0:
if (tmp171 == (ats_sum_ptr_type)0) { goto __ats_lab_126_0 ; }
__ats_lab_125_1:
tmp172 = dropz_37 (tmp171) ;
tmp169 = ATS_MALLOC(sizeof(anairiats_sum_6)) ;
ats_selptrset_mac(anairiats_sum_6, tmp169, atslab_0, tmp170) ;
ats_selptrset_mac(anairiats_sum_6, tmp169, atslab_1, tmp172) ;
break ;

/* branch: __ats_lab_126 */
__ats_lab_126_0:
// if (tmp171 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_126_1:
tmp169 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp169) ;
} /* end of [dropz_37] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/list.dats: 51232(line=1817, offs=5) -- 51354(line=1819, offs=58)
*/
ATSstaticdec()
ats_ptr_type
loop_40 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp178) ;
ATSlocal (ats_ptr_type, tmp179) ;
ATSlocal (ats_ptr_type, tmp180) ;

__ats_lab_loop_40:
do {
/* branch: __ats_lab_129 */
__ats_lab_129_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_130_0 ; }
__ats_lab_129_1:
tmp179 = ats_caselptrlab_mac(anairiats_sum_6, arg1, atslab_0) ;
tmp180 = ats_caselptrlab_mac(anairiats_sum_6, arg1, atslab_1) ;
arg0 = tmp179 ;
arg1 = tmp180 ;
goto __ats_lab_loop_40 ; // tail call
break ;

/* branch: __ats_lab_130 */
__ats_lab_130_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_130_1:
tmp178 = arg0 ;
break ;
} while (0) ;
return (tmp178) ;
} /* end of [loop_40] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/list.dats: 51194(line=1813, offs=11) -- 51390(line=1823, offs=2)
*/
ATSstaticdec()
ats_ptr_type
list_last_01407_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp177) ;
ATSlocal (ats_ptr_type, tmp181) ;
ATSlocal (ats_ptr_type, tmp182) ;

__ats_lab_list_last_01407_ats_ptr_type:
// if (arg0 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
tmp181 = ats_caselptrlab_mac(anairiats_sum_6, arg0, atslab_0) ;
tmp182 = ats_caselptrlab_mac(anairiats_sum_6, arg0, atslab_1) ;
tmp177 = loop_40 (tmp181, tmp182) ;
return (tmp177) ;
} /* end of [list_last_01407_ats_ptr_type] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_hidynexp_util.dats: 13086(line=673, offs=3) -- 14453(line=716, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_let_simplify (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp173) ;
ATSlocal (ats_ptr_type, tmp174) ;
ATSlocal (ats_ptr_type, tmp175) ;
ATSlocal (ats_ptr_type, tmp176) ;
ATSlocal (ats_ptr_type, tmp183) ;
ATSlocal (ats_ptr_type, tmp184) ;
ATSlocal (ats_ptr_type, tmp185) ;
ATSlocal (ats_bool_type, tmp186) ;
ATSlocal (ats_bool_type, tmp187) ;
ATSlocal (ats_ptr_type, tmp188) ;
ATSlocal (ats_ptr_type, tmp189) ;
ATSlocal (ats_ptr_type, tmp190) ;
ATSlocal (ats_ptr_type, tmp191) ;
ATSlocal (ats_ptr_type, tmp192) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_let_simplify:
do {
/* branch: __ats_lab_127 */
__ats_lab_127_0:
if (arg2 == (ats_sum_ptr_type)0) { goto __ats_lab_141_0 ; }
__ats_lab_127_1:
tmp174 = hidexp_is_varemp_34 (arg3) ;
do {
/* branch: __ats_lab_128 */
__ats_lab_128_0:
if (((ats_sum_ptr_type)tmp174)->tag != 1) { goto __ats_lab_135_0 ; }
__ats_lab_128_1:
tmp175 = ats_caselptrlab_mac(anairiats_sum_11, tmp174, atslab_0) ;
ATS_FREE(tmp174) ;
tmp176 = list_last_01407_ats_ptr_type (arg2) ;
tmp183 = hidecl_is_anybind_35 (tmp176) ;
do {
/* branch: __ats_lab_131 */
__ats_lab_131_0:
if (((ats_sum_ptr_type)tmp183)->tag != 0) { goto __ats_lab_132_0 ; }
__ats_lab_131_1:
tmp173 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_let (arg0, arg1, arg2, arg3) ;
break ;

/* branch: __ats_lab_132 */
__ats_lab_132_0:
if (((ats_sum_ptr_type)tmp183)->tag != 2) { goto __ats_lab_133_0 ; }
__ats_lab_132_1:
tmp184 = ats_caselptrlab_mac(anairiats_sum_5, tmp183, atslab_0) ;
tmp185 = ats_caselptrlab_mac(anairiats_sum_5, tmp183, atslab_1) ;
ATS_FREE(tmp183) ;
tmp187 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__eq_d2var_d2var (tmp175, tmp184) ;
tmp186 = atspre_neg_bool (tmp187) ;
if (tmp186) {
tmp173 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_let (arg0, arg1, arg2, arg3) ;
} else {
tmp188 = dropz_37 (arg2) ;
tmp173 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_let (arg0, arg1, tmp188, tmp185) ;
} /* end of [if] */
break ;

/* branch: __ats_lab_133 */
__ats_lab_133_0:
if (((ats_sum_ptr_type)tmp183)->tag != 1) { goto __ats_lab_134_0 ; }
__ats_lab_133_1:
ATS_FREE(tmp183) ;
tmp173 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_let (arg0, arg1, arg2, arg3) ;
break ;

/* branch: __ats_lab_134 */
__ats_lab_134_0:
// if (((ats_sum_ptr_type)tmp183)->tag != 3) { ats_deadcode_failure_handle () ; }
__ats_lab_134_1:
ATS_FREE(tmp183) ;
tmp173 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_let (arg0, arg1, arg2, arg3) ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_135 */
__ats_lab_135_0:
if (((ats_sum_ptr_type)tmp174)->tag != 2) { goto __ats_lab_140_0 ; }
__ats_lab_135_1:
tmp189 = list_last_01407_ats_ptr_type (arg2) ;
tmp190 = hidecl_is_anybind_35 (tmp189) ;
do {
/* branch: __ats_lab_136 */
__ats_lab_136_0:
if (((ats_sum_ptr_type)tmp190)->tag != 0) { goto __ats_lab_137_0 ; }
__ats_lab_136_1:
tmp173 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_let (arg0, arg1, arg2, arg3) ;
break ;

/* branch: __ats_lab_137 */
__ats_lab_137_0:
if (((ats_sum_ptr_type)tmp190)->tag != 3) { goto __ats_lab_138_0 ; }
__ats_lab_137_1:
tmp191 = ats_caselptrlab_mac(anairiats_sum_11, tmp190, atslab_0) ;
ATS_FREE(tmp190) ;
tmp192 = dropz_37 (arg2) ;
tmp173 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_let (arg0, arg1, tmp192, tmp191) ;
break ;

/* branch: __ats_lab_138 */
__ats_lab_138_0:
if (((ats_sum_ptr_type)tmp190)->tag != 1) { goto __ats_lab_139_0 ; }
__ats_lab_138_1:
ATS_FREE(tmp190) ;
tmp173 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_let (arg0, arg1, arg2, arg3) ;
break ;

/* branch: __ats_lab_139 */
__ats_lab_139_0:
// if (((ats_sum_ptr_type)tmp190)->tag != 2) { ats_deadcode_failure_handle () ; }
__ats_lab_139_1:
ATS_FREE(tmp190) ;
tmp173 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_let (arg0, arg1, arg2, arg3) ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_140 */
__ats_lab_140_0:
// if (((ats_sum_ptr_type)tmp174)->tag != 0) { ats_deadcode_failure_handle () ; }
__ats_lab_140_1:
tmp173 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_let (arg0, arg1, arg2, arg3) ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_141 */
__ats_lab_141_0:
// if (arg2 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_141_1:
tmp173 = arg3 ;
break ;
} while (0) ;
return (tmp173) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__hidexp_let_simplify] */

/* static load function */

// extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_atspre_2edats__staload (void) ;
// extern ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2unsafe_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_errmsg_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_errmsg_2edats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_basics_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_label_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_location_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_histaexp_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__staload (void) ;

ats_void_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__staload () {
static int _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__staload_flag) return ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__staload_flag = 1 ;

// _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_atspre_2edats__staload () ;
// ATS_2d0_2e2_2e12_2prelude_2SATS_2unsafe_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_errmsg_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_errmsg_2edats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_basics_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_label_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_location_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_histaexp_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_2esats__staload () ;

_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HDEVEnone_0.tag = 0 ;
// _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HDEVEsome_var_1.tag = 1 ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HDEVEsome_emp_2.tag = 2 ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HABNDnone_0.tag = 0 ;
// _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HABNDsome_any_1.tag = 1 ;
// _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HABNDsome_var_2.tag = 2 ;
// _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__HABNDsome_emp_3.tag = 3 ;
return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__dynload () {
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__dynload_flag = 1 ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_hidynexp_util_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e12_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____copy_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____free_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [pats_hidynexp_util_dats.c] */
