/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2016-7-23: 22h:12m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_e1xp_loc ;
ats_ptr_type atslab_e1xp_node ;
} anairiats_rec_0 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_1 ;

typedef struct {
ats_ptr_type atslab_0 ;
} anairiats_sum_2 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_3 ;

typedef
struct {
ats_ptr_type atslab_s2qua_svs ;
ats_ptr_type atslab_s2qua_sps ;
} anairiats_rec_4 ;

typedef struct {
anairiats_rec_4 atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_5 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_nil_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__None_vt_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__Some_vt_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp1_2esats__E1XPide_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp1_2esats__E1XPstring_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__S2ITMcst_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__D2ITMcst_0) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_bool_type, atspre_eq_string_string) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_string) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_symbol_2esats__fprint_symbol) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_symbol_2esats__symbol_get_name) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2rt_is_lin) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2rt_is_nonlin) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2rt_is_prgm) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2cst_is_datype) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2var_get_sym) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2var_get_srt) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__fprint_s2exp) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__d2cst_get_decarg) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans2_env_2esats__the_s2expenv_find) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans2_env_2esats__the_d2expenv_find) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_get_s2cst) (ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_bool_type aux_test_0 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type aux_find_4 (ats_ptr_type arg0) ;
static
ats_ptr_type aux_find_7 (ats_ptr_type arg0) ;
static
ats_void_type auxlst_10 (ats_ptr_type env0, ats_ptr_type arg0) ;
static
ats_clo_ptr_type auxlst_10_closure_make (ats_ptr_type env0) ;
static
ats_void_type auxlst_10_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) ;
static
ats_void_type aux_s2qua_9 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, anairiats_rec_4 arg3) ;
static
ats_void_type aux_s2qualst_11 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) ;
static
ats_void_type fprs2t_16 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_void_type loop_17 (ats_ptr_type env0, ats_ptr_type arg0) ;
static
ats_clo_ptr_type loop_17_closure_make (ats_ptr_type env0) ;
static
ats_void_type loop_17_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) ;
static
ats_void_type aux_15 (ats_ptr_type env0, anairiats_rec_4 arg0) ;
static
ats_clo_ptr_type aux_15_closure_make (ats_ptr_type env0) ;
static
ats_void_type aux_15_clofun (ats_clo_ptr_type cloptr, anairiats_rec_4 arg0) ;
static
ats_void_type auxlst_18 (ats_ptr_type env0, ats_ptr_type arg0) ;
static
ats_clo_ptr_type auxlst_18_closure_make (ats_ptr_type env0) ;
static
ats_void_type auxlst_18_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_codegen2_util.dats: 1714(line=60, offs=1) -- 1958(line=76, offs=2)
*/
ATSstaticdec()
ats_bool_type
aux_test_0 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp0) ;
ATSlocal (ats_ptr_type, tmp1) ;
ATSlocal (ats_ptr_type, tmp2) ;
ATSlocal (ats_ptr_type, tmp3) ;
ATSlocal (ats_ptr_type, tmp4) ;

__ats_lab_aux_test_0:
tmp1 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_0, arg0), atslab_e1xp_node) ;
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (((ats_sum_ptr_type)tmp1)->tag != 0) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp2 = ats_caselptrlab_mac(anairiats_sum_1, tmp1, atslab_0) ;
tmp3 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_symbol_2esats__symbol_get_name (tmp2) ;
tmp0 = atspre_eq_string_string (arg1, tmp3) ;
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
if (((ats_sum_ptr_type)tmp1)->tag != 5) { goto __ats_lab_2_0 ; }
__ats_lab_1_1:
tmp4 = ats_caselptrlab_mac(anairiats_sum_1, tmp1, atslab_0) ;
tmp0 = atspre_eq_string_string (arg1, tmp4) ;
break ;

/* branch: __ats_lab_2 */
__ats_lab_2_0:
__ats_lab_2_1:
tmp0 = ats_false_bool ;
break ;
} while (0) ;
return (tmp0) ;
} /* end of [aux_test_0] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_codegen2_util.dats: 2034(line=81, offs=17) -- 2063(line=81, offs=46)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__datcon_test_e1xp (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp5) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__datcon_test_e1xp:
tmp5 = aux_test_0 (arg0, ATSstrcst("datcon")) ;
return (tmp5) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__datcon_test_e1xp] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_codegen2_util.dats: 2093(line=83, offs=20) -- 2125(line=83, offs=52)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__datcontag_test_e1xp (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp6) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__datcontag_test_e1xp:
tmp6 = aux_test_0 (arg0, ATSstrcst("datcontag")) ;
return (tmp6) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__datcontag_test_e1xp] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_codegen2_util.dats: 2155(line=86, offs=17) -- 2184(line=86, offs=46)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__fprint_test_e1xp (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp7) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__fprint_test_e1xp:
tmp7 = aux_test_0 (arg0, ATSstrcst("fprint")) ;
return (tmp7) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__fprint_test_e1xp] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_codegen2_util.dats: 2243(line=95, offs=1) -- 2623(line=118, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux_find_4 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp8) ;
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_ptr_type, tmp10) ;
ATSlocal (ats_ptr_type, tmp11) ;
ATSlocal (ats_ptr_type, tmp12) ;

__ats_lab_aux_find_4:
tmp9 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans2_env_2esats__the_s2expenv_find (arg0) ;
do {
/* branch: __ats_lab_3 */
__ats_lab_3_0:
if (tmp9 == (ats_sum_ptr_type)0) { goto __ats_lab_8_0 ; }
__ats_lab_3_1:
tmp10 = ats_caselptrlab_mac(anairiats_sum_2, tmp9, atslab_0) ;
ATS_FREE(tmp9) ;
do {
/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (((ats_sum_ptr_type)tmp10)->tag != 1) { goto __ats_lab_7_0 ; }
__ats_lab_4_1:
tmp11 = ats_caselptrlab_mac(anairiats_sum_1, tmp10, atslab_0) ;
do {
/* branch: __ats_lab_5 */
__ats_lab_5_0:
if (tmp11 == (ats_sum_ptr_type)0) { goto __ats_lab_6_0 ; }
__ats_lab_5_1:
tmp12 = ats_caselptrlab_mac(anairiats_sum_3, tmp11, atslab_0) ;
tmp8 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, tmp8, atslab_0, tmp12) ;
break ;

/* branch: __ats_lab_6 */
__ats_lab_6_0:
// if (tmp11 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_6_1:
tmp8 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
__ats_lab_7_1:
tmp8 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_8 */
__ats_lab_8_0:
// if (tmp9 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_8_1:
tmp8 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp8) ;
} /* end of [aux_find_4] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_codegen2_util.dats: 2699(line=124, offs=3) -- 3070(line=154, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_get_s2cst (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp13) ;
ATSlocal (ats_ptr_type, tmp14) ;
ATSlocal (ats_ptr_type, tmp15) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_get_s2cst:
tmp14 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_0, arg0), atslab_e1xp_node) ;
do {
/* branch: __ats_lab_9 */
__ats_lab_9_0:
if (((ats_sum_ptr_type)tmp14)->tag != 0) { goto __ats_lab_10_0 ; }
__ats_lab_9_1:
tmp15 = ats_caselptrlab_mac(anairiats_sum_1, tmp14, atslab_0) ;
tmp13 = aux_find_4 (tmp15) ;
break ;

/* branch: __ats_lab_10 */
__ats_lab_10_0:
__ats_lab_10_1:
tmp13 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp13) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_get_s2cst] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_codegen2_util.dats: 3179(line=162, offs=3) -- 3443(line=177, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_get_datype (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp16) ;
ATSlocal (ats_ptr_type, tmp17) ;
ATSlocal (ats_ptr_type, tmp18) ;
ATSlocal (ats_bool_type, tmp19) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_get_datype:
tmp17 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_get_s2cst (arg0) ;
do {
/* branch: __ats_lab_11 */
__ats_lab_11_0:
if (tmp17 == (ats_sum_ptr_type)0) { goto __ats_lab_12_0 ; }
__ats_lab_11_1:
tmp18 = ats_caselptrlab_mac(anairiats_sum_2, tmp17, atslab_0) ;
tmp19 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2cst_is_datype (tmp18) ;
if (tmp19) {
tmp16 = tmp17 ;
} else {
ATS_FREE(tmp17) ;
tmp16 = (ats_sum_ptr_type)0 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_12 */
__ats_lab_12_0:
// if (tmp17 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_12_1:
tmp16 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp16) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_get_datype] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_codegen2_util.dats: 3509(line=184, offs=1) -- 3801(line=203, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux_find_7 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp20) ;
ATSlocal (ats_ptr_type, tmp21) ;
ATSlocal (ats_ptr_type, tmp22) ;
ATSlocal (ats_ptr_type, tmp23) ;

__ats_lab_aux_find_7:
tmp21 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans2_env_2esats__the_d2expenv_find (arg0) ;
do {
/* branch: __ats_lab_13 */
__ats_lab_13_0:
if (tmp21 == (ats_sum_ptr_type)0) { goto __ats_lab_16_0 ; }
__ats_lab_13_1:
tmp22 = ats_caselptrlab_mac(anairiats_sum_2, tmp21, atslab_0) ;
ATS_FREE(tmp21) ;
do {
/* branch: __ats_lab_14 */
__ats_lab_14_0:
if (((ats_sum_ptr_type)tmp22)->tag != 0) { goto __ats_lab_15_0 ; }
__ats_lab_14_1:
tmp23 = ats_caselptrlab_mac(anairiats_sum_1, tmp22, atslab_0) ;
tmp20 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, tmp20, atslab_0, tmp23) ;
break ;

/* branch: __ats_lab_15 */
__ats_lab_15_0:
__ats_lab_15_1:
tmp20 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_16 */
__ats_lab_16_0:
// if (tmp21 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_16_1:
tmp20 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp20) ;
} /* end of [aux_find_7] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_codegen2_util.dats: 3877(line=209, offs=3) -- 4245(line=238, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_get_d2cst (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp24) ;
ATSlocal (ats_ptr_type, tmp25) ;
ATSlocal (ats_ptr_type, tmp26) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_get_d2cst:
tmp25 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_0, arg0), atslab_e1xp_node) ;
do {
/* branch: __ats_lab_17 */
__ats_lab_17_0:
if (((ats_sum_ptr_type)tmp25)->tag != 0) { goto __ats_lab_18_0 ; }
__ats_lab_17_1:
tmp26 = ats_caselptrlab_mac(anairiats_sum_1, tmp25, atslab_0) ;
tmp24 = aux_find_7 (tmp26) ;
break ;

/* branch: __ats_lab_18 */
__ats_lab_18_0:
__ats_lab_18_1:
tmp24 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp24) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_get_d2cst] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_codegen2_util.dats: 4423(line=254, offs=1) -- 4589(line=265, offs=2)
*/
ATSstaticdec()
ats_void_type
auxlst_10 (ats_ptr_type env0, ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp28) ;
ATSlocal (ats_ptr_type, tmp29) ;
ATSlocal (ats_ptr_type, tmp30) ;
// ATSlocal_void (tmp31) ;
ATSlocal (ats_ptr_type, tmp32) ;

__ats_lab_auxlst_10:
do {
/* branch: __ats_lab_19 */
__ats_lab_19_0:
if (arg0 != (ats_sum_ptr_type)0) { goto __ats_lab_20_0 ; }
__ats_lab_19_1:
break ;

/* branch: __ats_lab_20 */
__ats_lab_20_0:
// if (arg0 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_20_1:
tmp29 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_0) ;
tmp30 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_1) ;
tmp32 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2var_get_sym (tmp29) ;
/* tmp31 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_symbol_2esats__fprint_symbol (env0, tmp32) ;
arg0 = tmp30 ;
goto __ats_lab_auxlst_10 ; // tail call
break ;
} while (0) ;
return /* (tmp28) */ ;
} /* end of [auxlst_10] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_ptr_type closure_env_0 ;
} auxlst_10_closure_type ;

ats_void_type
auxlst_10_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) {
auxlst_10 (((auxlst_10_closure_type*)cloptr)->closure_env_0, arg0) ; return ;
} /* end of function */

ATSinline()
ats_void_type
auxlst_10_closure_init (auxlst_10_closure_type *p_clo, ats_ptr_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&auxlst_10_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

ats_clo_ptr_type
auxlst_10_closure_make (ats_ptr_type env0) {
auxlst_10_closure_type *p_clo = ATS_MALLOC(sizeof(auxlst_10_closure_type)) ;
auxlst_10_closure_init (p_clo, env0) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_codegen2_util.dats: 4333(line=247, offs=1) -- 4661(line=269, offs=4)
*/
ATSstaticdec()
ats_void_type
aux_s2qua_9 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, anairiats_rec_4 arg3) {
/* local vardec */
// ATSlocal_void (tmp27) ;
// ATSlocal_void (tmp33) ;
// ATSlocal_void (tmp34) ;
ATSlocal (ats_ptr_type, tmp35) ;

__ats_lab_aux_s2qua_9:
/* tmp33 = */ atspre_fprint_string (arg0, arg1) ;
tmp35 = ats_select_mac(arg3, atslab_s2qua_svs) ;
/* tmp34 = */ auxlst_10 (arg0, tmp35) ;
/* tmp27 = */ atspre_fprint_string (arg0, arg2) ;
return /* (tmp27) */ ;
} /* end of [aux_s2qua_9] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_codegen2_util.dats: 4689(line=272, offs=1) -- 4953(line=286, offs=2)
*/
ATSstaticdec()
ats_void_type
aux_s2qualst_11 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) {
/* local vardec */
// ATSlocal_void (tmp36) ;
ATSlocal (anairiats_rec_4, tmp37) ;
ATSlocal (ats_ptr_type, tmp38) ;
// ATSlocal_void (tmp39) ;

__ats_lab_aux_s2qualst_11:
do {
/* branch: __ats_lab_21 */
__ats_lab_21_0:
if (arg3 != (ats_sum_ptr_type)0) { goto __ats_lab_22_0 ; }
__ats_lab_21_1:
break ;

/* branch: __ats_lab_22 */
__ats_lab_22_0:
// if (arg3 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_22_1:
tmp37 = ats_caselptrlab_mac(anairiats_sum_5, arg3, atslab_0) ;
tmp38 = ats_caselptrlab_mac(anairiats_sum_5, arg3, atslab_1) ;
/* tmp39 = */ aux_s2qua_9 (arg0, arg1, arg2, tmp37) ;
arg0 = arg0 ;
arg1 = arg1 ;
arg2 = arg2 ;
arg3 = tmp38 ;
goto __ats_lab_aux_s2qualst_11 ; // tail call
break ;
} while (0) ;
return /* (tmp36) */ ;
} /* end of [aux_s2qualst_11] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_codegen2_util.dats: 5041(line=292, offs=3) -- 5145(line=300, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_emit_tmpcstapp (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp40) ;
ATSlocal (ats_ptr_type, tmp41) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_emit_tmpcstapp:
tmp41 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__d2cst_get_decarg (arg1) ;
/* tmp40 = */ aux_s2qualst_11 (arg0, ATSstrcst("<"), ATSstrcst(">"), tmp41) ;
return /* (tmp40) */ ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_emit_tmpcstapp] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_codegen2_util.dats: 5219(line=304, offs=3) -- 5323(line=312, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_emit_tmpcstimp (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp42) ;
ATSlocal (ats_ptr_type, tmp43) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_emit_tmpcstimp:
tmp43 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__d2cst_get_decarg (arg1) ;
/* tmp42 = */ aux_s2qualst_11 (arg0, ATSstrcst("{"), ATSstrcst("}"), tmp43) ;
return /* (tmp42) */ ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_emit_tmpcstimp] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_codegen2_util.dats: 5516(line=329, offs=1) -- 5719(line=342, offs=2)
*/
ATSstaticdec()
ats_void_type
fprs2t_16 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp46) ;
ATSlocal (ats_bool_type, tmp47) ;
// ATSlocal_void (tmp48) ;
ATSlocal (ats_bool_type, tmp49) ;
ATSlocal (ats_bool_type, tmp50) ;

__ats_lab_fprs2t_16:
tmp47 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2rt_is_prgm (arg1) ;
if (tmp47) {
tmp49 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2rt_is_lin (arg1) ;
if (tmp49) {
/* tmp48 = */ atspre_fprint_string (arg0, ATSstrcst("vt0p")) ;
} else {
/* empty */
} /* end of [if] */
tmp50 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2rt_is_nonlin (arg1) ;
if (tmp50) {
/* tmp46 = */ atspre_fprint_string (arg0, ATSstrcst("t0p")) ;
} else {
/* empty */
} /* end of [if] */
} else {
/* empty */
} /* end of [if] */
return /* (tmp46) */ ;
} /* end of [fprs2t_16] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_codegen2_util.dats: 5749(line=345, offs=1) -- 6040(line=361, offs=2)
*/
ATSstaticdec()
ats_void_type
loop_17 (ats_ptr_type env0, ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp51) ;
ATSlocal (ats_ptr_type, tmp52) ;
ATSlocal (ats_ptr_type, tmp53) ;
ATSlocal (ats_ptr_type, tmp54) ;
ATSlocal (ats_ptr_type, tmp55) ;
// ATSlocal_void (tmp56) ;
// ATSlocal_void (tmp57) ;
// ATSlocal_void (tmp58) ;

__ats_lab_loop_17:
do {
/* branch: __ats_lab_23 */
__ats_lab_23_0:
if (arg0 != (ats_sum_ptr_type)0) { goto __ats_lab_24_0 ; }
__ats_lab_23_1:
break ;

/* branch: __ats_lab_24 */
__ats_lab_24_0:
// if (arg0 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_24_1:
tmp52 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_0) ;
tmp53 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_1) ;
tmp54 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2var_get_sym (tmp52) ;
tmp55 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2var_get_srt (tmp52) ;
/* tmp56 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_symbol_2esats__fprint_symbol (env0, tmp54) ;
/* tmp57 = */ atspre_fprint_string (env0, ATSstrcst(":")) ;
/* tmp58 = */ fprs2t_16 (env0, tmp55) ;
arg0 = tmp53 ;
goto __ats_lab_loop_17 ; // tail call
break ;
} while (0) ;
return /* (tmp51) */ ;
} /* end of [loop_17] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_ptr_type closure_env_0 ;
} loop_17_closure_type ;

ats_void_type
loop_17_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) {
loop_17 (((loop_17_closure_type*)cloptr)->closure_env_0, arg0) ; return ;
} /* end of function */

ATSinline()
ats_void_type
loop_17_closure_init (loop_17_closure_type *p_clo, ats_ptr_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&loop_17_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

ats_clo_ptr_type
loop_17_closure_make (ats_ptr_type env0) {
loop_17_closure_type *p_clo = ATS_MALLOC(sizeof(loop_17_closure_type)) ;
loop_17_closure_init (p_clo, env0) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_codegen2_util.dats: 5466(line=323, offs=1) -- 6128(line=367, offs=4)
*/
ATSstaticdec()
ats_void_type
aux_15 (ats_ptr_type env0, anairiats_rec_4 arg0) {
/* local vardec */
// ATSlocal_void (tmp45) ;
ATSlocal (ats_ptr_type, tmp59) ;
// ATSlocal_void (tmp60) ;
// ATSlocal_void (tmp61) ;

__ats_lab_aux_15:
tmp59 = ats_select_mac(arg0, atslab_s2qua_svs) ;
/* tmp60 = */ atspre_fprint_string (env0, ATSstrcst("{")) ;
/* tmp61 = */ loop_17 (env0, tmp59) ;
/* tmp45 = */ atspre_fprint_string (env0, ATSstrcst("}")) ;
return /* (tmp45) */ ;
} /* end of [aux_15] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_ptr_type closure_env_0 ;
} aux_15_closure_type ;

ats_void_type
aux_15_clofun (ats_clo_ptr_type cloptr, anairiats_rec_4 arg0) {
aux_15 (((aux_15_closure_type*)cloptr)->closure_env_0, arg0) ; return ;
} /* end of function */

ATSinline()
ats_void_type
aux_15_closure_init (aux_15_closure_type *p_clo, ats_ptr_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&aux_15_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

ats_clo_ptr_type
aux_15_closure_make (ats_ptr_type env0) {
aux_15_closure_type *p_clo = ATS_MALLOC(sizeof(aux_15_closure_type)) ;
aux_15_closure_init (p_clo, env0) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_codegen2_util.dats: 6150(line=370, offs=1) -- 6283(line=378, offs=2)
*/
ATSstaticdec()
ats_void_type
auxlst_18 (ats_ptr_type env0, ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp62) ;
ATSlocal (anairiats_rec_4, tmp63) ;
ATSlocal (ats_ptr_type, tmp64) ;
// ATSlocal_void (tmp65) ;

__ats_lab_auxlst_18:
do {
/* branch: __ats_lab_25 */
__ats_lab_25_0:
if (arg0 != (ats_sum_ptr_type)0) { goto __ats_lab_26_0 ; }
__ats_lab_25_1:
break ;

/* branch: __ats_lab_26 */
__ats_lab_26_0:
// if (arg0 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_26_1:
tmp63 = ats_caselptrlab_mac(anairiats_sum_5, arg0, atslab_0) ;
tmp64 = ats_caselptrlab_mac(anairiats_sum_5, arg0, atslab_1) ;
/* tmp65 = */ aux_15 (env0, tmp63) ;
arg0 = tmp64 ;
goto __ats_lab_auxlst_18 ; // tail call
break ;
} while (0) ;
return /* (tmp62) */ ;
} /* end of [auxlst_18] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_ptr_type closure_env_0 ;
} auxlst_18_closure_type ;

ats_void_type
auxlst_18_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) {
auxlst_18 (((auxlst_18_closure_type*)cloptr)->closure_env_0, arg0) ; return ;
} /* end of function */

ATSinline()
ats_void_type
auxlst_18_closure_init (auxlst_18_closure_type *p_clo, ats_ptr_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&auxlst_18_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

ats_clo_ptr_type
auxlst_18_closure_make (ats_ptr_type env0) {
auxlst_18_closure_type *p_clo = ATS_MALLOC(sizeof(auxlst_18_closure_type)) ;
auxlst_18_closure_init (p_clo, env0) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_codegen2_util.dats: 5441(line=320, offs=3) -- 6348(line=382, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_emit_tmpcstdec (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp44) ;
ATSlocal (ats_ptr_type, tmp66) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_emit_tmpcstdec:
tmp66 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__d2cst_get_decarg (arg1) ;
/* tmp44 = */ auxlst_18 (arg0, tmp66) ;
return /* (tmp44) */ ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_emit_tmpcstdec] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_codegen2_util.dats: 6441(line=388, offs=3) -- 6491(line=391, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_emit_s2exp (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp67) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_emit_s2exp:
/* tmp67 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__fprint_s2exp (arg0, arg1) ;
return /* (tmp67) */ ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__codegen2_emit_s2exp] */

/* static load function */

extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_symbol_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp1_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans2_env_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__staload (void) ;

ats_void_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_util_2edats__staload () {
static int _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_util_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_util_2edats__staload_flag) return ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_util_2edats__staload_flag = 1 ;

_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_symbol_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp1_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans2_env_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_util_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_util_2edats__dynload () {
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_util_2edats__dynload_flag = 1 ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_codegen2_util_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [pats_codegen2_util_dats.c] */
