######
##
## The Perl code is generated by atscc2pl
## The starting compilation time is: 2017-4-11: 16h:58m
##
######
sub
_ats2plpre_list_patsfun_35__closurerize($)
{
  my($env0) = @_;
  return [sub{ my($cenv, $arg0) = @_; return _ats2plpre_list_patsfun_35($cenv->[1], $arg0); }, $env0];
}

sub
_ats2plpre_list_patsfun_39__closurerize($)
{
  my($env0) = @_;
  return [sub{ my($cenv, $arg0) = @_; return _ats2plpre_list_patsfun_39($cenv->[1], $arg0); }, $env0];
}

sub
_ats2plpre_list_patsfun_42__closurerize($)
{
  my($env0) = @_;
  return [sub{ my($cenv, $arg0) = @_; return _ats2plpre_list_patsfun_42($cenv->[1], $arg0); }, $env0];
}

sub
_ats2plpre_list_patsfun_46__closurerize($)
{
  my($env0) = @_;
  return [sub{ my($cenv, $arg0) = @_; return _ats2plpre_list_patsfun_46($cenv->[1], $arg0); }, $env0];
}

sub
_ats2plpre_list_patsfun_50__closurerize($)
{
  my($env0) = @_;
  return [sub{ my($cenv, $arg0) = @_; return _ats2plpre_list_patsfun_50($cenv->[1], $arg0); }, $env0];
}

sub
_ats2plpre_list_patsfun_54__closurerize($)
{
  my($env0) = @_;
  return [sub{ my($cenv, $arg0) = @_; return _ats2plpre_list_patsfun_54($cenv->[1], $arg0); }, $env0];
}

sub
_ats2plpre_list_patsfun_57__closurerize($)
{
  my($env0) = @_;
  return [sub{ my($cenv, $arg0) = @_; return _ats2plpre_list_patsfun_57($cenv->[1], $arg0); }, $env0];
}

sub
_ats2plpre_list_patsfun_61__closurerize($)
{
  my($env0) = @_;
  return [sub{ my($cenv, $arg0) = @_; return _ats2plpre_list_patsfun_61($cenv->[1], $arg0); }, $env0];
}

sub
_ats2plpre_list_patsfun_65__closurerize($)
{
  my($env0) = @_;
  return [sub{ my($cenv, $arg0) = @_; return _ats2plpre_list_patsfun_65($cenv->[1], $arg0); }, $env0];
}

sub
_ats2plpre_list_patsfun_69__closurerize($$)
{
  my($env0, $env1) = @_;
  return [sub{ my($cenv, $arg0) = @_; return _ats2plpre_list_patsfun_69($cenv->[1], $cenv->[2], $arg0); }, $env0, $env1];
}

sub
_ats2plpre_list_patsfun_73__closurerize($$)
{
  my($env0, $env1) = @_;
  return [sub{ my($cenv, $arg0) = @_; return _ats2plpre_list_patsfun_73($cenv->[1], $cenv->[2], $arg0); }, $env0, $env1];
}

sub
_ats2plpre_list_patsfun_77__closurerize($$)
{
  my($env0, $env1) = @_;
  return [sub{ my($cenv, $arg0) = @_; return _ats2plpre_list_patsfun_77($cenv->[1], $cenv->[2], $arg0); }, $env0, $env1];
}

sub
_ats2plpre_list_patsfun_81__closurerize($$)
{
  my($env0, $env1) = @_;
  return [sub{ my($cenv, $arg0) = @_; return _ats2plpre_list_patsfun_81($cenv->[1], $cenv->[2], $arg0); }, $env0, $env1];
}

sub
_ats2plpre_list_patsfun_86__closurerize($)
{
  my($env0) = @_;
  return [sub{ my($cenv, $arg0) = @_; return _ats2plpre_list_patsfun_86($cenv->[1], $arg0); }, $env0];
}

sub
_ats2plpre_list_patsfun_89__closurerize($$)
{
  my($env0, $env1) = @_;
  return [sub{ my($cenv, $arg0) = @_; return _ats2plpre_list_patsfun_89($cenv->[1], $cenv->[2], $arg0); }, $env0, $env1];
}

sub
_ats2plpre_list_patsfun_92__closurerize($$)
{
  my($env0, $env1) = @_;
  return [sub{ my($cenv, $arg0) = @_; return _ats2plpre_list_patsfun_92($cenv->[1], $cenv->[2], $arg0); }, $env0, $env1];
}

sub
_ats2plpre_list_patsfun_94__closurerize($$)
{
  my($env0, $env1) = @_;
  return [sub{ my($cenv, $arg0) = @_; return _ats2plpre_list_patsfun_94($cenv->[1], $cenv->[2], $arg0); }, $env0, $env1];
}


sub
ats2plpre_list_make_elt($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret2;
  my $tmp7;
##
  __patsflab_list_make_elt:
  $tmp7 = 0;
  $tmpret2 = _ats2plpre_list_loop_3($arg1, $arg0, $tmp7);
  return $tmpret2;
} #end-of-function


sub
_ats2plpre_list_loop_3($$$)
{
##
  my($env0, $arg0, $arg1) = @_;
##
  my $apy0;
  my $apy1;
  my $tmpret3;
  my $tmp4;
  my $tmp5;
  my $tmp6;
##
  __patsflab__ats2plpre_list_loop_3:
  $tmp4 = ats2plpre_gt_int1_int1($arg0, 0);
  if($tmp4) {
    $tmp5 = ats2plpre_sub_int1_int1($arg0, 1);
    $tmp6 = [$env0, $arg1];
    #ATStailcalseq_beg
    $apy0 = $tmp5;
    $apy1 = $tmp6;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab__ats2plpre_list_loop_3;
    #ATStailcalseq_end
  } else {
    $tmpret3 = $arg1;
  } #endif
  return $tmpret3;
} #end-of-function


sub
ats2plpre_list_make_intrange_2($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret8;
##
  __patsflab_list_make_intrange_2:
  $tmpret8 = ats2plpre_list_make_intrange_3($arg0, $arg1, 1);
  return $tmpret8;
} #end-of-function


sub
ats2plpre_list_make_intrange_3($$$)
{
##
  my($arg0, $arg1, $arg2) = @_;
##
  my $tmpret9;
  my $tmp20;
  my $tmp21;
  my $tmp22;
  my $tmp23;
  my $tmp24;
  my $tmp25;
  my $tmp26;
  my $tmp27;
  my $tmp28;
  my $tmp29;
  my $tmp30;
  my $tmp31;
  my $tmp32;
  my $tmp33;
  my $tmp34;
  my $tmp35;
  my $tmp36;
  my $tmp37;
  my $tmp38;
  my $tmp39;
  my $tmp40;
##
  __patsflab_list_make_intrange_3:
  #ATScaseofseq_beg
  while(1)
  {
    #ATSbranchseq_beg
    __atstmplab6:
    $tmp20 = ats2plpre_gt_int0_int0($arg2, 0);
    if(!ATSCKpat_bool($tmp20, 1)) { goto __atstmplab7; }
    $tmp21 = ats2plpre_lt_int0_int0($arg0, $arg1);
    if($tmp21) {
      $tmp25 = ats2plpre_sub_int0_int0($arg1, $arg0);
      $tmp24 = ats2plpre_add_int0_int0($tmp25, $arg2);
      $tmp23 = ats2plpre_sub_int0_int0($tmp24, 1);
      $tmp22 = ats2plpre_div_int0_int0($tmp23, $arg2);
      $tmp28 = ats2plpre_sub_int0_int0($tmp22, 1);
      $tmp27 = ats2plpre_mul_int0_int0($tmp28, $arg2);
      $tmp26 = ats2plpre_add_int0_int0($arg0, $tmp27);
      $tmp29 = 0;
      $tmpret9 = _ats2plpre_list_loop1_6($tmp22, $tmp26, $arg2, $tmp29);
    } else {
      $tmpret9 = 0;
    } #endif
    last;
    #ATSbranchseq_end
    #ATSbranchseq_beg
    __atstmplab7:
    $tmp30 = ats2plpre_lt_int0_int0($arg2, 0);
    if(!ATSCKpat_bool($tmp30, 1)) { goto __atstmplab8; }
    $tmp31 = ats2plpre_gt_int0_int0($arg0, $arg1);
    if($tmp31) {
      $tmp32 = ats2plpre_neg_int0($arg2);
      $tmp36 = ats2plpre_sub_int0_int0($arg0, $arg1);
      $tmp35 = ats2plpre_add_int0_int0($tmp36, $tmp32);
      $tmp34 = ats2plpre_sub_int0_int0($tmp35, 1);
      $tmp33 = ats2plpre_div_int0_int0($tmp34, $tmp32);
      $tmp39 = ats2plpre_sub_int0_int0($tmp33, 1);
      $tmp38 = ats2plpre_mul_int0_int0($tmp39, $tmp32);
      $tmp37 = ats2plpre_sub_int0_int0($arg0, $tmp38);
      $tmp40 = 0;
      $tmpret9 = _ats2plpre_list_loop2_7($tmp33, $tmp37, $tmp32, $tmp40);
    } else {
      $tmpret9 = 0;
    } #endif
    last;
    #ATSbranchseq_end
    #ATSbranchseq_beg
    __atstmplab8:
    $tmpret9 = 0;
    last;
    #ATSbranchseq_end
  } #end-of-while-loop;
  #ATScaseofseq_end
  return $tmpret9;
} #end-of-function


sub
_ats2plpre_list_loop1_6($$$$)
{
##
  my($arg0, $arg1, $arg2, $arg3) = @_;
##
  my $apy0;
  my $apy1;
  my $apy2;
  my $apy3;
  my $tmpret10;
  my $tmp11;
  my $tmp12;
  my $tmp13;
  my $tmp14;
##
  __patsflab__ats2plpre_list_loop1_6:
  $tmp11 = ats2plpre_gt_int0_int0($arg0, 0);
  if($tmp11) {
    $tmp12 = ats2plpre_sub_int0_int0($arg0, 1);
    $tmp13 = ats2plpre_sub_int0_int0($arg1, $arg2);
    $tmp14 = [$arg1, $arg3];
    #ATStailcalseq_beg
    $apy0 = $tmp12;
    $apy1 = $tmp13;
    $apy2 = $arg2;
    $apy3 = $tmp14;
    $arg0 = $apy0;
    $arg1 = $apy1;
    $arg2 = $apy2;
    $arg3 = $apy3;
    goto __patsflab__ats2plpre_list_loop1_6;
    #ATStailcalseq_end
  } else {
    $tmpret10 = $arg3;
  } #endif
  return $tmpret10;
} #end-of-function


sub
_ats2plpre_list_loop2_7($$$$)
{
##
  my($arg0, $arg1, $arg2, $arg3) = @_;
##
  my $apy0;
  my $apy1;
  my $apy2;
  my $apy3;
  my $tmpret15;
  my $tmp16;
  my $tmp17;
  my $tmp18;
  my $tmp19;
##
  __patsflab__ats2plpre_list_loop2_7:
  $tmp16 = ats2plpre_gt_int0_int0($arg0, 0);
  if($tmp16) {
    $tmp17 = ats2plpre_sub_int0_int0($arg0, 1);
    $tmp18 = ats2plpre_add_int0_int0($arg1, $arg2);
    $tmp19 = [$arg1, $arg3];
    #ATStailcalseq_beg
    $apy0 = $tmp17;
    $apy1 = $tmp18;
    $apy2 = $arg2;
    $apy3 = $tmp19;
    $arg0 = $apy0;
    $arg1 = $apy1;
    $arg2 = $apy2;
    $arg3 = $apy3;
    goto __patsflab__ats2plpre_list_loop2_7;
    #ATStailcalseq_end
  } else {
    $tmpret15 = $arg3;
  } #endif
  return $tmpret15;
} #end-of-function


sub
ats2plpre_list_length($)
{
##
  my($arg0) = @_;
##
  my $tmpret52;
##
  __patsflab_list_length:
  $tmpret52 = _ats2plpre_list_loop_14($arg0, 0);
  return $tmpret52;
} #end-of-function


sub
_ats2plpre_list_loop_14($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $apy0;
  my $apy1;
  my $tmpret53;
  my $tmp55;
  my $tmp56;
##
  __patsflab__ats2plpre_list_loop_14:
  #ATScaseofseq_beg
  while(1)
  {
    #ATSbranchseq_beg
    __atstmplab13:
    if(ATSCKptriscons($arg0)) { goto __atstmplab16; }
    __atstmplab14:
    $tmpret53 = $arg1;
    last;
    #ATSbranchseq_end
    #ATSbranchseq_beg
    __atstmplab15:
    __atstmplab16:
    $tmp55 = $arg0->[1];
    $tmp56 = ats2plpre_add_int1_int1($arg1, 1);
    #ATStailcalseq_beg
    $apy0 = $tmp55;
    $apy1 = $tmp56;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab__ats2plpre_list_loop_14;
    #ATStailcalseq_end
    last;
    #ATSbranchseq_end
  } #end-of-while-loop;
  #ATScaseofseq_end
  return $tmpret53;
} #end-of-function


sub
ats2plpre_list_last($)
{
##
  my($arg0) = @_;
##
  my $apy0;
  my $tmpret57;
  my $tmp58;
  my $tmp59;
##
  __patsflab_list_last:
  $tmp58 = $arg0->[0];
  $tmp59 = $arg0->[1];
  #ATScaseofseq_beg
  while(1)
  {
    #ATSbranchseq_beg
    __atstmplab17:
    if(ATSCKptriscons($tmp59)) { goto __atstmplab20; }
    __atstmplab18:
    $tmpret57 = $tmp58;
    last;
    #ATSbranchseq_end
    #ATSbranchseq_beg
    __atstmplab19:
    __atstmplab20:
    #ATStailcalseq_beg
    $apy0 = $tmp59;
    $arg0 = $apy0;
    goto __patsflab_list_last;
    #ATStailcalseq_end
    last;
    #ATSbranchseq_end
  } #end-of-while-loop;
  #ATScaseofseq_end
  return $tmpret57;
} #end-of-function


sub
ats2plpre_list_get_at($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $apy0;
  my $apy1;
  my $tmpret60;
  my $tmp61;
  my $tmp62;
  my $tmp63;
  my $tmp64;
##
  __patsflab_list_get_at:
  $tmp61 = ats2plpre_eq_int1_int1($arg1, 0);
  if($tmp61) {
    $tmp62 = $arg0->[0];
    $tmpret60 = $tmp62;
  } else {
    $tmp63 = $arg0->[1];
    $tmp64 = ats2plpre_sub_int1_int1($arg1, 1);
    #ATStailcalseq_beg
    $apy0 = $tmp63;
    $apy1 = $tmp64;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab_list_get_at;
    #ATStailcalseq_end
  } #endif
  return $tmpret60;
} #end-of-function


sub
ats2plpre_list_snoc($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret65;
  my $tmp66;
  my $tmp67;
##
  __patsflab_list_snoc:
  $tmp67 = 0;
  $tmp66 = [$arg1, $tmp67];
  $tmpret65 = ats2plpre_list_append($arg0, $tmp66);
  return $tmpret65;
} #end-of-function


sub
ats2plpre_list_extend($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret68;
  my $tmp69;
  my $tmp70;
##
  __patsflab_list_extend:
  $tmp70 = 0;
  $tmp69 = [$arg1, $tmp70];
  $tmpret68 = ats2plpre_list_append($arg0, $tmp69);
  return $tmpret68;
} #end-of-function


sub
ats2plpre_list_append($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret71;
  my $tmp72;
  my $tmp73;
  my $tmp74;
##
  __patsflab_list_append:
  #ATScaseofseq_beg
  while(1)
  {
    #ATSbranchseq_beg
    __atstmplab21:
    if(ATSCKptriscons($arg0)) { goto __atstmplab24; }
    __atstmplab22:
    $tmpret71 = $arg1;
    last;
    #ATSbranchseq_end
    #ATSbranchseq_beg
    __atstmplab23:
    __atstmplab24:
    $tmp72 = $arg0->[0];
    $tmp73 = $arg0->[1];
    $tmp74 = ats2plpre_list_append($tmp73, $arg1);
    $tmpret71 = [$tmp72, $tmp74];
    last;
    #ATSbranchseq_end
  } #end-of-while-loop;
  #ATScaseofseq_end
  return $tmpret71;
} #end-of-function


sub
ats2plpre_mul_int_list($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret75;
  my $tmp80;
##
  __patsflab_mul_int_list:
  $tmp80 = 0;
  $tmpret75 = _ats2plpre_list_loop_21($arg1, $arg0, $tmp80);
  return $tmpret75;
} #end-of-function


sub
_ats2plpre_list_loop_21($$$)
{
##
  my($env0, $arg0, $arg1) = @_;
##
  my $apy0;
  my $apy1;
  my $tmpret76;
  my $tmp77;
  my $tmp78;
  my $tmp79;
##
  __patsflab__ats2plpre_list_loop_21:
  $tmp77 = ats2plpre_gt_int1_int1($arg0, 0);
  if($tmp77) {
    $tmp78 = ats2plpre_sub_int1_int1($arg0, 1);
    $tmp79 = ats2plpre_list_append($env0, $arg1);
    #ATStailcalseq_beg
    $apy0 = $tmp78;
    $apy1 = $tmp79;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab__ats2plpre_list_loop_21;
    #ATStailcalseq_end
  } else {
    $tmpret76 = $arg1;
  } #endif
  return $tmpret76;
} #end-of-function


sub
ats2plpre_list_reverse($)
{
##
  my($arg0) = @_;
##
  my $tmpret81;
  my $tmp82;
##
  __patsflab_list_reverse:
  $tmp82 = 0;
  $tmpret81 = ats2plpre_list_reverse_append($arg0, $tmp82);
  return $tmpret81;
} #end-of-function


sub
ats2plpre_list_reverse_append($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret83;
##
  __patsflab_list_reverse_append:
  $tmpret83 = _ats2plpre_list_loop_24($arg0, $arg1);
  return $tmpret83;
} #end-of-function


sub
_ats2plpre_list_loop_24($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $apy0;
  my $apy1;
  my $tmpret84;
  my $tmp85;
  my $tmp86;
  my $tmp87;
##
  __patsflab__ats2plpre_list_loop_24:
  #ATScaseofseq_beg
  while(1)
  {
    #ATSbranchseq_beg
    __atstmplab25:
    if(ATSCKptriscons($arg0)) { goto __atstmplab28; }
    __atstmplab26:
    $tmpret84 = $arg1;
    last;
    #ATSbranchseq_end
    #ATSbranchseq_beg
    __atstmplab27:
    __atstmplab28:
    $tmp85 = $arg0->[0];
    $tmp86 = $arg0->[1];
    $tmp87 = [$tmp85, $arg1];
    #ATStailcalseq_beg
    $apy0 = $tmp86;
    $apy1 = $tmp87;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab__ats2plpre_list_loop_24;
    #ATStailcalseq_end
    last;
    #ATSbranchseq_end
  } #end-of-while-loop;
  #ATScaseofseq_end
  return $tmpret84;
} #end-of-function


sub
ats2plpre_list_concat($)
{
##
  my($arg0) = @_;
##
  my $tmpret88;
##
  __patsflab_list_concat:
  $tmpret88 = _ats2plpre_list_auxlst_26($arg0);
  return $tmpret88;
} #end-of-function


sub
_ats2plpre_list_auxlst_26($)
{
##
  my($arg0) = @_;
##
  my $tmpret89;
  my $tmp90;
  my $tmp91;
  my $tmp92;
##
  __patsflab__ats2plpre_list_auxlst_26:
  #ATScaseofseq_beg
  while(1)
  {
    #ATSbranchseq_beg
    __atstmplab29:
    if(ATSCKptriscons($arg0)) { goto __atstmplab32; }
    __atstmplab30:
    $tmpret89 = 0;
    last;
    #ATSbranchseq_end
    #ATSbranchseq_beg
    __atstmplab31:
    __atstmplab32:
    $tmp90 = $arg0->[0];
    $tmp91 = $arg0->[1];
    $tmp92 = _ats2plpre_list_auxlst_26($tmp91);
    $tmpret89 = ats2plpre_list_append($tmp90, $tmp92);
    last;
    #ATSbranchseq_end
  } #end-of-while-loop;
  #ATScaseofseq_end
  return $tmpret89;
} #end-of-function


sub
ats2plpre_list_take($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret93;
  my $tmp94;
  my $tmp95;
  my $tmp96;
  my $tmp97;
  my $tmp98;
##
  __patsflab_list_take:
  $tmp94 = ats2plpre_gt_int1_int1($arg1, 0);
  if($tmp94) {
    $tmp95 = $arg0->[0];
    $tmp96 = $arg0->[1];
    $tmp98 = ats2plpre_sub_int1_int1($arg1, 1);
    $tmp97 = ats2plpre_list_take($tmp96, $tmp98);
    $tmpret93 = [$tmp95, $tmp97];
  } else {
    $tmpret93 = 0;
  } #endif
  return $tmpret93;
} #end-of-function


sub
ats2plpre_list_drop($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $apy0;
  my $apy1;
  my $tmpret99;
  my $tmp100;
  my $tmp101;
  my $tmp102;
##
  __patsflab_list_drop:
  $tmp100 = ats2plpre_gt_int1_int1($arg1, 0);
  if($tmp100) {
    $tmp101 = $arg0->[1];
    $tmp102 = ats2plpre_sub_int1_int1($arg1, 1);
    #ATStailcalseq_beg
    $apy0 = $tmp101;
    $apy1 = $tmp102;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab_list_drop;
    #ATStailcalseq_end
  } else {
    $tmpret99 = $arg0;
  } #endif
  return $tmpret99;
} #end-of-function


sub
ats2plpre_list_split_at($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret103;
  my $tmp104;
  my $tmp105;
##
  __patsflab_list_split_at:
  $tmp104 = ats2plpre_list_take($arg0, $arg1);
  $tmp105 = ats2plpre_list_drop($arg0, $arg1);
  $tmpret103 = [$tmp104, $tmp105];
  return $tmpret103;
} #end-of-function


sub
ats2plpre_list_insert_at($$$)
{
##
  my($arg0, $arg1, $arg2) = @_;
##
  my $tmpret106;
  my $tmp107;
  my $tmp108;
  my $tmp109;
  my $tmp110;
  my $tmp111;
##
  __patsflab_list_insert_at:
  $tmp107 = ats2plpre_gt_int1_int1($arg1, 0);
  if($tmp107) {
    $tmp108 = $arg0->[0];
    $tmp109 = $arg0->[1];
    $tmp111 = ats2plpre_sub_int1_int1($arg1, 1);
    $tmp110 = ats2plpre_list_insert_at($tmp109, $tmp111, $arg2);
    $tmpret106 = [$tmp108, $tmp110];
  } else {
    $tmpret106 = [$arg2, $arg0];
  } #endif
  return $tmpret106;
} #end-of-function


sub
ats2plpre_list_remove_at($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret112;
  my $tmp113;
  my $tmp114;
  my $tmp115;
  my $tmp116;
  my $tmp117;
##
  __patsflab_list_remove_at:
  $tmp113 = $arg0->[0];
  $tmp114 = $arg0->[1];
  $tmp115 = ats2plpre_gt_int1_int1($arg1, 0);
  if($tmp115) {
    $tmp117 = ats2plpre_sub_int1_int1($arg1, 1);
    $tmp116 = ats2plpre_list_remove_at($tmp114, $tmp117);
    $tmpret112 = [$tmp113, $tmp116];
  } else {
    $tmpret112 = $tmp114;
  } #endif
  return $tmpret112;
} #end-of-function


sub
ats2plpre_list_takeout_at($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret118;
  my $tmp119;
  my $tmp120;
  my $tmp121;
  my $tmp122;
  my $tmp123;
  my $tmp124;
  my $tmp125;
  my $tmp126;
##
  __patsflab_list_takeout_at:
  $tmp119 = $arg0->[0];
  $tmp120 = $arg0->[1];
  $tmp121 = ats2plpre_gt_int1_int1($arg1, 0);
  if($tmp121) {
    $tmp123 = ats2plpre_sub_int1_int1($arg1, 1);
    $tmp122 = ats2plpre_list_takeout_at($tmp120, $tmp123);
    $tmp124 = $tmp122->[0];
    $tmp125 = $tmp122->[1];
    $tmp126 = [$tmp119, $tmp125];
    $tmpret118 = [$tmp124, $tmp126];
  } else {
    $tmpret118 = [$tmp119, $tmp120];
  } #endif
  return $tmpret118;
} #end-of-function


sub
ats2plpre_list_exists($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $apy0;
  my $apy1;
  my $tmpret127;
  my $tmp128;
  my $tmp129;
  my $tmp130;
##
  __patsflab_list_exists:
  #ATScaseofseq_beg
  while(1)
  {
    #ATSbranchseq_beg
    __atstmplab33:
    if(ATSCKptriscons($arg0)) { goto __atstmplab36; }
    __atstmplab34:
    $tmpret127 = 0;
    last;
    #ATSbranchseq_end
    #ATSbranchseq_beg
    __atstmplab35:
    __atstmplab36:
    $tmp128 = $arg0->[0];
    $tmp129 = $arg0->[1];
    $tmp130 = &{$arg1->[0]}($arg1, $tmp128);
    if($tmp130) {
      $tmpret127 = 1;
    } else {
      #ATStailcalseq_beg
      $apy0 = $tmp129;
      $apy1 = $arg1;
      $arg0 = $apy0;
      $arg1 = $apy1;
      goto __patsflab_list_exists;
      #ATStailcalseq_end
    } #endif
    last;
    #ATSbranchseq_end
  } #end-of-while-loop;
  #ATScaseofseq_end
  return $tmpret127;
} #end-of-function


sub
ats2plpre_list_exists_method($)
{
##
  my($arg0) = @_;
##
  my $tmpret131;
##
  __patsflab_list_exists_method:
  $tmpret131 = _ats2plpre_list_patsfun_35__closurerize($arg0);
  return $tmpret131;
} #end-of-function


sub
_ats2plpre_list_patsfun_35($$)
{
##
  my($env0, $arg0) = @_;
##
  my $tmpret132;
##
  __patsflab__ats2plpre_list_patsfun_35:
  $tmpret132 = ats2plpre_list_exists($env0, $arg0);
  return $tmpret132;
} #end-of-function


sub
ats2plpre_list_iexists($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret133;
##
  __patsflab_list_iexists:
  $tmpret133 = _ats2plpre_list_loop_37($arg1, 0, $arg0);
  return $tmpret133;
} #end-of-function


sub
_ats2plpre_list_loop_37($$$)
{
##
  my($env0, $arg0, $arg1) = @_;
##
  my $apy0;
  my $apy1;
  my $tmpret134;
  my $tmp135;
  my $tmp136;
  my $tmp137;
  my $tmp138;
##
  __patsflab__ats2plpre_list_loop_37:
  #ATScaseofseq_beg
  while(1)
  {
    #ATSbranchseq_beg
    __atstmplab37:
    if(ATSCKptriscons($arg1)) { goto __atstmplab40; }
    __atstmplab38:
    $tmpret134 = 0;
    last;
    #ATSbranchseq_end
    #ATSbranchseq_beg
    __atstmplab39:
    __atstmplab40:
    $tmp135 = $arg1->[0];
    $tmp136 = $arg1->[1];
    $tmp137 = &{$env0->[0]}($env0, $arg0, $tmp135);
    if($tmp137) {
      $tmpret134 = 1;
    } else {
      $tmp138 = ats2plpre_add_int1_int1($arg0, 1);
      #ATStailcalseq_beg
      $apy0 = $tmp138;
      $apy1 = $tmp136;
      $arg0 = $apy0;
      $arg1 = $apy1;
      goto __patsflab__ats2plpre_list_loop_37;
      #ATStailcalseq_end
    } #endif
    last;
    #ATSbranchseq_end
  } #end-of-while-loop;
  #ATScaseofseq_end
  return $tmpret134;
} #end-of-function


sub
ats2plpre_list_iexists_method($)
{
##
  my($arg0) = @_;
##
  my $tmpret139;
##
  __patsflab_list_iexists_method:
  $tmpret139 = _ats2plpre_list_patsfun_39__closurerize($arg0);
  return $tmpret139;
} #end-of-function


sub
_ats2plpre_list_patsfun_39($$)
{
##
  my($env0, $arg0) = @_;
##
  my $tmpret140;
##
  __patsflab__ats2plpre_list_patsfun_39:
  $tmpret140 = ats2plpre_list_iexists($env0, $arg0);
  return $tmpret140;
} #end-of-function


sub
ats2plpre_list_forall($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $apy0;
  my $apy1;
  my $tmpret141;
  my $tmp142;
  my $tmp143;
  my $tmp144;
##
  __patsflab_list_forall:
  #ATScaseofseq_beg
  while(1)
  {
    #ATSbranchseq_beg
    __atstmplab41:
    if(ATSCKptriscons($arg0)) { goto __atstmplab44; }
    __atstmplab42:
    $tmpret141 = 1;
    last;
    #ATSbranchseq_end
    #ATSbranchseq_beg
    __atstmplab43:
    __atstmplab44:
    $tmp142 = $arg0->[0];
    $tmp143 = $arg0->[1];
    $tmp144 = &{$arg1->[0]}($arg1, $tmp142);
    if($tmp144) {
      #ATStailcalseq_beg
      $apy0 = $tmp143;
      $apy1 = $arg1;
      $arg0 = $apy0;
      $arg1 = $apy1;
      goto __patsflab_list_forall;
      #ATStailcalseq_end
    } else {
      $tmpret141 = 0;
    } #endif
    last;
    #ATSbranchseq_end
  } #end-of-while-loop;
  #ATScaseofseq_end
  return $tmpret141;
} #end-of-function


sub
ats2plpre_list_forall_method($)
{
##
  my($arg0) = @_;
##
  my $tmpret145;
##
  __patsflab_list_forall_method:
  $tmpret145 = _ats2plpre_list_patsfun_42__closurerize($arg0);
  return $tmpret145;
} #end-of-function


sub
_ats2plpre_list_patsfun_42($$)
{
##
  my($env0, $arg0) = @_;
##
  my $tmpret146;
##
  __patsflab__ats2plpre_list_patsfun_42:
  $tmpret146 = ats2plpre_list_forall($env0, $arg0);
  return $tmpret146;
} #end-of-function


sub
ats2plpre_list_iforall($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret147;
##
  __patsflab_list_iforall:
  $tmpret147 = _ats2plpre_list_loop_44($arg1, 0, $arg0);
  return $tmpret147;
} #end-of-function


sub
_ats2plpre_list_loop_44($$$)
{
##
  my($env0, $arg0, $arg1) = @_;
##
  my $apy0;
  my $apy1;
  my $tmpret148;
  my $tmp149;
  my $tmp150;
  my $tmp151;
  my $tmp152;
##
  __patsflab__ats2plpre_list_loop_44:
  #ATScaseofseq_beg
  while(1)
  {
    #ATSbranchseq_beg
    __atstmplab45:
    if(ATSCKptriscons($arg1)) { goto __atstmplab48; }
    __atstmplab46:
    $tmpret148 = 1;
    last;
    #ATSbranchseq_end
    #ATSbranchseq_beg
    __atstmplab47:
    __atstmplab48:
    $tmp149 = $arg1->[0];
    $tmp150 = $arg1->[1];
    $tmp151 = &{$env0->[0]}($env0, $arg0, $tmp149);
    if($tmp151) {
      $tmp152 = ats2plpre_add_int1_int1($arg0, 1);
      #ATStailcalseq_beg
      $apy0 = $tmp152;
      $apy1 = $tmp150;
      $arg0 = $apy0;
      $arg1 = $apy1;
      goto __patsflab__ats2plpre_list_loop_44;
      #ATStailcalseq_end
    } else {
      $tmpret148 = 0;
    } #endif
    last;
    #ATSbranchseq_end
  } #end-of-while-loop;
  #ATScaseofseq_end
  return $tmpret148;
} #end-of-function


sub
ats2plpre_list_iforall_method($)
{
##
  my($arg0) = @_;
##
  my $tmpret153;
##
  __patsflab_list_iforall_method:
  $tmpret153 = _ats2plpre_list_patsfun_46__closurerize($arg0);
  return $tmpret153;
} #end-of-function


sub
_ats2plpre_list_patsfun_46($$)
{
##
  my($env0, $arg0) = @_;
##
  my $tmpret154;
##
  __patsflab__ats2plpre_list_patsfun_46:
  $tmpret154 = ats2plpre_list_iforall($env0, $arg0);
  return $tmpret154;
} #end-of-function


sub
ats2plpre_list_app($$)
{
##
  my($arg0, $arg1) = @_;
##
##
  __patsflab_list_app:
  ats2plpre_list_foreach($arg0, $arg1);
  return;#_void
} #end-of-function


sub
ats2plpre_list_foreach($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $apy0;
  my $apy1;
  my $tmp157;
  my $tmp158;
##
  __patsflab_list_foreach:
  #ATScaseofseq_beg
  while(1)
  {
    #ATSbranchseq_beg
    __atstmplab49:
    if(ATSCKptriscons($arg0)) { goto __atstmplab52; }
    __atstmplab50:
    #ATSINSmove_void;
    last;
    #ATSbranchseq_end
    #ATSbranchseq_beg
    __atstmplab51:
    __atstmplab52:
    $tmp157 = $arg0->[0];
    $tmp158 = $arg0->[1];
    &{$arg1->[0]}($arg1, $tmp157);
    #ATStailcalseq_beg
    $apy0 = $tmp158;
    $apy1 = $arg1;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab_list_foreach;
    #ATStailcalseq_end
    last;
    #ATSbranchseq_end
  } #end-of-while-loop;
  #ATScaseofseq_end
  return;#_void
} #end-of-function


sub
ats2plpre_list_foreach_method($)
{
##
  my($arg0) = @_;
##
  my $tmpret160;
##
  __patsflab_list_foreach_method:
  $tmpret160 = _ats2plpre_list_patsfun_50__closurerize($arg0);
  return $tmpret160;
} #end-of-function


sub
_ats2plpre_list_patsfun_50($$)
{
##
  my($env0, $arg0) = @_;
##
##
  __patsflab__ats2plpre_list_patsfun_50:
  ats2plpre_list_foreach($env0, $arg0);
  return;#_void
} #end-of-function


sub
ats2plpre_list_iforeach($$)
{
##
  my($arg0, $arg1) = @_;
##
##
  __patsflab_list_iforeach:
  _ats2plpre_list_aux_52($arg1, 0, $arg0);
  return;#_void
} #end-of-function


sub
_ats2plpre_list_aux_52($$$)
{
##
  my($env0, $arg0, $arg1) = @_;
##
  my $apy0;
  my $apy1;
  my $tmp164;
  my $tmp165;
  my $tmp167;
##
  __patsflab__ats2plpre_list_aux_52:
  #ATScaseofseq_beg
  while(1)
  {
    #ATSbranchseq_beg
    __atstmplab53:
    if(ATSCKptriscons($arg1)) { goto __atstmplab56; }
    __atstmplab54:
    #ATSINSmove_void;
    last;
    #ATSbranchseq_end
    #ATSbranchseq_beg
    __atstmplab55:
    __atstmplab56:
    $tmp164 = $arg1->[0];
    $tmp165 = $arg1->[1];
    &{$env0->[0]}($env0, $arg0, $tmp164);
    $tmp167 = ats2plpre_add_int1_int1($arg0, 1);
    #ATStailcalseq_beg
    $apy0 = $tmp167;
    $apy1 = $tmp165;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab__ats2plpre_list_aux_52;
    #ATStailcalseq_end
    last;
    #ATSbranchseq_end
  } #end-of-while-loop;
  #ATScaseofseq_end
  return;#_void
} #end-of-function


sub
ats2plpre_list_iforeach_method($)
{
##
  my($arg0) = @_;
##
  my $tmpret168;
##
  __patsflab_list_iforeach_method:
  $tmpret168 = _ats2plpre_list_patsfun_54__closurerize($arg0);
  return $tmpret168;
} #end-of-function


sub
_ats2plpre_list_patsfun_54($$)
{
##
  my($env0, $arg0) = @_;
##
##
  __patsflab__ats2plpre_list_patsfun_54:
  ats2plpre_list_iforeach($env0, $arg0);
  return;#_void
} #end-of-function


sub
ats2plpre_list_rforeach($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmp171;
  my $tmp172;
##
  __patsflab_list_rforeach:
  #ATScaseofseq_beg
  while(1)
  {
    #ATSbranchseq_beg
    __atstmplab57:
    if(ATSCKptriscons($arg0)) { goto __atstmplab60; }
    __atstmplab58:
    #ATSINSmove_void;
    last;
    #ATSbranchseq_end
    #ATSbranchseq_beg
    __atstmplab59:
    __atstmplab60:
    $tmp171 = $arg0->[0];
    $tmp172 = $arg0->[1];
    ats2plpre_list_rforeach($tmp172, $arg1);
    &{$arg1->[0]}($arg1, $tmp171);
    last;
    #ATSbranchseq_end
  } #end-of-while-loop;
  #ATScaseofseq_end
  return;#_void
} #end-of-function


sub
ats2plpre_list_rforeach_method($)
{
##
  my($arg0) = @_;
##
  my $tmpret174;
##
  __patsflab_list_rforeach_method:
  $tmpret174 = _ats2plpre_list_patsfun_57__closurerize($arg0);
  return $tmpret174;
} #end-of-function


sub
_ats2plpre_list_patsfun_57($$)
{
##
  my($env0, $arg0) = @_;
##
##
  __patsflab__ats2plpre_list_patsfun_57:
  ats2plpre_list_rforeach($env0, $arg0);
  return;#_void
} #end-of-function


sub
ats2plpre_list_filter($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret176;
##
  __patsflab_list_filter:
  $tmpret176 = _ats2plpre_list_aux_59($arg1, $arg0);
  return $tmpret176;
} #end-of-function


sub
_ats2plpre_list_aux_59($$)
{
##
  my($env0, $arg0) = @_;
##
  my $apy0;
  my $tmpret177;
  my $tmp178;
  my $tmp179;
  my $tmp180;
  my $tmp181;
##
  __patsflab__ats2plpre_list_aux_59:
  #ATScaseofseq_beg
  while(1)
  {
    #ATSbranchseq_beg
    __atstmplab61:
    if(ATSCKptriscons($arg0)) { goto __atstmplab64; }
    __atstmplab62:
    $tmpret177 = 0;
    last;
    #ATSbranchseq_end
    #ATSbranchseq_beg
    __atstmplab63:
    __atstmplab64:
    $tmp178 = $arg0->[0];
    $tmp179 = $arg0->[1];
    $tmp180 = &{$env0->[0]}($env0, $tmp178);
    if($tmp180) {
      $tmp181 = _ats2plpre_list_aux_59($env0, $tmp179);
      $tmpret177 = [$tmp178, $tmp181];
    } else {
      #ATStailcalseq_beg
      $apy0 = $tmp179;
      $arg0 = $apy0;
      goto __patsflab__ats2plpre_list_aux_59;
      #ATStailcalseq_end
    } #endif
    last;
    #ATSbranchseq_end
  } #end-of-while-loop;
  #ATScaseofseq_end
  return $tmpret177;
} #end-of-function


sub
ats2plpre_list_filter_method($)
{
##
  my($arg0) = @_;
##
  my $tmpret182;
##
  __patsflab_list_filter_method:
  $tmpret182 = _ats2plpre_list_patsfun_61__closurerize($arg0);
  return $tmpret182;
} #end-of-function


sub
_ats2plpre_list_patsfun_61($$)
{
##
  my($env0, $arg0) = @_;
##
  my $tmpret183;
##
  __patsflab__ats2plpre_list_patsfun_61:
  $tmpret183 = ats2plpre_list_filter($env0, $arg0);
  return $tmpret183;
} #end-of-function


sub
ats2plpre_list_map($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret184;
##
  __patsflab_list_map:
  $tmpret184 = _ats2plpre_list_aux_63($arg1, $arg0);
  return $tmpret184;
} #end-of-function


sub
_ats2plpre_list_aux_63($$)
{
##
  my($env0, $arg0) = @_;
##
  my $tmpret185;
  my $tmp186;
  my $tmp187;
  my $tmp188;
  my $tmp189;
##
  __patsflab__ats2plpre_list_aux_63:
  #ATScaseofseq_beg
  while(1)
  {
    #ATSbranchseq_beg
    __atstmplab65:
    if(ATSCKptriscons($arg0)) { goto __atstmplab68; }
    __atstmplab66:
    $tmpret185 = 0;
    last;
    #ATSbranchseq_end
    #ATSbranchseq_beg
    __atstmplab67:
    __atstmplab68:
    $tmp186 = $arg0->[0];
    $tmp187 = $arg0->[1];
    $tmp188 = &{$env0->[0]}($env0, $tmp186);
    $tmp189 = _ats2plpre_list_aux_63($env0, $tmp187);
    $tmpret185 = [$tmp188, $tmp189];
    last;
    #ATSbranchseq_end
  } #end-of-while-loop;
  #ATScaseofseq_end
  return $tmpret185;
} #end-of-function


sub
ats2plpre_list_map_method($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret190;
##
  __patsflab_list_map_method:
  $tmpret190 = _ats2plpre_list_patsfun_65__closurerize($arg0);
  return $tmpret190;
} #end-of-function


sub
_ats2plpre_list_patsfun_65($$)
{
##
  my($env0, $arg0) = @_;
##
  my $tmpret191;
##
  __patsflab__ats2plpre_list_patsfun_65:
  $tmpret191 = ats2plpre_list_map($env0, $arg0);
  return $tmpret191;
} #end-of-function


sub
ats2plpre_list_foldleft($$$)
{
##
  my($arg0, $arg1, $arg2) = @_;
##
  my $tmpret192;
##
  __patsflab_list_foldleft:
  $tmpret192 = _ats2plpre_list_loop_67($arg2, $arg1, $arg0);
  return $tmpret192;
} #end-of-function


sub
_ats2plpre_list_loop_67($$$)
{
##
  my($env0, $arg0, $arg1) = @_;
##
  my $apy0;
  my $apy1;
  my $tmpret193;
  my $tmp194;
  my $tmp195;
  my $tmp196;
##
  __patsflab__ats2plpre_list_loop_67:
  #ATScaseofseq_beg
  while(1)
  {
    #ATSbranchseq_beg
    __atstmplab69:
    if(ATSCKptriscons($arg1)) { goto __atstmplab72; }
    __atstmplab70:
    $tmpret193 = $arg0;
    last;
    #ATSbranchseq_end
    #ATSbranchseq_beg
    __atstmplab71:
    __atstmplab72:
    $tmp194 = $arg1->[0];
    $tmp195 = $arg1->[1];
    $tmp196 = &{$env0->[0]}($env0, $arg0, $tmp194);
    #ATStailcalseq_beg
    $apy0 = $tmp196;
    $apy1 = $tmp195;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab__ats2plpre_list_loop_67;
    #ATStailcalseq_end
    last;
    #ATSbranchseq_end
  } #end-of-while-loop;
  #ATScaseofseq_end
  return $tmpret193;
} #end-of-function


sub
ats2plpre_list_foldleft_method($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret197;
##
  __patsflab_list_foldleft_method:
  $tmpret197 = _ats2plpre_list_patsfun_69__closurerize($arg0, $arg1);
  return $tmpret197;
} #end-of-function


sub
_ats2plpre_list_patsfun_69($$$)
{
##
  my($env0, $env1, $arg0) = @_;
##
  my $tmpret198;
##
  __patsflab__ats2plpre_list_patsfun_69:
  $tmpret198 = ats2plpre_list_foldleft($env0, $env1, $arg0);
  return $tmpret198;
} #end-of-function


sub
ats2plpre_list_ifoldleft($$$)
{
##
  my($arg0, $arg1, $arg2) = @_;
##
  my $tmpret199;
##
  __patsflab_list_ifoldleft:
  $tmpret199 = _ats2plpre_list_loop_71($arg2, 0, $arg1, $arg0);
  return $tmpret199;
} #end-of-function


sub
_ats2plpre_list_loop_71($$$$)
{
##
  my($env0, $arg0, $arg1, $arg2) = @_;
##
  my $apy0;
  my $apy1;
  my $apy2;
  my $tmpret200;
  my $tmp201;
  my $tmp202;
  my $tmp203;
  my $tmp204;
##
  __patsflab__ats2plpre_list_loop_71:
  #ATScaseofseq_beg
  while(1)
  {
    #ATSbranchseq_beg
    __atstmplab73:
    if(ATSCKptriscons($arg2)) { goto __atstmplab76; }
    __atstmplab74:
    $tmpret200 = $arg1;
    last;
    #ATSbranchseq_end
    #ATSbranchseq_beg
    __atstmplab75:
    __atstmplab76:
    $tmp201 = $arg2->[0];
    $tmp202 = $arg2->[1];
    $tmp203 = ats2plpre_add_int1_int1($arg0, 1);
    $tmp204 = &{$env0->[0]}($env0, $arg0, $arg1, $tmp201);
    #ATStailcalseq_beg
    $apy0 = $tmp203;
    $apy1 = $tmp204;
    $apy2 = $tmp202;
    $arg0 = $apy0;
    $arg1 = $apy1;
    $arg2 = $apy2;
    goto __patsflab__ats2plpre_list_loop_71;
    #ATStailcalseq_end
    last;
    #ATSbranchseq_end
  } #end-of-while-loop;
  #ATScaseofseq_end
  return $tmpret200;
} #end-of-function


sub
ats2plpre_list_ifoldleft_method($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret205;
##
  __patsflab_list_ifoldleft_method:
  $tmpret205 = _ats2plpre_list_patsfun_73__closurerize($arg0, $arg1);
  return $tmpret205;
} #end-of-function


sub
_ats2plpre_list_patsfun_73($$$)
{
##
  my($env0, $env1, $arg0) = @_;
##
  my $tmpret206;
##
  __patsflab__ats2plpre_list_patsfun_73:
  $tmpret206 = ats2plpre_list_ifoldleft($env0, $env1, $arg0);
  return $tmpret206;
} #end-of-function


sub
ats2plpre_list_foldright($$$)
{
##
  my($arg0, $arg1, $arg2) = @_;
##
  my $tmpret207;
##
  __patsflab_list_foldright:
  $tmpret207 = _ats2plpre_list_aux_75($arg1, $arg0, $arg2);
  return $tmpret207;
} #end-of-function


sub
_ats2plpre_list_aux_75($$$)
{
##
  my($env0, $arg0, $arg1) = @_;
##
  my $tmpret208;
  my $tmp209;
  my $tmp210;
  my $tmp211;
##
  __patsflab__ats2plpre_list_aux_75:
  #ATScaseofseq_beg
  while(1)
  {
    #ATSbranchseq_beg
    __atstmplab77:
    if(ATSCKptriscons($arg0)) { goto __atstmplab80; }
    __atstmplab78:
    $tmpret208 = $arg1;
    last;
    #ATSbranchseq_end
    #ATSbranchseq_beg
    __atstmplab79:
    __atstmplab80:
    $tmp209 = $arg0->[0];
    $tmp210 = $arg0->[1];
    $tmp211 = _ats2plpre_list_aux_75($env0, $tmp210, $arg1);
    $tmpret208 = &{$env0->[0]}($env0, $tmp209, $tmp211);
    last;
    #ATSbranchseq_end
  } #end-of-while-loop;
  #ATScaseofseq_end
  return $tmpret208;
} #end-of-function


sub
ats2plpre_list_foldright_method($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret212;
##
  __patsflab_list_foldright_method:
  $tmpret212 = _ats2plpre_list_patsfun_77__closurerize($arg0, $arg1);
  return $tmpret212;
} #end-of-function


sub
_ats2plpre_list_patsfun_77($$$)
{
##
  my($env0, $env1, $arg0) = @_;
##
  my $tmpret213;
##
  __patsflab__ats2plpre_list_patsfun_77:
  $tmpret213 = ats2plpre_list_foldright($env0, $arg0, $env1);
  return $tmpret213;
} #end-of-function


sub
ats2plpre_list_ifoldright($$$)
{
##
  my($arg0, $arg1, $arg2) = @_;
##
  my $tmpret214;
##
  __patsflab_list_ifoldright:
  $tmpret214 = _ats2plpre_list_aux_79($arg1, 0, $arg0, $arg2);
  return $tmpret214;
} #end-of-function


sub
_ats2plpre_list_aux_79($$$$)
{
##
  my($env0, $arg0, $arg1, $arg2) = @_;
##
  my $tmpret215;
  my $tmp216;
  my $tmp217;
  my $tmp218;
  my $tmp219;
##
  __patsflab__ats2plpre_list_aux_79:
  #ATScaseofseq_beg
  while(1)
  {
    #ATSbranchseq_beg
    __atstmplab81:
    if(ATSCKptriscons($arg1)) { goto __atstmplab84; }
    __atstmplab82:
    $tmpret215 = $arg2;
    last;
    #ATSbranchseq_end
    #ATSbranchseq_beg
    __atstmplab83:
    __atstmplab84:
    $tmp216 = $arg1->[0];
    $tmp217 = $arg1->[1];
    $tmp219 = ats2plpre_add_int1_int1($arg0, 1);
    $tmp218 = _ats2plpre_list_aux_79($env0, $tmp219, $tmp217, $arg2);
    $tmpret215 = &{$env0->[0]}($env0, $arg0, $tmp216, $tmp218);
    last;
    #ATSbranchseq_end
  } #end-of-while-loop;
  #ATScaseofseq_end
  return $tmpret215;
} #end-of-function


sub
ats2plpre_list_ifoldright_method($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret220;
##
  __patsflab_list_ifoldright_method:
  $tmpret220 = _ats2plpre_list_patsfun_81__closurerize($arg0, $arg1);
  return $tmpret220;
} #end-of-function


sub
_ats2plpre_list_patsfun_81($$$)
{
##
  my($env0, $env1, $arg0) = @_;
##
  my $tmpret221;
##
  __patsflab__ats2plpre_list_patsfun_81:
  $tmpret221 = ats2plpre_list_ifoldright($env0, $arg0, $env1);
  return $tmpret221;
} #end-of-function


sub
ats2plpre_streamize_list_elt($)
{
##
  my($arg0) = @_;
##
  my $tmpret224;
##
  __patsflab_streamize_list_elt:
  $tmpret224 = _ats2plpre_list_auxmain_85($arg0);
  return $tmpret224;
} #end-of-function


sub
_ats2plpre_list_auxmain_85($)
{
##
  my($arg0) = @_;
##
  my $tmpret225;
##
  __patsflab__ats2plpre_list_auxmain_85:
  $tmpret225 = ATSPMVllazyval(_ats2plpre_list_patsfun_86__closurerize($arg0));
  return $tmpret225;
} #end-of-function


sub
_ats2plpre_list_patsfun_86($$)
{
##
  my($env0, $arg0) = @_;
##
  my $tmpret226;
  my $tmp227;
  my $tmp228;
  my $tmp229;
##
  __patsflab__ats2plpre_list_patsfun_86:
  if($arg0) {
    #ATScaseofseq_beg
    while(1)
    {
      #ATSbranchseq_beg
      __atstmplab85:
      if(ATSCKptriscons($env0)) { goto __atstmplab88; }
      __atstmplab86:
      $tmpret226 = 0;
      last;
      #ATSbranchseq_end
      #ATSbranchseq_beg
      __atstmplab87:
      __atstmplab88:
      $tmp227 = $env0->[0];
      $tmp228 = $env0->[1];
      $tmp229 = _ats2plpre_list_auxmain_85($tmp228);
      $tmpret226 = [$tmp227, $tmp229];
      last;
      #ATSbranchseq_end
    } #end-of-while-loop;
    #ATScaseofseq_end
  } else {
  } #endif
  return $tmpret226;
} #end-of-function


sub
ats2plpre_streamize_list_zip($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret230;
##
  __patsflab_streamize_list_zip:
  $tmpret230 = _ats2plpre_list_auxmain_88($arg0, $arg1);
  return $tmpret230;
} #end-of-function


sub
_ats2plpre_list_auxmain_88($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret231;
##
  __patsflab__ats2plpre_list_auxmain_88:
  $tmpret231 = ATSPMVllazyval(_ats2plpre_list_patsfun_89__closurerize($arg0, $arg1));
  return $tmpret231;
} #end-of-function


sub
_ats2plpre_list_patsfun_89($$$)
{
##
  my($env0, $env1, $arg0) = @_;
##
  my $tmpret232;
  my $tmp233;
  my $tmp234;
  my $tmp235;
  my $tmp236;
  my $tmp237;
  my $tmp238;
##
  __patsflab__ats2plpre_list_patsfun_89:
  if($arg0) {
    #ATScaseofseq_beg
    while(1)
    {
      #ATSbranchseq_beg
      __atstmplab89:
      if(ATSCKptriscons($env0)) { goto __atstmplab92; }
      __atstmplab90:
      $tmpret232 = 0;
      last;
      #ATSbranchseq_end
      #ATSbranchseq_beg
      __atstmplab91:
      __atstmplab92:
      $tmp233 = $env0->[0];
      $tmp234 = $env0->[1];
      #ATScaseofseq_beg
      while(1)
      {
        #ATSbranchseq_beg
        __atstmplab93:
        if(ATSCKptriscons($env1)) { goto __atstmplab96; }
        __atstmplab94:
        $tmpret232 = 0;
        last;
        #ATSbranchseq_end
        #ATSbranchseq_beg
        __atstmplab95:
        __atstmplab96:
        $tmp235 = $env1->[0];
        $tmp236 = $env1->[1];
        $tmp237 = [$tmp233, $tmp235];
        $tmp238 = _ats2plpre_list_auxmain_88($tmp234, $tmp236);
        $tmpret232 = [$tmp237, $tmp238];
        last;
        #ATSbranchseq_end
      } #end-of-while-loop;
      #ATScaseofseq_end
      last;
      #ATSbranchseq_end
    } #end-of-while-loop;
    #ATScaseofseq_end
  } else {
  } #endif
  return $tmpret232;
} #end-of-function


sub
ats2plpre_streamize_list_cross($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret239;
##
  __patsflab_streamize_list_cross:
  $tmpret239 = _ats2plpre_list_auxmain_93($arg0, $arg1);
  return $tmpret239;
} #end-of-function


sub
_ats2plpre_list_auxone_91($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret240;
##
  __patsflab__ats2plpre_list_auxone_91:
  $tmpret240 = ATSPMVllazyval(_ats2plpre_list_patsfun_92__closurerize($arg0, $arg1));
  return $tmpret240;
} #end-of-function


sub
_ats2plpre_list_patsfun_92($$$)
{
##
  my($env0, $env1, $arg0) = @_;
##
  my $tmpret241;
  my $tmp242;
  my $tmp243;
  my $tmp244;
  my $tmp245;
##
  __patsflab__ats2plpre_list_patsfun_92:
  if($arg0) {
    #ATScaseofseq_beg
    while(1)
    {
      #ATSbranchseq_beg
      __atstmplab97:
      if(ATSCKptriscons($env1)) { goto __atstmplab100; }
      __atstmplab98:
      $tmpret241 = 0;
      last;
      #ATSbranchseq_end
      #ATSbranchseq_beg
      __atstmplab99:
      __atstmplab100:
      $tmp242 = $env1->[0];
      $tmp243 = $env1->[1];
      $tmp244 = [$env0, $tmp242];
      $tmp245 = _ats2plpre_list_auxone_91($env0, $tmp243);
      $tmpret241 = [$tmp244, $tmp245];
      last;
      #ATSbranchseq_end
    } #end-of-while-loop;
    #ATScaseofseq_end
  } else {
  } #endif
  return $tmpret241;
} #end-of-function


sub
_ats2plpre_list_auxmain_93($$)
{
##
  my($arg0, $arg1) = @_;
##
  my $tmpret246;
##
  __patsflab__ats2plpre_list_auxmain_93:
  $tmpret246 = ATSPMVllazyval(_ats2plpre_list_patsfun_94__closurerize($arg0, $arg1));
  return $tmpret246;
} #end-of-function


sub
_ats2plpre_list_patsfun_94($$$)
{
##
  my($env0, $env1, $arg0) = @_;
##
  my $tmpret247;
  my $tmp248;
  my $tmp249;
  my $tmp250;
  my $tmp251;
  my $tmp252;
##
  __patsflab__ats2plpre_list_patsfun_94:
  if($arg0) {
    #ATScaseofseq_beg
    while(1)
    {
      #ATSbranchseq_beg
      __atstmplab101:
      if(ATSCKptriscons($env0)) { goto __atstmplab104; }
      __atstmplab102:
      $tmpret247 = 0;
      last;
      #ATSbranchseq_end
      #ATSbranchseq_beg
      __atstmplab103:
      __atstmplab104:
      $tmp248 = $env0->[0];
      $tmp249 = $env0->[1];
      $tmp251 = _ats2plpre_list_auxone_91($tmp248, $env1);
      $tmp252 = _ats2plpre_list_auxmain_93($tmp249, $env1);
      $tmp250 = ats2plpre_stream_vt_append($tmp251, $tmp252);
      $tmpret247 = ATSPMVllazyval_eval($tmp250);
      last;
      #ATSbranchseq_end
    } #end-of-while-loop;
    #ATScaseofseq_end
  } else {
  } #endif
  return $tmpret247;
} #end-of-function


######
#ATSextcode_beg()
######
######
1; ##note that it is needed by 'use' or 'require'
######
######
#ATSextcode_end()
######
######
##
## end-of-compilation-unit
##
######
