/*
**
** The JavaScript code is generated by atscc2js
** The starting compilation time is: 2017-10-16: 17h:11m
**
*/

/* ATSextcode_beg() */
//
function
document_getElementById
  (id)
{
  return document.getElementById(id);
}
//
function
xmldoc_set_innerHTML
  (xmldoc, text)
  { xmldoc.innerHTML = text; return; }
//
/* ATSextcode_end() */

/* ATSextcode_beg() */
function
board_size_get()
{
  return parseInt(document.getElementById("param_board_size").value);
}
function
delay_time_get()
{
  return parseInt(document.getElementById("param_delay_time").value);
}
/* ATSextcode_end() */

/* ATSextcode_beg() */
//
function
button_enable(button)
{
  button.disabled=false; return;
}
function
button_disable(button)
{
  button.disabled = true; return;
}
/* ATSextcode_end() */

var QueenPuzzle__statmp328

var QueenPuzzle__statmp329

var QueenPuzzle__statmp398

var QueenPuzzle__statmp399

var QueenPuzzle__statmp400

var QueenPuzzle__statmp401

var QueenPuzzle__statmp410

var QueenPuzzle__statmp411

var QueenPuzzle__statmp412

var QueenPuzzle__statmp413

function
QueenPuzzle__patsfun_83__closurerize(env0)
{
  return [function(cenv) { return QueenPuzzle__patsfun_83(cenv[1]); }, env0];
}


function
QueenPuzzle__patsfun_100__closurerize(env0)
{
  return [function(cenv, arg0) { return QueenPuzzle__patsfun_100(cenv[1], arg0); }, env0];
}


function
QueenPuzzle__patsfun_118__closurerize(env0)
{
  return [function(cenv) { return QueenPuzzle__patsfun_118(cenv[1]); }, env0];
}


function
QueenPuzzle__patsfun_116__116__1__closurerize(env0)
{
  return [function(cenv) { return QueenPuzzle__patsfun_116__116__1(cenv[1]); }, env0];
}


function
QueenPuzzle__patsfun_90__90__1__closurerize(env0, env1)
{
  return [function(cenv) { return QueenPuzzle__patsfun_90__90__1(cenv[1], cenv[2]); }, env0, env1];
}


function
QueenPuzzle__patsfun_125__closurerize()
{
  return [function(cenv, arg0) { return QueenPuzzle__patsfun_125(arg0); }];
}


function
QueenPuzzle__patsfun_23__23__1__closurerize()
{
  return [function(cenv, arg0, arg1) { return QueenPuzzle__patsfun_23__23__1(arg0, arg1); }];
}


function
QueenPuzzle__patsfun_135__closurerize(env0)
{
  return [function(cenv, arg0, arg1) { return QueenPuzzle__patsfun_135(cenv[1], arg0, arg1); }, env0];
}


function
QueenPuzzle__patsfun_139__closurerize(env0)
{
  return [function(cenv, arg0) { return QueenPuzzle__patsfun_139(cenv[1], arg0); }, env0];
}


function
QueenPuzzle__patsfun_3__3__1__closurerize(env0)
{
  return [function(cenv, arg0) { return QueenPuzzle__patsfun_3__3__1(cenv[1], arg0); }, env0];
}


function
QueenPuzzle__patsfun_147__closurerize()
{
  return [function(cenv, arg0) { return QueenPuzzle__patsfun_147(arg0); }];
}


function
QueenPuzzle__patsfun_3__3__2__closurerize(env0)
{
  return [function(cenv, arg0) { return QueenPuzzle__patsfun_3__3__2(cenv[1], arg0); }, env0];
}


function
QueenPuzzle__patsfun_153__closurerize()
{
  return [function(cenv, arg0) { return QueenPuzzle__patsfun_153(arg0); }];
}


function
QueenPuzzle__patsfun_155__closurerize(env0)
{
  return [function(cenv, arg0) { return QueenPuzzle__patsfun_155(cenv[1], arg0); }, env0];
}


function
QueenPuzzle__patsfun_3__3__3__closurerize(env0)
{
  return [function(cenv, arg0) { return QueenPuzzle__patsfun_3__3__3(cenv[1], arg0); }, env0];
}


function
QueenPuzzle__patsfun_160__closurerize(env0)
{
  return [function(cenv, arg0) { return QueenPuzzle__patsfun_160(cenv[1], arg0); }, env0];
}


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__int_stream_from(arg0)
{
//
// knd = 0
  var tmpret228
  var tmplab, tmplab_js
//
  // __patsflab_int_stream_from
  tmpret228 = ATSPMVlazyval(QueenPuzzle__patsfun_83__closurerize(arg0));
  return tmpret228;
} // end-of-function


function
QueenPuzzle__patsfun_83(env0)
{
//
// knd = 0
  var tmpret229
  var tmp230
  var tmp231
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__patsfun_83
  tmp231 = ats2jspre_add_int0_int0(env0, 1);
  tmp230 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__int_stream_from(tmp231);
  tmpret229 = [env0, tmp230];
  return tmpret229;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__int_stream_vt_from(arg0)
{
//
// knd = 0
  var tmpret289
  var tmplab, tmplab_js
//
  // __patsflab_int_stream_vt_from
  tmpret289 = ATSPMVllazyval(QueenPuzzle__patsfun_100__closurerize(arg0));
  return tmpret289;
} // end-of-function


function
QueenPuzzle__patsfun_100(env0, arg0)
{
//
// knd = 0
  var tmpret290
  var tmp291
  var tmp292
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__patsfun_100
  if(arg0) {
    tmp292 = ats2jspre_add_int0_int0(env0, 1);
    tmp291 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__int_stream_vt_from(tmp292);
    tmpret290 = [env0, tmp291];
  } else {
  } // end-of-if
  return tmpret290;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__N_get()
{
//
// knd = 0
  var tmpret330
  var tmplab, tmplab_js
//
  // __patsflab_N_get
  tmpret330 = ats2jspre_ref_get_elt(QueenPuzzle__statmp328);
  return tmpret330;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__N_set(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_N_set
  ats2jspre_ref_set_elt(QueenPuzzle__statmp328, arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__theDelayTime_get()
{
//
// knd = 0
  var tmpret332
  var tmplab, tmplab_js
//
  // __patsflab_theDelayTime_get
  tmpret332 = ats2jspre_ref_get_elt(QueenPuzzle__statmp329);
  return tmpret332;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__theDelayTime_set(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_theDelayTime_set
  ats2jspre_ref_set_elt(QueenPuzzle__statmp329, arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__node_dfsenum(arg0)
{
//
// knd = 0
  var tmpret340
  var tmplab, tmplab_js
//
  // __patsflab_node_dfsenum
  tmpret340 = ATSPMVlazyval(QueenPuzzle__patsfun_118__closurerize(arg0));
  return tmpret340;
} // end-of-function


function
QueenPuzzle__patsfun_118(env0)
{
//
// knd = 0
  var tmpret341
  var tmp342
  var tmp355
  var tmp362
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__patsfun_118
  tmp362 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__node_get_children(env0);
  tmp355 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__list0_map__34__1(tmp362, QueenPuzzle__patsfun_125__closurerize());
  tmp342 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__list0_stream_concat__115__1(tmp355);
  tmpret341 = [env0, tmp342];
  return tmpret341;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__list0_stream_concat__115__1(arg0)
{
//
// knd = 0
  var tmpret334__1
  var tmplab, tmplab_js
//
  // __patsflab_list0_stream_concat
  tmpret334__1 = ATSPMVlazyval(QueenPuzzle__patsfun_116__116__1__closurerize(arg0));
  return tmpret334__1;
} // end-of-function


function
QueenPuzzle__patsfun_116__116__1(env0)
{
//
// knd = 0
  var tmpret335__1
  var tmp336__1
  var tmp337__1
  var tmp338__1
  var tmp339__1
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__patsfun_116
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab154
      if(ATSCKptriscons(env0)) {
        { tmplab_js = 4; break; }
      } // ifthen
      case 2: // __atstmplab155
      tmpret335__1 = null;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab156
      case 4: // __atstmplab157
      tmp336__1 = env0[0];
      tmp337__1 = env0[1];
      tmp339__1 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__list0_stream_concat__115__1(tmp337__1);
      tmp338__1 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__stream_append__89__1(tmp336__1, tmp339__1);
      tmpret335__1 = ATSPMVlazyval_eval(tmp338__1); 
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret335__1;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__stream_append__89__1(arg0, arg1)
{
//
// knd = 0
  var tmpret251__1
  var tmplab, tmplab_js
//
  // __patsflab_stream_append
  tmpret251__1 = ATSPMVlazyval(QueenPuzzle__patsfun_90__90__1__closurerize(arg0, arg1));
  return tmpret251__1;
} // end-of-function


function
QueenPuzzle__patsfun_90__90__1(env0, env1)
{
//
// knd = 0
  var tmpret252__1
  var tmp253__1
  var tmp254__1
  var tmp255__1
  var tmp256__1
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__patsfun_90
  tmp253__1 = ATSPMVlazyval_eval(env0); 
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab110
      if(ATSCKptriscons(tmp253__1)) {
        { tmplab_js = 4; break; }
      } // ifthen
      case 2: // __atstmplab111
      tmpret252__1 = ATSPMVlazyval_eval(env1); 
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab112
      case 4: // __atstmplab113
      tmp254__1 = tmp253__1[0];
      tmp255__1 = tmp253__1[1];
      tmp256__1 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__stream_append__89__1(tmp255__1, env1);
      tmpret252__1 = [tmp254__1, tmp256__1];
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret252__1;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__list0_map__34__1(arg0, arg1)
{
//
// knd = 0
  var tmpret68__1
  var tmplab, tmplab_js
//
  // __patsflab_list0_map
  tmpret68__1 = QueenPuzzle__auxlst_35__35__1(arg1, arg0);
  return tmpret68__1;
} // end-of-function


function
QueenPuzzle__auxlst_35__35__1(env0, arg0)
{
//
// knd = 0
  var tmpret69__1
  var tmp70__1
  var tmp71__1
  var tmp72__1
  var tmp73__1
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__auxlst_35
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab20
      if(ATSCKptriscons(arg0)) {
        { tmplab_js = 4; break; }
      } // ifthen
      case 2: // __atstmplab21
      tmpret69__1 = null;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab22
      case 4: // __atstmplab23
      tmp70__1 = arg0[0];
      tmp71__1 = arg0[1];
      tmp72__1 = env0[0](env0, tmp70__1);
      tmp73__1 = QueenPuzzle__auxlst_35__35__1(env0, tmp71__1);
      tmpret69__1 = [tmp72__1, tmp73__1];
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret69__1;
} // end-of-function


function
QueenPuzzle__patsfun_125(arg0)
{
//
// knd = 0
  var tmpret363
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__patsfun_125
  tmpret363 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__node_dfsenum(arg0);
  return tmpret363;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__node_init()
{
//
// knd = 0
  var tmpret364
  var tmplab, tmplab_js
//
  // __patsflab_node_init
  tmpret364 = null;
  return tmpret364;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__node_length(arg0)
{
//
// knd = 0
  var tmpret365
  var tmplab, tmplab_js
//
  // __patsflab_node_length
  tmpret365 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__list0_length__22__1(arg0);
  return tmpret365;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__list0_length__22__1(arg0)
{
//
// knd = 0
  var tmpret48__1
  var tmplab, tmplab_js
//
  // __patsflab_list0_length
  tmpret48__1 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__list0_foldleft__18__1(arg0, 0, QueenPuzzle__patsfun_23__23__1__closurerize());
  return tmpret48__1;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__list0_foldleft__18__1(arg0, arg1, arg2)
{
//
// knd = 0
  var tmpret38__1
  var tmplab, tmplab_js
//
  // __patsflab_list0_foldleft
  tmpret38__1 = QueenPuzzle__loop_19__19__1(arg2, arg0, arg1);
  return tmpret38__1;
} // end-of-function


function
QueenPuzzle__loop_19__19__1(env0, arg0, arg1)
{
//
// knd = 1
  var apy0
  var apy1
  var tmpret39__1
  var tmp40__1
  var tmp41__1
  var tmp42__1
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_QueenPuzzle__loop_19
    // ATScaseofseq_beg
    tmplab_js = 1;
    while(true) {
      tmplab = tmplab_js; tmplab_js = 0;
      switch(tmplab) {
        // ATSbranchseq_beg
        case 1: // __atstmplab8
        if(ATSCKptriscons(arg0)) {
          { tmplab_js = 4; break; }
        } // ifthen
        case 2: // __atstmplab9
        tmpret39__1 = arg1;
        break;
        // ATSbranchseq_end
        // ATSbranchseq_beg
        case 3: // __atstmplab10
        case 4: // __atstmplab11
        tmp40__1 = arg0[0];
        tmp41__1 = arg0[1];
        tmp42__1 = env0[0](env0, arg1, tmp40__1);
        // ATStailcalseq_beg
        apy0 = tmp41__1;
        apy1 = tmp42__1;
        arg0 = apy0;
        arg1 = apy1;
        funlab_js = 1; // __patsflab_QueenPuzzle__loop_19
        // ATStailcalseq_end
        break;
        // ATSbranchseq_end
      } // end-of-switch
      if (tmplab_js === 0) break;
    } // endwhile
    // ATScaseofseq_end
    if (funlab_js > 0) continue; else return tmpret39__1;
  } // endwhile-fun
} // end-of-function


function
QueenPuzzle__patsfun_23__23__1(arg0, arg1)
{
//
// knd = 0
  var tmpret49__1
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__patsfun_23
  tmpret49__1 = ats2jspre_add_int0_int0(arg0, 1);
  return tmpret49__1;
} // end-of-function


function
QueenPuzzle__test_safety_132(arg0, arg1)
{
//
// knd = 0
  var tmpret373
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__test_safety_132
  tmpret373 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__list0_iforall__66__1(arg1, QueenPuzzle__patsfun_135__closurerize(arg0));
  return tmpret373;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__list0_iforall__66__1(arg0, arg1)
{
//
// knd = 0
  var tmpret149__1
  var tmplab, tmplab_js
//
  // __patsflab_list0_iforall
  tmpret149__1 = QueenPuzzle__loop_67__67__1(arg1, 0, arg0);
  return tmpret149__1;
} // end-of-function


function
QueenPuzzle__loop_67__67__1(env0, arg0, arg1)
{
//
// knd = 1
  var apy0
  var apy1
  var tmpret150__1
  var tmp151__1
  var tmp152__1
  var tmp153__1
  var tmp154__1
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_QueenPuzzle__loop_67
    // ATScaseofseq_beg
    tmplab_js = 1;
    while(true) {
      tmplab = tmplab_js; tmplab_js = 0;
      switch(tmplab) {
        // ATSbranchseq_beg
        case 1: // __atstmplab60
        if(ATSCKptriscons(arg1)) {
          { tmplab_js = 4; break; }
        } // ifthen
        case 2: // __atstmplab61
        tmpret150__1 = true;
        break;
        // ATSbranchseq_end
        // ATSbranchseq_beg
        case 3: // __atstmplab62
        case 4: // __atstmplab63
        tmp151__1 = arg1[0];
        tmp152__1 = arg1[1];
        tmp153__1 = env0[0](env0, arg0, tmp151__1);
        if(tmp153__1) {
          tmp154__1 = ats2jspre_add_int0_int0(arg0, 1);
          // ATStailcalseq_beg
          apy0 = tmp154__1;
          apy1 = tmp152__1;
          arg0 = apy0;
          arg1 = apy1;
          funlab_js = 1; // __patsflab_QueenPuzzle__loop_67
          // ATStailcalseq_end
        } else {
          tmpret150__1 = false;
        } // end-of-if
        break;
        // ATSbranchseq_end
      } // end-of-switch
      if (tmplab_js === 0) break;
    } // endwhile
    // ATScaseofseq_end
    if (funlab_js > 0) continue; else return tmpret150__1;
  } // endwhile-fun
} // end-of-function


function
QueenPuzzle__patsfun_135(env0, arg0, arg1)
{
//
// knd = 0
  var tmpret380
  var tmp381
  var tmp382
  var tmp383
  var tmp384
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__patsfun_135
  tmp381 = ats2jspre_neq_int0_int0(env0, arg1);
  if(tmp381) {
    tmp383 = ats2jspre_sub_int0_int0(env0, arg1);
    tmp382 = ats2jspre_abs_int0(tmp383);
    tmp384 = ats2jspre_add_int0_int0(arg0, 1);
    tmpret380 = ats2jspre_neq_int0_int0(tmp382, tmp384);
  } else {
    tmpret380 = false;
  } // end-of-if
  return tmpret380;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__node_get_children(arg0)
{
//
// knd = 0
  var tmpret385
  var tmp394
  var tmplab, tmplab_js
//
  // __patsflab_node_get_children
  tmp394 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__N_get();
  tmpret385 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__int_list0_mapopt__47__1(tmp394, QueenPuzzle__patsfun_139__closurerize(arg0));
  return tmpret385;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__int_list0_mapopt__47__1(arg0, arg1)
{
//
// knd = 0
  var tmpret102__1
  var tmplab, tmplab_js
//
  // __patsflab_int_list0_mapopt
  tmpret102__1 = QueenPuzzle__auxmain_48__48__1(arg0, arg1, 0);
  return tmpret102__1;
} // end-of-function


function
QueenPuzzle__auxmain_48__48__1(env0, env1, arg0)
{
//
// knd = 1
  var apy0
  var tmpret103__1
  var tmp104__1
  var tmp105__1
  var tmp106__1
  var tmp107__1
  var tmp108__1
  var tmp109__1
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_QueenPuzzle__auxmain_48
    tmp104__1 = ats2jspre_lt_int0_int0(arg0, env0);
    if(tmp104__1) {
      tmp105__1 = env1[0](env1, arg0);
      // ATScaseofseq_beg
      tmplab_js = 1;
      while(true) {
        tmplab = tmplab_js; tmplab_js = 0;
        switch(tmplab) {
          // ATSbranchseq_beg
          case 1: // __atstmplab40
          if(ATSCKptriscons(tmp105__1)) {
            { tmplab_js = 4; break; }
          } // ifthen
          case 2: // __atstmplab41
          tmp107__1 = ats2jspre_add_int0_int0(arg0, 1);
          // ATStailcalseq_beg
          apy0 = tmp107__1;
          arg0 = apy0;
          funlab_js = 1; // __patsflab_QueenPuzzle__auxmain_48
          // ATStailcalseq_end
          break;
          // ATSbranchseq_end
          // ATSbranchseq_beg
          case 3: // __atstmplab42
          case 4: // __atstmplab43
          tmp106__1 = tmp105__1[0];
          tmp109__1 = ats2jspre_add_int0_int0(arg0, 1);
          tmp108__1 = QueenPuzzle__auxmain_48__48__1(env0, env1, tmp109__1);
          tmpret103__1 = [tmp106__1, tmp108__1];
          break;
          // ATSbranchseq_end
        } // end-of-switch
        if (tmplab_js === 0) break;
      } // endwhile
      // ATScaseofseq_end
    } else {
      tmpret103__1 = null;
    } // end-of-if
    if (funlab_js > 0) continue; else return tmpret103__1;
  } // endwhile-fun
} // end-of-function


function
QueenPuzzle__patsfun_139(env0, arg0)
{
//
// knd = 0
  var tmpret395
  var tmp396
  var tmp397
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__patsfun_139
  tmp396 = QueenPuzzle__test_safety_132(arg0, env0);
  if(tmp396) {
    tmp397 = [arg0, env0];
    tmpret395 = [tmp397];
  } else {
    tmpret395 = null;
  } // end-of-if
  return tmpret395;
} // end-of-function


function
param_initize()
{
//
// knd = 0
  var tmp408
  var tmp409
  var tmplab, tmplab_js
//
  // __patsflab_param_initize
  tmp408 = board_size_get();
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__N_set(tmp408);
  tmp409 = delay_time_get();
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__theDelayTime_set(tmp409);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__QueenPuzzleShow_node(arg0)
{
//
// knd = 0
  var tmp415
  var tmp443
  var tmp446
  var tmp449
  var tmp457
  var tmp459
  var tmp460
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzleShow_node
  tmp415 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__N_get();
  tmp443 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__node_length(arg0);
  ats2jspre_the_print_store_clear();
  tmp446 = ats2jspre_ML_list0_rforeach_method(arg0);
  tmp446[0](tmp446, QueenPuzzle__patsfun_155__closurerize(tmp415));
  tmp457 = ats2jspre_sub_int0_int0(tmp415, tmp443);
  tmp449 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__int_foreach_method__2__3(tmp457);
  tmp449[0](tmp449, QueenPuzzle__patsfun_160__closurerize(tmp415));
  tmp459 = document.getElementById("theStage");
  tmp460 = ats2jspre_the_print_store_join();
  xmldoc_set_innerHTML(tmp459, tmp460);
  return/*_void*/;
} // end-of-function


function
QueenPuzzle__print_dots_142(arg0)
{
//
// knd = 0
  var tmp417
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__print_dots_142
  tmp417 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__int_foreach_method__2__1(arg0);
  tmp417[0](tmp417, QueenPuzzle__patsfun_147__closurerize());
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__int_foreach_method__2__1(arg0)
{
//
// knd = 0
  var tmpret5__1
  var tmplab, tmplab_js
//
  // __patsflab_int_foreach_method
  tmpret5__1 = QueenPuzzle__patsfun_3__3__1__closurerize(arg0);
  return tmpret5__1;
} // end-of-function


function
QueenPuzzle__patsfun_3__3__1(env0, arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__patsfun_3
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__int_foreach__0__1(env0, arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__int_foreach__0__1(arg0, arg1)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_int_foreach
  QueenPuzzle__loop_1__1__1(arg0, arg1, 0);
  return/*_void*/;
} // end-of-function


function
QueenPuzzle__loop_1__1__1(env0, env1, arg0)
{
//
// knd = 1
  var apy0
  var tmp2__1
  var tmp4__1
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_QueenPuzzle__loop_1
    tmp2__1 = ats2jspre_lt_int0_int0(arg0, env0);
    if(tmp2__1) {
      env1[0](env1, arg0);
      tmp4__1 = ats2jspre_add_int0_int0(arg0, 1);
      // ATStailcalseq_beg
      apy0 = tmp4__1;
      arg0 = apy0;
      funlab_js = 1; // __patsflab_QueenPuzzle__loop_1
      // ATStailcalseq_end
    } else {
      // ATSINSmove_void
    } // end-of-if
    if (funlab_js > 0) continue; else return/*_void*/;
  } // endwhile-fun
} // end-of-function


function
QueenPuzzle__patsfun_147(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__patsfun_147
  ats2jspre_print_string(". ");
  return/*_void*/;
} // end-of-function


function
QueenPuzzle__println_dots_148(arg0)
{
//
// knd = 0
  var tmp428
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__println_dots_148
  tmp428 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__int_foreach_method__2__2(arg0);
  tmp428[0](tmp428, QueenPuzzle__patsfun_153__closurerize());
  ats2jspre_print_newline();
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__int_foreach_method__2__2(arg0)
{
//
// knd = 0
  var tmpret5__2
  var tmplab, tmplab_js
//
  // __patsflab_int_foreach_method
  tmpret5__2 = QueenPuzzle__patsfun_3__3__2__closurerize(arg0);
  return tmpret5__2;
} // end-of-function


function
QueenPuzzle__patsfun_3__3__2(env0, arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__patsfun_3
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__int_foreach__0__2(env0, arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__int_foreach__0__2(arg0, arg1)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_int_foreach
  QueenPuzzle__loop_1__1__2(arg0, arg1, 0);
  return/*_void*/;
} // end-of-function


function
QueenPuzzle__loop_1__1__2(env0, env1, arg0)
{
//
// knd = 1
  var apy0
  var tmp2__2
  var tmp4__2
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_QueenPuzzle__loop_1
    tmp2__2 = ats2jspre_lt_int0_int0(arg0, env0);
    if(tmp2__2) {
      env1[0](env1, arg0);
      tmp4__2 = ats2jspre_add_int0_int0(arg0, 1);
      // ATStailcalseq_beg
      apy0 = tmp4__2;
      arg0 = apy0;
      funlab_js = 1; // __patsflab_QueenPuzzle__loop_1
      // ATStailcalseq_end
    } else {
      // ATSINSmove_void
    } // end-of-if
    if (funlab_js > 0) continue; else return/*_void*/;
  } // endwhile-fun
} // end-of-function


function
QueenPuzzle__patsfun_153(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__patsfun_153
  ats2jspre_print_string(". ");
  return/*_void*/;
} // end-of-function


function
QueenPuzzle__println_qrow_154(env0, arg0)
{
//
// knd = 0
  var tmp441
  var tmp442
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__println_qrow_154
  QueenPuzzle__print_dots_142(arg0);
  ats2jspre_print_string("Q ");
  tmp442 = ats2jspre_sub_int0_int0(env0, 1);
  tmp441 = ats2jspre_sub_int0_int0(tmp442, arg0);
  QueenPuzzle__print_dots_142(tmp441);
  ats2jspre_print_newline();
  return/*_void*/;
} // end-of-function


function
QueenPuzzle__patsfun_155(env0, arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__patsfun_155
  QueenPuzzle__println_qrow_154(env0, arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__int_foreach_method__2__3(arg0)
{
//
// knd = 0
  var tmpret5__3
  var tmplab, tmplab_js
//
  // __patsflab_int_foreach_method
  tmpret5__3 = QueenPuzzle__patsfun_3__3__3__closurerize(arg0);
  return tmpret5__3;
} // end-of-function


function
QueenPuzzle__patsfun_3__3__3(env0, arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__patsfun_3
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__int_foreach__0__3(env0, arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__int_foreach__0__3(arg0, arg1)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_int_foreach
  QueenPuzzle__loop_1__1__3(arg0, arg1, 0);
  return/*_void*/;
} // end-of-function


function
QueenPuzzle__loop_1__1__3(env0, env1, arg0)
{
//
// knd = 1
  var apy0
  var tmp2__3
  var tmp4__3
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_QueenPuzzle__loop_1
    tmp2__3 = ats2jspre_lt_int0_int0(arg0, env0);
    if(tmp2__3) {
      env1[0](env1, arg0);
      tmp4__3 = ats2jspre_add_int0_int0(arg0, 1);
      // ATStailcalseq_beg
      apy0 = tmp4__3;
      arg0 = apy0;
      funlab_js = 1; // __patsflab_QueenPuzzle__loop_1
      // ATStailcalseq_end
    } else {
      // ATSINSmove_void
    } // end-of-if
    if (funlab_js > 0) continue; else return/*_void*/;
  } // endwhile-fun
} // end-of-function


function
QueenPuzzle__patsfun_160(env0, arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle__patsfun_160
  QueenPuzzle__println_dots_148(env0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__QueenPuzzleShow_clear()
{
//
// knd = 0
  var tmp462
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzleShow_clear
  tmp462 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__node_init();
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__QueenPuzzleShow_node(tmp462);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__QueenPuzzleShow_loop()
{
//
// knd = 0
  var tmp464
  var tmp465
  var tmp466
  var tmp467
  var tmp468
  var tmp471
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzleShow_loop
  tmp464 = ats2jspre_ref_get_elt(QueenPuzzle__statmp412);
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab158
      if(ATSCKptriscons(tmp464)) {
        { tmplab_js = 4; break; }
      } // ifthen
      case 2: // __atstmplab159
      // ATSINSmove_void
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab160
      case 4: // __atstmplab161
      tmp465 = tmp464[0];
      tmp466 = ATSPMVlazyval_eval(tmp465); 
      // ATScaseofseq_beg
      tmplab_js = 1;
      while(true) {
        tmplab = tmplab_js; tmplab_js = 0;
        switch(tmplab) {
          // ATSbranchseq_beg
          case 1: // __atstmplab162
          if(ATSCKptriscons(tmp466)) {
            { tmplab_js = 4; break; }
          } // ifthen
          case 2: // __atstmplab163
          // ATSINSmove_void
          break;
          // ATSbranchseq_end
          // ATSbranchseq_beg
          case 3: // __atstmplab164
          case 4: // __atstmplab165
          tmp467 = tmp466[0];
          tmp468 = tmp466[1];
          _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__QueenPuzzleShow_node(tmp467);
          tmp471 = [tmp468];
          ats2jspre_ref_set_elt(QueenPuzzle__statmp412, tmp471);
          _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__QueenPuzzleShow_loop_delay();
          break;
          // ATSbranchseq_end
        } // end-of-switch
        if (tmplab_js === 0) break;
      } // endwhile
      // ATScaseofseq_end
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__QueenPuzzleShow_loop_delay()
{
//
// knd = 0
  var tmp473
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzleShow_loop_delay
  tmp473 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__theDelayTime_get();
  setTimeout(_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__QueenPuzzleShow_loop, tmp473);
  return/*_void*/;
} // end-of-function


function
QueenPuzzleControl_start()
{
//
// knd = 0
  var tmp479
  var tmp480
  var tmp482
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzleControl_start
  param_initize();
  button_enable(QueenPuzzle__statmp400);
  button_disable(QueenPuzzle__statmp398);
  button_disable(QueenPuzzle__statmp401);
  tmp480 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__node_init();
  tmp479 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__node_dfsenum(tmp480);
  tmp482 = [tmp479];
  ats2jspre_ref_set_elt(QueenPuzzle__statmp412, tmp482);
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__QueenPuzzleShow_loop();
  return/*_void*/;
} // end-of-function


function
QueenPuzzleControl_pause()
{
//
// knd = 0
  var tmp486
  var tmp488
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzleControl_pause
  button_enable(QueenPuzzle__statmp401);
  button_disable(QueenPuzzle__statmp400);
  tmp486 = ats2jspre_ref_get_elt(QueenPuzzle__statmp412);
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab166
      if(ATSCKptriscons(tmp486)) {
        { tmplab_js = 4; break; }
      } // ifthen
      case 2: // __atstmplab167
      // ATSINSmove_void
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab168
      case 4: // __atstmplab169
      ats2jspre_ref_set_elt(QueenPuzzle__statmp410, tmp486);
      tmp488 = null;
      ats2jspre_ref_set_elt(QueenPuzzle__statmp412, tmp488);
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
QueenPuzzleControl_resume()
{
//
// knd = 0
  var tmp492
  var tmp495
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzleControl_resume
  button_enable(QueenPuzzle__statmp400);
  button_disable(QueenPuzzle__statmp401);
  tmp492 = ats2jspre_ref_get_elt(QueenPuzzle__statmp410);
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab170
      if(ATSCKptriscons(tmp492)) {
        { tmplab_js = 4; break; }
      } // ifthen
      case 2: // __atstmplab171
      // ATSINSmove_void
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab172
      case 4: // __atstmplab173
      ats2jspre_ref_set_elt(QueenPuzzle__statmp412, tmp492);
      tmp495 = null;
      ats2jspre_ref_set_elt(QueenPuzzle__statmp410, tmp495);
      _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__QueenPuzzleShow_loop();
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
QueenPuzzleControl_reset()
{
//
// knd = 0
  var tmp502
  var tmp504
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzleControl_reset
  param_initize();
  button_enable(QueenPuzzle__statmp398);
  button_disable(QueenPuzzle__statmp400);
  button_disable(QueenPuzzle__statmp401);
  tmp502 = null;
  ats2jspre_ref_set_elt(QueenPuzzle__statmp410, tmp502);
  tmp504 = null;
  ats2jspre_ref_set_elt(QueenPuzzle__statmp412, tmp504);
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__QueenPuzzleShow_clear();
  return/*_void*/;
} // end-of-function

// dynloadflag_minit
var _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__dynloadflag = 0;

function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__dynload()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // ATSdynload()
  // ATSdynloadflag_sta(_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__dynloadflag(453))
  if(ATSCKiseqz(_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__dynloadflag)) {
    _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__dynloadflag = 1 ; // flag is set
    QueenPuzzle__statmp328 = ats2jspre_ref(8);
    QueenPuzzle__statmp329 = ats2jspre_ref(500);
    QueenPuzzle__statmp398 = document_getElementById("button_start");
    QueenPuzzle__statmp399 = document_getElementById("button_reset");
    QueenPuzzle__statmp400 = document_getElementById("button_pause");
    QueenPuzzle__statmp401 = document_getElementById("button_resume");
    button_enable(QueenPuzzle__statmp398);
    button_enable(QueenPuzzle__statmp399);
    button_disable(QueenPuzzle__statmp400);
    button_disable(QueenPuzzle__statmp401);
    QueenPuzzle__statmp411 = null;
    QueenPuzzle__statmp410 = ats2jspre_ref(QueenPuzzle__statmp411);
    QueenPuzzle__statmp413 = null;
    QueenPuzzle__statmp412 = ats2jspre_ref(QueenPuzzle__statmp413);
  } // end-of-if
  return/*_void*/;
} // end-of-function


function
QueenPuzzle__dynload()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_057_doc_057_BOOK_057_ATS2FUNCRASH_057_LECTURE_057_10_055_10_057_CODE_057_QueenPuzzle_056_dats__dynload();
  return/*_void*/;
} // end-of-function


/* ATSextcode_beg() */
//
function
QueenPuzzle__initize()
{
//
QueenPuzzle__dynload(); return;
//
} // end of [QueenPuzzle__initize]
/* ATSextcode_end() */

/* ATSextcode_beg() */
//
jQuery(document).ready(function(){QueenPuzzle__initize();});
//
/* ATSextcode_end() */

/* ****** ****** */

/* end-of-compilation-unit */
